/*
 * ⛔ GENERATED by scripts/build-docs-site.mjs from the rendered pages.
 * Do not edit by hand.
 *
 * ⚠ There is no search service behind the box on this site. Typing in it
 * contacts nothing — the index is this file, which the page already loaded.
 */
window.SOURCERER_SEARCH_INDEX = [
 {
  "url": "features.html#numbers",
  "heading": "By the numbers",
  "text": "Each figure is counted from the app's own code and its record of changes. Nothing is rounded up. 5 ways to search one index: file name, content, audio, properties and similar names 72 file properties read from headers 32 programming languages its content search reads 65 audio file types in the Audio filter 7 match modes, from Match Case to Ignore Punctuation 3 operating systems: Windows, macOS and Linux 18 languages $0 price today"
 },
 {
  "url": "features.html#free",
  "heading": "Free today",
  "text": "Everything Sourcerer does today is free, for everyone: no paid tier, no subscription and no trial that runs out. Freally Sourcerer is free today. Future versions may be sold."
 },
 {
  "url": "features.html#inside",
  "heading": "What version 1.0 does",
  "text": ""
 },
 {
  "url": "features.html#index",
  "heading": "A live index of every disk",
  "text": "One index across your drives, kept current by each system's own change feed — the NTFS change journal on Windows, FSEvents on macOS, inotify and fanotify on Linux — so new, renamed and deleted files show up without a rescan. A drive you unplug stays searchable, and its results say which drive they are on."
 },
 {
  "url": "features.html#names",
  "heading": "File names, the way Everything finds them",
  "text": "Substrings, wildcards, regular expressions, AND, OR, NOT and grouping, with Everything's modifiers and spellings for size, date, extension, attributes and path, and seven match modes, from Match Case to Ignore Punctuation and matching Chinese, Japanese and Korean names by their reading."
 },
 {
  "url": "features.html#content",
  "heading": "The text inside files",
  "text": "Full-text search in PDFs, Word, Excel and PowerPoint files, plain text and Markdown, source code in 32 languages, JSON, CSV and YAML, mail, and inside zip, 7z and tar archives without unpacking them. A viewer steps through every hit in context."
 },
 {
  "url": "features.html#audio",
  "heading": "Audio by how it sounds",
  "text": "Measured, not tagged: loudness in LUFS, true peak, silence, dynamic range, length, codec, sample rate and channels. Sort by loudness or length, and play a file in the preview without leaving the list."
 },
 {
  "url": "features.html#properties",
  "heading": "What a file says about itself",
  "text": "Seventy-two properties read from file headers and searched like any other modifier: image size and camera data, video codec and duration, document author and page count, a program's architecture and signature, installer versions, shortcut targets, archive contents, fonts, mail headers and database tables. Any of them can be a column."
 },
 {
  "url": "features.html#similar",
  "heading": "Names that are only close",
  "text": "The similarity lens finds names near what you typed — a typo, a version number, a different prefix — and a search that finds nothing offers the closest real name as a one-click correction."
 },
 {
  "url": "features.html#results",
  "heading": "Everything you do with a result",
  "text": "Open, reveal, Open with, copy the path, the name, the contents or the file itself, open a terminal there, and run commands you define. Space opens Quick Look, audio and video play in the preview, and the result count opens statistics for the whole set."
 },
 {
  "url": "features.html#rename",
  "heading": "Rename, undo, tidy up",
  "text": "Rename a whole set of results with find and replace, regular expressions, counters and case changes, previewed first and refused if two names would collide. Undo reverses a rename, even after a restart. Find duplicates and empty folders straight from the index."
 },
 {
  "url": "features.html#everything",
  "heading": "At home if you come from Everything",
  "text": "Everything's search syntax, quick filters and file lists, in and out, plus CSV, plain text, playlists and NDJSON. A strict mode checks that a query uses only what Everything understands."
 },
 {
  "url": "features.html#cli",
  "heading": "A command line for scripts",
  "text": "The freally command speaks the same query language, prints JSON, NDJSON, CSV or NUL-separated paths, returns exit codes that mean something, and completes in bash, zsh, fish and PowerShell."
 },
 {
  "url": "features.html#portable",
  "heading": "Portable, if you want it",
  "text": "Run it from a USB stick: the index, settings, bookmarks and logs stay in a Data folder beside the app, and nothing is registered with the computer it is plugged into."
 },
 {
  "url": "features.html#languages",
  "heading": "Eighteen languages, light or dark",
  "text": "Menus, settings and every dialog switch language live, and Arabic lays out right to left. The app follows your system's light or dark theme, or keeps the one you choose."
 },
 {
  "url": "features.html#compare",
  "heading": "Side by side with the commercial tools",
  "text": "Freally Sourcerer 1.0 next to the commercial desktop search tools people use today. Every cell for another product comes from its maker's own pages, checked on 2 October 2026, and prices are US list prices as of October 2026 — except where a maker shows no US price, which the cell says. ✓ has it ◐ partly ✗ does not — not verified Feature Freally Sourcerer 1.0 Everything 1.5 in beta Listary Pro FileLocator Pro 2022 Copernic Desktop Search 8 HoudahSpot 6 DocFetcher Pro Price (USD, October 2026) Free today $0 freeware $19.95 one-time $79 one-time $28.99 per year, Basic — not verified €40 one-time, in euros only Windows, macOS and Linux ✓ has it Windows · macOS · Linux ◐ partly Windows ◐ partly Windows ◐ partly Windows ◐ partly Windows ◐ partly macOS ✓ has it Windows · macOS · Linux Finds files by name from an index kept current as files change ✓ has it NTFS · FSEvents · inotify ✓ has it NTFS ✓ has it NTFS ◐ partly index updated on a schedule — not verified ✓ has it Spotlight's index ✓ has it folders you choose Searches the text inside documents such as PDF and Office files ✓ has it ◐ partly not indexed, slow — not verified ✓ has it ✓ has it ✓ has it ✓ has it Finds audio by measured lo"
 },
 {
  "url": "features.html#why",
  "heading": "Why it is built the way it is",
  "text": "It listens instead of rescanning Every system already records the changes to its files. Sourcerer reads that record rather than walking your folders on a timer, so the index stays current without reading the disk again. It reads only what a question needs A file's properties are read the first time a search asks about it, from its header alone, and kept until the file changes. Nothing decodes a picture or opens a database's rows to answer how wide an image is. It says what it cannot see A folder that could not be read looks just like an empty one, so Sourcerer names the folders it skipped and why. A count that reached its limit is shown as a minimum, never as an exact number. It is careful with your files A rename is previewed and happens all at once or not at all, a delete goes to the Trash or Recycle Bin, and a command of your own runs as a program with arguments, never as a shell line, after asking you once. It stays on your machine No telemetry. The index lives on your own disk, and nothing about your files or your searches is sent anywhere. The update check only asks whether there is a newer version, and you can switch it off. It respects what you already know Everything's syn"
 },
 {
  "url": "features.html#coming",
  "heading": "What is still coming",
  "text": "Stated plainly, because a feature list that hides its gaps is not worth reading. This page is version 1.0, and Sourcerer is built one version at a time: the versions after 0.23 are still to come. Each one on the road to 1.0 is marked with its state. Two of the five lenses — the text inside files and names that are only close — are built but not yet connected to search. They are on this page because they are in 1.0. Done built and tagged, but not a download Planned still to be built, on the way to 1.0 The goal version 1.0 itself, and the first downloads this site will offer See every rung on the road to 1.0 What 1.0 does not do It reads properties from file headers only: it does not decode pictures, play video or render documents to find them, so a property a header does not carry cannot be searched. On macOS and Linux the first index walks every folder, so on a large disk it takes minutes rather than seconds. A portable copy does not update itself: replace its folder with a newer version. There are no downloads before version 1.0, and none on this page. Proprietary — All Rights Reserved. © Mike Weaver. Free to use today; future versions may be sold. Not open source. Everything is a"
 },
 {
  "url": "documentation.html#start",
  "heading": "Getting started",
  "text": "Sourcerer runs as two parts: a background indexer, freally-indexd , that keeps the index current, and the app you search from. The installer sets up both, and the indexer starts when you sign in. The app's id is com.freallyproducts.sourcerer , and your settings, bookmarks and index are kept in your system's app-data folder under that name. Versions up to 0.23.2 used io.mikeweaver.freally ; a newer version moves that folder to the new name the first time it starts, so nothing is indexed again. The first time the app opens, a short setup asks which folders to index, the hotkey that brings the app forward, and your language and theme. You can change all of them later in Settings. Then it builds the index. On Windows it reads the NTFS change journal, which is quick; on macOS and Linux it walks your folders, which takes minutes on a large disk. You can search while it works: results fill in as it goes. There are no downloads before version 1.0.0, and the source code is private."
 },
 {
  "url": "documentation.html#search",
  "heading": "Searching",
  "text": "Type in the search bar. Results appear as you type, grouped by lens, each group with how long it took. Every character narrows them; there is nothing to submit. Move through the results with the arrow keys, and press Enter or double-click a row to open the file with its usual app. Ctrl+Shift+F searches within the results you already have. Each term becomes a chip you can remove on its own, so you can step back without retyping. What you typed is shown in bold in the names and paths. A modifier such as ext:json narrows the list rather than being something you look for, so it is not marked. Esc clears the search bar."
 },
 {
  "url": "documentation.html#lenses",
  "heading": "The five lenses",
  "text": "Sourcerer has five lenses, all reading the same index. Today the file-name, audio and property lenses answer your searches; the content and similarity lenses are built but not yet connected to the search bar — that comes on the road to 1.0. File name: names and paths, with wildcards, regular expressions and Everything's modifiers. The fastest of the five. Content: the text inside PDFs, Word, Excel and PowerPoint files, plain text and Markdown, source code in 32 languages, JSON, CSV and YAML, mail, and zip, 7z and tar archives, without unpacking them. Not yet connected to the search bar. Audio: what an audio file measures — loudness in LUFS, silence, dynamic range, length, codec and sample rate — worked out the first time a search asks, and kept until the file changes. Properties: what a file's own header says — seventy-two properties across images, camera data, video, documents, programs, installers, shortcuts, archives, fonts, mail and SQLite databases. Similarity: names close to what you typed, for when you remember a file only roughly. Not yet connected to the search bar; until it is, a search that finds nothing offers the closest real name instead. Lenses can be switched on and"
 },
 {
  "url": "documentation.html#syntax",
  "heading": "The query syntax",
  "text": "Sourcerer understands voidtools' Everything syntax, and adds modifiers for its other lenses."
 },
 {
  "url": "documentation.html#syntax-basics",
  "heading": "The basics",
  "text": "Plain words match anywhere in the name, and every word must match: report 2024 . * matches any run of characters and ? one character, against the whole name: invoice_202?.pdf . A space or AND means both, | or OR either, ! or NOT neither, and parentheses group: (budget | forecast) !draft . regex: starts a regular expression: regex:^report-\\d+ . The syntax is Rust's, so there are no backreferences and no lookaround."
 },
 {
  "url": "documentation.html#syntax-modifiers",
  "heading": "Modifiers",
  "text": "Modifiers narrow results by what is known about a file. Combine as many as you like. Modifier What it matches Example size: Size, with kb, mb and gb, comparisons and ranges size:>50mb date: Date modified; dc: created, da: accessed date:today ext: Extension, one or several separated by semicolons ext:jpg;png attrib: File attributes, such as hidden attrib:h path: The full path contains the text path:projects parent: The file is directly inside that folder parent:src name^: name$: The name starts with, or ends with, the text name^:invoice lufs: dr: Measured loudness in LUFS, and dynamic range in dB lufs:<-14 length: An audio file's length length:>3:00 codec: rate: Audio codec, and sample rate in Hz codec:flac rate:48000 silence: How much of an audio file is silent, from 0 to 1 silence:<0.05 width: camera-model: … Any of the seventy-two properties; property: is the long form width:>1920 dupe: Files that share a name and a size; name-dupe: and size-dupe: match on one of the two dupe: ext:pdf empty: Empty files and folders; empty:roots finds the top of each chain of folders that holds no files empty:folder child-count: Folders by how many items they hold directly; descendant-count: at an"
 },
 {
  "url": "documentation.html#syntax-modes",
  "heading": "Match modes",
  "text": "The Search menu toggles Match Case ( Ctrl+I ), Match Whole Word ( Ctrl+B ), Match Path ( Ctrl+U ) and Match Diacritics ( Ctrl+M ). Ignore Punctuation lets foobar find foo-bar , and Ignore Whitespace lets myreport find my report . Both are off by default. Match CJK Phonetics finds Chinese, Japanese and Korean names by their reading: wenjian finds 文件. Enable Regex ( Ctrl+R ) treats the whole query as a regular expression. The regular expression builder beside the search bar tests a pattern against the names on screen as you type it, with the engine's own error if it is invalid."
 },
 {
  "url": "documentation.html#filters",
  "heading": "Quick filters",
  "text": "Quick filters limit results to a kind of file in one click: Audio, Compressed, Document, Executable, Folder, Image and Video. Each one carries every extension Everything's own filter does, and more — 65 audio types, 79 video, 77 image, 86 document and 70 archive. You can also type them, with the aliases you would guess: audio: , video: , image: , document: , executable: and archive: , or music: , photos: , docs: and zip: . Source code is not filed under Document, unlike in Everything; ext:c;cpp;h brings that set back. To keep a search of your own as a filter, choose Search → Add to Filters… , and edit them with Organize Filters… ( Ctrl+Shift+O )."
 },
 {
  "url": "documentation.html#bookmarks",
  "heading": "Bookmarks and the sidebar",
  "text": "Ctrl+D saves the current search as a bookmark, and Ctrl+Shift+B organizes them. Type : followed by a bookmark's name to run it. View → Sidebar shows a column with your bookmarks, the quick filters, your drives and your recent searches. Drag bookmarks to reorder them; click a drive to search only that drive. Recent searches are not recorded while Privacy Mode is on or search history is switched off."
 },
 {
  "url": "documentation.html#results",
  "heading": "Working with results",
  "text": "Every row is a real file on your disk. Right-click a row for what you can do with it: Open, Reveal in file manager, and Open with, which lists the apps your system has registered for that kind of file. Copy contents for a text file's body, Copy as file to paste the file itself into a folder, and Copy path list — one per line, quoted, space-separated or shell-escaped. View hits in context shows every match in a document; F3 and Shift+F3 step through them. Open terminal here opens a terminal in the file's folder. Commands of your own, from Settings → General → Custom Commands , with {path} , {dir} , {name} , {stem} and {ext} in their arguments. Each runs as a program with arguments, never as a shell line, and the app asks once before a program runs for the first time. Delete sends a file to the Trash or the Recycle Bin. Drag a row into another app as if from your file manager. Click a column header to sort, or use Ctrl+1 to Ctrl+9 ; the + at the end of the header row adds a property as a column. The View menu switches between details and thumbnails. Click the result count in the status bar for statistics on the whole result set: sizes and counts by type, the largest, oldest and newes"
 },
 {
  "url": "documentation.html#rename",
  "heading": "Renaming in bulk",
  "text": "Select the results to rename and press F2 . You describe the change once, and every old and new name is shown before anything touches the disk. Find and replace, as plain text or as a regular expression, with $1 , $2 for what it captured. {n} in the replacement numbers the files in the order of the preview; {n:03} pads the number to three digits. Change the case, and choose whether the rule applies to the name alone or to the extension too. By default extensions are left alone. Rows that would collide, overwrite a file or make a name the system refuses are marked, and nothing is renamed while any row is marked: the batch happens whole or not at all. Ctrl+Z undoes a rename, even after you restart the app, and Ctrl+Shift+Z redoes it. On Windows and Linux, Undo also brings a deleted file back from the Recycle Bin or the Trash. On macOS it cannot: restore the file from the Trash yourself."
 },
 {
  "url": "documentation.html#preview",
  "heading": "Preview and Quick Look",
  "text": "View → Preview ( Alt+P ) shows the selected file beside the results: pictures, text and code, and documents. Audio and video play in the pane, with play and pause, seeking, looping and volume. Audio draws a waveform you can click, with its codec, sample rate, channels and loudness beneath it. Space opens Quick Look, a large preview over the window. The arrow keys keep moving through the results while it is open, and Space or Esc closes it. On macOS, Quick Look also offers to open a file in the system's own Quick Look, for formats the system can show and Sourcerer cannot."
 },
 {
  "url": "documentation.html#drives",
  "heading": "Unplugged drives and file lists",
  "text": "When you unplug a drive, everything indexed on it stays searchable. Its results carry a badge with the drive's name, so they also answer which drive a file is on, and volume: searches one drive by its name. A drive that comes back on another letter or mount point is still recognised. File → Export Results… ( Ctrl+S ) saves the results as Everything's .efu file list, CSV, plain text, an M3U playlist of the audio files, or NDJSON for a script. File → Open File List… ( Ctrl+O ) searches inside a list, Everything's included, instead of the index, until you choose Close File List ."
 },
 {
  "url": "documentation.html#health",
  "heading": "Index Health and skipped folders",
  "text": "Tools → Index maintenance → Index Health… shows, for each place being watched, whether changes arrive live or only when it is rescanned, how far behind the index is, and how many changes were dropped. When something is wrong it says what, with a one-click rebuild where that is the fix. A folder the app cannot read looks exactly like an empty one. Permission Health… , in the same menu or from the \"folders skipped\" badge in the status bar, lists the folders that were skipped, the system's reason, and the fix. On macOS it checks whether Full Disk Access is granted and opens the right settings page if not."
 },
 {
  "url": "documentation.html#portable",
  "heading": "Portable mode",
  "text": "To run Sourcerer from a USB stick, put an empty file named portable.flag beside the app, or start it with --portable . The index, settings, bookmarks and logs then live in a Data folder beside the app, and nothing is registered with the computer: no background service, no link handler and no updater. Update a portable copy by replacing its folder. On macOS, the Data folder is made beside the app, not inside it, because writing inside an app breaks its signature."
 },
 {
  "url": "documentation.html#settings",
  "heading": "Settings and the hotkey",
  "text": "Tools → Options… ( Ctrl+, ) opens Settings, laid out like Everything's Options: a tree of panels on the left, a box above it that filters panels and options as you type, and OK , Cancel and Apply . The panels cover the look of the app, search behaviour, results, keyboard shortcuts, the folders, drives and exclusions that make up the index, each lens, privacy and updates, logs, backup and reset, and the language. A global hotkey brings the app forward from anywhere, with the search bar ready. Set it in Settings → General → Keyboard . A link of the form freally://search?q=… opens the app with that search."
 },
 {
  "url": "documentation.html#language",
  "heading": "Languages",
  "text": "Sourcerer speaks eighteen languages. Choose one in Settings → Locale and the whole app — menus, settings, dialogs and the status bar — switches at once, without a restart. Arabic lays the window out right to left."
 },
 {
  "url": "documentation.html#cli",
  "heading": "The command line",
  "text": "The freally command searches the same index as the app, through the same indexer, in the same query language. freally search \"report ext:pdf size:>1mb\" freally search --json --fields path,size \"*.rs\" freally search -0 \"ext:log\" | xargs -0 grep ERROR freally search --strict-everything \"report ext:pdf\" freally index status freally completions bash --json , --ndjson and --csv print results for scripts, -0 prints NUL-separated paths for xargs -0 , and --fields chooses the columns. The exit code says whether anything matched. --strict-everything refuses any query that uses something Everything does not have, and names it — the way to check that a query works in both. freally index shows the indexer's status and can pause, resume, verify, compact or rebuild it; freally bookmark saves, lists and deletes bookmarks. freally completions prints completions for bash, zsh, fish and PowerShell, including modifier names and your bookmarks."
 },
 {
  "url": "documentation.html#privacy",
  "heading": "Privacy and the network",
  "text": "There is no telemetry. The index is built and kept on your own computer, and nothing about your files or your searches is sent anywhere. The app asks whether a newer version exists once a day; in Settings → Privacy & Updates you can make that weekly, monthly or never, or check now. It asks before installing anything, naming both versions, and a portable copy never checks. Privacy Mode stops recording recent searches and switches off the property lens, which reads inside files."
 },
 {
  "url": "documentation.html#privacy-reports",
  "heading": "Reporting a problem",
  "text": "When the app runs into an error, its message has a Report button beside it. After a crash, the next launch offers Report or Dismiss . Report opens the report page, freallyproducts.com/freally-sourcerer/report/ , in your browser, with the technical facts already filled in: you can read them but not change them. You add what you were doing and, if you like, an email address. Nothing is sent unless you press Send on that page, and nothing is ever sent in the background."
 },
 {
  "url": "documentation.html#faq",
  "heading": "Questions",
  "text": ""
 },
 {
  "url": "documentation.html#faq-missing",
  "heading": "Why is a file missing from the results?",
  "text": "The first index may still be running: the status bar says so. Its folder may not be indexed: check the folders, drives and exclusions under Settings → Indexes . Its folder may be unreadable: open Permission Health… ."
 },
 {
  "url": "documentation.html#faq-smaller",
  "heading": "How do I make the index smaller?",
  "text": "Exclude folders full of files you never look for, such as node_modules and .git , under Settings → Indexes → Exclude ."
 },
 {
  "url": "documentation.html#faq-rebuild",
  "heading": "How do I start the index again?",
  "text": "Tools → Index maintenance → Force Rebuild Index… clears the index and builds it again from the start. Verify Index… and Compact Index… in the same menu check it and make it smaller. Proprietary — All Rights Reserved. © Mike Weaver. Free to use today; future versions may be sold. Not open source. Everything is a trademark of voidtools, named here only to compare. Freally Sourcerer is not affiliated with voidtools."
 },
 {
  "url": "changelog.html#unreleased",
  "heading": "[Unreleased]",
  "text": ""
 },
 {
  "url": "changelog.html#unreleased-added",
  "heading": "Added",
  "text": "[all platforms] The property lens (SRC-N01 … SRC-N15) — a fifth lens that reads container headers . width:>1920 , camera-model:R5 , author:lovelace , binary-type:arm64 , package-version:0.23 , broken-link: , entry-count:>1000 , font-scripts:cyrillic , from:ada@example.com , table-names:notes — seventy-two properties across eleven groups, every one of them typed as a modifier and every one of them also available as a result column. New crate freally-properties ; new property: DSL namespace for the generic form ( property:duration>60 , which is how you reach a key an older modifier already spells). Lazy and journal-invalidated. Nothing runs at index time. A property is read the first time a query asks about the file and cached against its mtime_ns after that, so the journal invalidates this lens without the lens ever subscribing to it — the same contract the audio lens has had since Phase 9. Misses are cached too: a folder of .txt files costs one open each per index generation rather than one per keystroke. Header-only. No parser decodes an image, demuxes a stream, renders a page, or reads a row of anyone's database. That line is what keeps width:>1920 answerable at typing speed over"
 },
 {
  "url": "changelog.html#unreleased-changed",
  "heading": "Changed",
  "text": "[all platforms] Filename search is dramatically faster for filtered queries. Measured at one million files, ext:json went 229 ms → 11 ms (20.7×), regex:^report- 76 ms → 9.5 ms (7.9×), *.rs 60 ms → 19 ms (3.1×), and report path:horizon 31 ms → 12 ms (2.6×). Plain one-word searches were already fast and are unchanged. Four things did it: those query shapes now produce a trigram seed instead of walking every indexed name; the name index carries each row's extension, size, date and attribute bits so those filters are answered from memory rather than by fetching every matching row out of SQLite; a directory's path is stored once instead of once per file it holds, which lets path: reject rows before they are fetched; and typing a longer word now narrows the previous keystroke's results instead of starting over. On Linux at 200 000 files every benchmark scenario is now under 8 ms. See the README's Search performance section for the full tables, the machine they were measured on, and why your machine will differ. [all platforms] Quick filters cover far more of your disk. Audio went from 22 extensions to 65, Video 23 → 79, Image 24 → 77, Document 25 → 86, Archive 23 → 70. Every extension Ev"
 },
 {
  "url": "changelog.html#unreleased-fixed",
  "heading": "Fixed",
  "text": "[all platforms] The Index Health panel pegged the main thread and hammered the daemon with index_health calls as fast as they could answer, instead of polling every 2 s. Its $effect started the poller inline, and the poller reads and writes the state the effect then subscribed to, so every answer restarted it. The panel was unusable and the app stopped responding while it was open. It had been shipping since M13; the e2e spec that would have caught it was test.fixme for an unrelated reason. [all platforms] path: and parent: allocated a lowercased string per hydrated row where path: already had a cached copy. [all platforms] Dialogs had two corner radii and three drop shadows, because Modal 's inline style prop silently beats the shell's own class. The prop is metrics-only now, and reaching past it is reported in dev. [all platforms] Two of the six View → Display format → Size format choices did nothing. The settings schema offers b | kb | mb | gb | auto_binary | auto_decimal ; formatBytes accepted a different five-value vocabulary, and every call site cast its way past the mismatch, so b and auto_decimal fell through to the binary auto branch. One vocabulary now, auto_decimal count"
 },
 {
  "url": "changelog.html#unreleased-security",
  "heading": "Security",
  "text": "[Windows] A shortcut's target is bytes out of an untrusted file, and answering broken-link: meant calling Path::exists on it. On Windows that hands a UNC path to the SMB redirector, which connects to the named host and offers the logged-in user's NTLM credentials — the classic shell-link forced-authentication primitive, and indexing alone would have triggered it, one handshake per file, with nothing clicked. Dropping a folder of .lnk files pointing at \\attacker\\share\\x into any watched directory was enough. Targets are now checked for UNC and URL forms before they are resolved, and a remote one leaves broken-link unset rather than probed. The same guard covers symlink targets, which arrive the same way inside any archive. [Windows] Authenticode verification ran with dwProvFlags: 0 . WTD_REVOKE_NONE suppresses CRL and OCSP but not the chain engine's AIA fetch, so a self-signed binary whose certificate named http://attacker/<unique>.cer would have turned indexing into a read receipt — landed, this IP, this time — from a daemon whose Privacy panel promises no outbound request. Now pinned to WTD_CACHE_ONLY_URL_RETRIEVAL | WTD_REVOCATION_CHECK_NONE ."
 },
 {
  "url": "changelog.html#unreleased-removed",
  "heading": "Removed",
  "text": "[all platforms] The Automatically remove offline volumes setting. It drove nothing — no code ever read it — and what it described is the opposite of the behaviour that shipped: an unplugged volume is deliberately kept as an offline catalog so its rows stay searchable and badged. Implementing it as written, defaulting to on, would have deleted the index for every unplugged drive."
 },
 {
  "url": "changelog.html#0-23-2-updater-key-rotation-and-ci-repair-2026-08-19",
  "heading": "[0.23.2] — Updater key rotation and CI repair (2026-08-19)",
  "text": "Same application as 0.23.1 , which was tagged but whose release was replaced rather than published. Everything in the 0.23.1 section below ships here; what follows is what changed on top of it."
 },
 {
  "url": "changelog.html#0-23-2-updater-key-rotation-and-ci-repair-2026-08-19-security",
  "heading": "Security",
  "text": "New updater signing key. Releases through 0.23.1 were signed with 9F291C936CFA28B7 , whose private half existed only as a GitHub repository secret. Repository secrets cannot be read back, so that key could not be copied, moved, or recovered — and it is now gone. Releases from 0.23.2 on are signed with E5035E2194EB7E04 , whose private half, password and public half are stored together outside GitHub. This breaks the updater for any install of 0.23.1 or earlier : the old binaries verify against a public key that no longer signs anything, so an update will fail signature verification rather than install. Reinstall from the downloads below. No install is known to be affected — download counts on every prior release matched routine link-checking."
 },
 {
  "url": "changelog.html#0-23-2-updater-key-rotation-and-ci-repair-2026-08-19-fixed",
  "heading": "Fixed",
  "text": "apt-get update could hang a Linux build indefinitely. The Ubuntu mirror the runner images prefer, azure.archive.ubuntu.com , returned nothing for the whole jammy index set for several hours, and with no timeout configured the step waited rather than failed — up to an hour against a 72-second baseline, four times, each needing a manual cancel. Builds now use archive.ubuntu.com , cap the step at ten minutes, and retry. The same step subsequently ran in 41 seconds. workflow_dispatch on the release workflow built the wrong tree. It takes a tag as input and is the documented way to rebuild a release, but its checkout step had no ref , so it checked out whatever branch it was dispatched from while naming the artifacts after the input tag. The wall-clock budget tests ran under full parallel load in CI. scripts/ci-local.mjs had been changed to run them alone — because nextest's process-per-test model puts the machine under sustained load and the assertion then measures the load — but CI kept running them with everything else, so the local gate had stopped predicting CI for exactly the tests hardest to reproduce. CI now splits its nextest step the same way, and the ceiling is widened on sha"
 },
 {
  "url": "changelog.html#0-23-2-updater-key-rotation-and-ci-repair-2026-08-19-documentation",
  "heading": "Documentation",
  "text": "README.md advertised v0.19.84 as the upcoming first release, four releases after the fact, and linked five documents that are not part of this repository. Download sizes on the site were 0.23.0 's, carried over with the links."
 },
 {
  "url": "changelog.html#0-23-1-build-4-groundwork-the-build-3-handoff-closed-out-2026-08-19",
  "heading": "[0.23.1] — Build 4 groundwork · the Build 3 handoff, closed out (2026-08-19)",
  "text": ""
 },
 {
  "url": "changelog.html#0-23-1-build-4-groundwork-the-build-3-handoff-closed-out-2026-08-19-build-4-groundwork-closing-out-the-build-3-handoff",
  "heading": "Build 4 groundwork — closing out the Build 3 handoff",
  "text": "Everything the previous handoff left open after v0.23.0, plus three bugs found while doing it. No new features; this is the cleanup pass that Build 4's property-lens work sits on top of. Fixed The Search → menu did nothing. SRC-M23 sent all seven match-mode flags from query.ts and taught the daemon's QueryRunParams to read all seven — but the Tauri command in between declared none of them, and Tauri drops invoke arguments a command does not name, silently. Every flag arrived at the executor as its serde default, so Match Case, Match Whole Word, Match Path, Match Diacritics, Match Phonetic, Ignore Punctuation and Ignore Whitespace each moved a checkmark and changed nothing else. commands/query.rs now has a QuerySearchOpts landing spot, and tests/unit/query_wire.test.ts pins the argument names on both sides. Match Case was wrong in both directions. With it on, an uppercase query returned nothing and a lowercase query still matched case-insensitively. The name index stores lowercased keys, so the candidate pre-filter had no cased text to test and rejected every row before hydration could look at the real name. This was known and deferred — a test asserted the broken behaviour and poin"
 },
 {
  "url": "changelog.html#0-23-0-build-3-must-have-stable-gate-slice-3-of-3-2026-08-03",
  "heading": "[0.23.0] — Build 3 · Must-Have stable gate, slice 3 of 3 (2026-08-03)",
  "text": "The last of the three Must-Have builds: SRC-M17 … SRC-M24. Ships as v0.23.0, the stable tag. SRC-M17 — portable mode. freally --portable , or an empty portable.flag file beside the binary, keeps the index, settings, bookmarks, journal cursors and logs in a Data/ folder next to the executable, and stops the app registering anything with the OS. All three binaries take the switch; the flag file is what makes a double-clicked zip or AppImage portable with no command line at all. The layout lives in freally_rpc::portable — the one crate the Tauri shell, the daemon and the CLI all already depend on. What portable mode deliberately does not do, each for a concrete reason rather than tidiness: No service, launchd plist, or systemd unit. freally-indexd install / uninstall / service all refuse in portable mode. Each writes a registration that outlives the USB stick and points at a path that will not be there next boot. uninstall is refused for the opposite reason: a portable copy never registered anything, so letting it through would deregister the installed copy on the host. No freally:// scheme registration. It writes a machine-level handler pointing at the executable's current path; unpl"
 },
 {
  "url": "changelog.html#0-23-0-build-3-must-have-stable-gate-slice-3-of-3-2026-08-03-build-3-closeout-what-the-review-passes-changed",
  "heading": "Build 3 closeout — what the review passes changed",
  "text": "/simplify ran four reviewers over the full build diff. Three of them independently flagged the same thing, and two findings were real defects rather than style: The sidebar dropped a bookmark's saved filters. applyBookmark re-implemented the dropdown's load flow and omitted typeFilterStore.setFromIds(...) , so opening a bookmark from the sidebar composed a different lens prefix than opening the same bookmark from the dropdown. Both now call one bookmarksStore.apply . visibleHits existed twice, with different answers. The Quick Look copy sorted; resultsStore.visibleHits — which export, select-all and the status-bar count read — did not. The two disagreed the moment a column sort was active. The sort moved into the store's getter and the copy is gone, which also makes that getter's \"the single answer to what the user is looking at\" comment true rather than aspirational. Two hand-synced strict-mode lists had already drifted. The parser's Freally-only modifier list carried volume: and report.rs 's copy did not, so a strict-everything query using volume: was rejected by the parser while the report the search bar renders from called it fine. Now one is_freally_only_modifier . Performance"
 },
 {
  "url": "changelog.html#0-23-0-build-3-must-have-stable-gate-slice-3-of-3-2026-08-03-build-3-closeout-what-security-review-changed",
  "heading": "Build 3 closeout — what /security-review changed",
  "text": "Two HIGH findings, both introduced by this build, both fixed. media_bytes was gated at the level the frontend can mint for itself. It returns the complete contents of a named file to the webview, and it was using Provenance::FrontendAsserted — the level files_whitelist_user_chosen hands out for any string the JS layer asks for. A compromised frontend dependency could have whitelisted ~/.ssh/id_ed25519 and then read it, with no dialog and no daemon involved. The other two commands that return file contents, content_document and copy_file_contents , already demanded QueryHit ; these two now do too. The legitimate caller is driven from result rows, which carry that level already, so nothing user-facing changes. The portable-mode socket sat directly in the shared temp directory. /tmp is mode 1777 and the name was an FNV hash of a guessable path, so any local account could bind it first. The transport authenticates the peer of a listener it owns; a client connecting out checked nothing, so squatting that path was a full daemon impersonation — and register_hit_paths turns anything arriving in a query:batch into Provenance::QueryHit , which is the gate on delete, rename, and every other d"
 },
 {
  "url": "changelog.html#0-22-0-build-2-must-have-stable-gate-slice-2-of-3-2026-08-02",
  "heading": "[0.22.0] — Build 2 · Must-Have stable gate, slice 2 of 3 (2026-08-02)",
  "text": "The second of the three Must-Have builds: SRC-M09 … SRC-M16. Cross-platform unless a per-OS note says otherwise. Full feature documentation is in docs/documentation.html ."
 },
 {
  "url": "changelog.html#0-22-0-build-2-must-have-stable-gate-slice-2-of-3-2026-08-02-added",
  "heading": "Added",
  "text": "SRC-M09 — machine-readable CLI output. freally search gains --json , --ndjson (one object per hit, streaming), --csv , --fields for column selection, -0 for xargs -0 , --limit / --offset , and meaningful exit codes (0 hits found, 1 none, 2 error). SRC-M10 — shell completions. freally completions <shell> prints completions for bash, zsh, fish and PowerShell, covering subcommands, flags, and — dynamically — the modifier keywords and saved-search names. SRC-M11 — typo-tolerant \"did you mean\". When the filename lens returns nothing, similarity candidates are re-ranked by bounded Damerau-Levenshtein distance and the closest is offered as a one-click correction. SRC-M12 — CJK phonetic matching. Typing wenjian or wj matches 文件 ; romaji matches kana; lead jamo matches Hangul. Readings are indexed as auxiliary name keys and are opt-in via Search → Match CJK Phonetics . Every conversion is a table lookup or arithmetic — Hangul decomposition is pure arithmetic on the Unicode syllable block, kana is an in-tree table, and Han readings come from the pinyin crate. Live change journaling. The index now updates as files change, rather than only when a scan runs. Every OS subscriber already implemen"
 },
 {
  "url": "changelog.html#0-22-0-build-2-must-have-stable-gate-slice-2-of-3-2026-08-02-changed",
  "heading": "Changed",
  "text": "volume: is a Freally-only modifier, so it is rejected under strict-Everything mode alongside similar: and the audio family. freally-journal exposes an OS-agnostic JournalPosition ( generation + offset ) on all three subscribers, so the daemon can detect a wrapped or recreated change stream without knowing the per-OS cursor type."
 },
 {
  "url": "changelog.html#0-22-0-build-2-must-have-stable-gate-slice-2-of-3-2026-08-02-known-gaps",
  "heading": "Known gaps",
  "text": "auto_remove_offline remains a no-op. Implementing it literally means purging an offline device's rows from the index; that is destructive, outside SRC-M14's scope, and its default of true would have applied to every existing install silently. Retention is what the feature wants and what the daemon already did. The four existing match-mode toggles (case, whole word, path, diacritics) are still UI-only — the daemon builds ExecOpts::default() and only SRC-M12's phonetic flag crosses the wire. Pre-dates Build 2; wiring them would change what existing queries return."
 },
 {
  "url": "changelog.html#0-21-0-build-1-must-have-stable-gate-slice-1-of-3-2026-07-31",
  "heading": "[0.21.0] — Build 1 · Must-Have stable gate, slice 1 of 3 (2026-07-31)",
  "text": "The first of the three Must-Have builds: SRC-M01 … SRC-M08. Cross-platform unless a per-OS note says otherwise. Full feature documentation is in docs/documentation.html ."
 },
 {
  "url": "changelog.html#0-21-0-build-1-must-have-stable-gate-slice-1-of-3-2026-07-31-added",
  "heading": "Added",
  "text": "SRC-M01 — hit-in-context content viewer. A full-document view for any file the extractor pipeline can read: every match highlighted, numbered lines, a match-count badge, F3 / Shift+F3 between matches, and jump-to-first-hit on open. Reached from the new result right-click menu. Highlighted terms are the query's literal and quoted atoms plus any active refinement chips. Bounded at 20,000 lines, and says so. SRC-M02 — search within results. Ctrl+Shift+F opens a second-stage box that narrows the set already on screen instead of re-running the query. Each term becomes a removable chip, so overshooting costs one click rather than a retype. A term containing a path separator matches the full path, otherwise the file name. Export and Select All read the refined set, so they never act on rows a chip scrolled away. (Organize Filters moves to Ctrl+Shift+O .) SRC-M03 — Everything-interop import/export. File → Export Results… picks its format from the extension chosen in the save dialog: .efu , .csv , .txt , .m3u / .m3u8 , .ndjson , .json . .efu is byte-compatible with voidtools' Everything — the literal Filename,Size,Date Modified,Date Created,Attributes header, CRLF rows, RFC-4180 quoting, an"
 },
 {
  "url": "changelog.html#0-21-0-build-1-must-have-stable-gate-slice-1-of-3-2026-07-31-fixed",
  "heading": "Fixed",
  "text": "[all platforms] KnownPaths had no writer. Phase 12 moved query hits into daemon notifications and nothing took over registering them, so every gated file-op rejected every result row. daemon.rs registers them as query:batch passes through. [all platforms] finalize_bootstrap did not advance applied_events , so a DirStats derived mid-scan stayed cached against the finished index — making empty:folder match every directory until the next journal batch. [all platforms] A dupe: in an unsupported position was silently stripped whenever another sat at top level ( dupe:name !size-dupe: returned zero hits with no error). The position guard now counts nodes rather than checking for absence. [all platforms] empty:roots reported nothing when the whole scanned tree was file-free: every row synthesises a counts entry for its parent, so the scan root's own parent looked indexed. [all platforms] Negating a predicate the name index cannot decide ( !empty:file , !size:>1mb ) returned zero rows — the name stage's \"let it through\" convention inverts to a reject under NOT . Pre-existing; Build 1 made it prominent. [all platforms] The hit viewer located matches in a lowercased copy of each line while th"
 },
 {
  "url": "changelog.html#0-21-0-build-1-must-have-stable-gate-slice-1-of-3-2026-07-31-security",
  "heading": "Security",
  "text": "[all platforms] wasmtime 44.0.1 → 47.0.3 in the custom-extractor host, closing RUSTSEC-2026-0222 (type indices can be mixed up between engines). Reachable only through a user-installed WASM extractor, but cargo-deny gates the build on it either way. [all platforms] File-list export and import now open their OS dialogs in Rust and act on the path they read back. Routing the destination through the webview meant file_list_export — Build 1's first write -side command — would overwrite any path the frontend named, and the registry entry it checked against was one the frontend could mint. KnownPaths also gained a Provenance dimension so a frontend-reachable grant can never confer write permission. [all platforms] run_custom_command takes a command id and resolves it against the backend's persisted settings. Accepting the program field over IPC made it an arbitrary-process-execution primitive: passing arguments through Command::arg is no protection when the caller also chooses the executable. See docs/SECURITY.md for the full threat-model delta."
 },
 {
  "url": "changelog.html#0-20-1-2026-07-10",
  "heading": "[0.20.1] — 2026-07-10",
  "text": "A patch release with no new features. It exists because v0.20.0 cannot fix itself: the updater endpoint is compiled into the shipped binary, so every install is checking a repository that does not exist and will never be offered an update. This is the build that repairs that, and it carries the security upgrades v0.20.0 predates."
 },
 {
  "url": "changelog.html#0-20-1-2026-07-10-security",
  "heading": "Security",
  "text": "[all platforms] quick-xml 0.39.4 → 0.41.0, closing RUSTSEC-2026-0194 (quadratic run time when checking a start tag for duplicate attribute names) and RUSTSEC-2026-0195 (unbounded namespace-declaration allocation in NsReader , a memory-exhaustion denial of service). Both are reachable: the docx and pptx extractors in freally-extractors feed untrusted Office XML straight into quick_xml::Reader . A hostile document could stall or exhaust the extractor host. Licence unchanged (MIT). [all platforms] calamine 0.34.0 → 0.36.0 — the first release that accepts quick-xml ^0.41 , and so a requirement of the above rather than a change in its own right. Licence unchanged (MIT). Its transitive zip moves 7 → 8; the workspace's own zip stays pinned at 5. [all platforms] crossbeam-epoch 0.9.18 → 0.9.20, closing RUSTSEC-2026-0204 (invalid pointer dereference in the fmt::Pointer impl for Atomic and Shared when the underlying pointer is invalid). Transitive and semver-compatible. Licence unchanged (MIT OR Apache-2.0). All three were fixed by upgrading. No advisory was added to deny.toml 's ignore list."
 },
 {
  "url": "changelog.html#0-20-1-2026-07-10-fixed",
  "heading": "Fixed",
  "text": "[all platforms] The auto-updater now points at the repository this project actually lives in. tauri.conf.json named MikesRuthless12/Freally , which does not exist, so latest.json resolved to a 404 and auto-update has never worked in any shipped build . Because the endpoint is baked into the binary, v0.19.84 and v0.20.0 keep polling the dead URL; only installs of this release or later can find an update."
 },
 {
  "url": "changelog.html#0-20-0-2026-07-01",
  "heading": "[0.20.0] — 2026-07-01",
  "text": "No notes were written for this release. What it changed is recoverable only from the commit range between v0.19.84 and v0.20.0 ; it is recorded here as absent rather than reconstructed, because a plausible summary written five months later is a guess wearing the same formatting as a fact. The one thing known about it for certain is in [0.20.1] below: its updater endpoint named a repository that does not exist, and it could not fix itself."
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21",
  "heading": "[0.19.84] — Phases 0–12 · the first public build (2026-06-21)",
  "text": "These notes sat under ## [Unreleased] from 2026-05-11 until 2026-08-21, through five tagged releases. They are not unreleased work and never were — the Phase 0 entry below ends \"First public tag will be v0.19.84 \", which is what this section documents. The tag was cut on 2026-06-21 without anyone renaming the heading, and every release after it inherited the same block. That was a live hazard, not untidiness. The release workflow builds its published notes by renaming ## [Unreleased] to the version being cut, so the next release would have shipped 533 lines of Phase 0–12 work — five months old, already in every install — as if it were new. It is dated to the tag it shipped in rather than split between v0.19.84 and v0.20.0 , because every entry in it predates both. > Everything below predates the Build 1–3 releases and was never promoted into a version section. It is left here untouched rather than back-filed into 0.21.0 – 0.23.0 on a guess; sorting it is its own pass."
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-task-098-full-fluent-i18n-end-to-end-across-all-18-locales-2026-05-11",
  "heading": "TASK-098 — full Fluent i18n end-to-end across all 18 locales (2026-05-11)",
  "text": "The 18-locale Fluent loader is now wired. Switching the language in Settings → Locale (or in the first-run wizard) re-renders every translated string in the UI — menus, status bar, settings panels, dialogs, and the wizard — without a restart. Loader. apps/freally-ui/src/lib/i18n/bundle.ts replaces the Phase-11 EN_FTL inline string with import.meta.glob(\"../../../../../locales/*/freally.ftl\", { query: \"?raw\", eager: true }) . All 18 .ftl files are inlined at build time; each FluentBundle layers en underneath as a fallback resource so a stray missing key surfaces in English rather than as a raw key string. vite.config.ts extends server.fs.allow to the workspace root so dev mode can read the locale tree that lives outside the package root. bundle.ts exports loadedLocales() for the test suite to assert the glob actually picked up all 18 files. Translation data — Standing Rule #4 lockstep. en/freally.ftl grew from 314 to 557 keys. The 243 additions cover wizard polish (hints, placeholders, \"Step N of N\"), status bar segments, lens / preview / bookmarks strings, the About / Connect dialogs, every UI/Home/Backup/Keyboard/History/Locale/Folders/Volumes panel hint + section title + toast, a"
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-phase-12-polish-pass-ux-reliability-and-live-apply-2026-05-11",
  "heading": "Phase-12 polish pass — UX, reliability, and live-apply (2026-05-11)",
  "text": "Major behavioral pass during a long debugging session. Most fixes are direct voidtools-Everything parity gains plus the foundational reliability work that makes the desktop app pleasant to run repeatedly during development. Single-instance + non-blocking daemon boot. kill_other_freally_instances() runs at the top of run() on Windows (taskkill /F /T against freally-ui.exe + freally-indexd.exe , filtered to PIDs ≠ self) so relaunching the app always starts from a clean slate without manual process killing. macOS / Linux stub for parity. Daemon::boot now spawns a dedicated freally-daemon-boot thread inside tauri::Builder::setup ; the setup hook returns immediately and the window appears right away. Previously the canonical-store replay could block the GUI thread for 10-15 s, tripping the Windows non-responsive-window watchdog and tearing the process down before any HWND existed. Client::connect is wrapped in a 500 × 40 ms retry loop on the consumer side so a slow daemon boot doesn't lose to a single connect race. Filter chips + Search menu — multi-select with OR composition. New lib/stores/type_filter.svelte.ts holds a Set<TypeFilterId> ; default is the full set (Everything mode). toQ"
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-added",
  "heading": "Added",
  "text": "[all platforms] Phase 12 settings dialog + real daemon IPC + custom-extractor framework + i18n. Replaces the Phase-11 mock IPC layer with a real freally-rpc length-prefixed JSON-RPC transport over a per-user Unix socket / named pipe and lands the full PRD §8.1-§8.27 settings dialog plus the Wasm-sandboxed custom-extractor host. New crate freally-rpc (under crates/freally-rpc/ ) — the foundation that lets the Tauri UI and the new freally CLI both speak the same protocol to a single freally-indexd instance. frame.rs : u32-BE length-prefixed framing with a 16-MiB hard payload cap so a hostile peer cannot OOM the server with a single 4-GiB length prefix. jsonrpc.rs : JSON-RPC 2.0 Request / Response / Notification envelopes; the ResponseEnvelope untagged enum disambiguates a single frame as either a response or a server-pushed notification. service.rs : the Service trait that freally-indexd implements; NotificationSink lets a method handler push asynchronous notifications down the same connection. server.rs : per-connection accept loop with a bounded outbound queue ( PER_CONN_OUT_QUEUE = 256 ); spawns a writer task per connection and a notification fan-in task that forwards Notification"
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-fixed-phase-8-review-pass",
  "heading": "Fixed (Phase 8 review pass)",
  "text": "[all platforms] Phase 8 plain-text extractor now detects encoding before the cap-overshoot truncation runs. The previous version unconditionally ran a from_utf8 -in-a-loop trim on the truncated buffer regardless of encoding — for UTF-16 input that overshot the 5 MiB cap (≈ 2.5 M codepoints), the loop popped bytes until it found a UTF-8-shaped prefix, often leaving the buffer at an odd byte length, which decode then rejected as ExtractError::Malformed . With the encoding-aware truncation, UTF-16 trims to an even-byte boundary and UTF-8 trims to a codepoint boundary via the new trim_to_utf8_boundary helper. New regression utf16_le_overshoot_truncates_at_even_boundary_not_malformed locks the contract in. [all platforms] Phase 8 archive-peek + structured-data extractors now sanitize line-break control characters ( \\n / \\r / \\0 ) in archive entry names, CSV field values, and JSON / YAML scalar string values via the new extractors::util::sanitize_inline helper. A hostile zip / 7z / tar entry could previously declare a name containing \\n and inject phantom rows into the search blob (one entry impersonating many); the same bug existed at the CSV / JSON / YAML scalar surface where quoted fi"
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-fixed-phase-5-review-pass",
  "heading": "Fixed (Phase 5 review pass)",
  "text": "[all platforms] Phase 5 query parser now treats ! after ) as a prefix-NOT — (a)!b parses as (a) AND !b to match voidtools-Everything's documented behavior. Previously the byte-and-token boundary check omitted RParen , so the trailing !b collapsed into a single literal !b and the negation was silently dropped (Standing Rule #8 regression). New parser-test bang_after_rparen_is_not locks the contract in. [all platforms] Phase 5 plan cache no longer mutates the cached plan when match_mode.match_path is on. The seed-clear that lets a path-search bypass the trigram pre-filter now runs at execute-time only — the ExecPlan stays a pure function of the query string, so two concurrent callers with the same query but different match_path settings can no longer poison each other's cached plan. New wiring-test plan_cache_survives_match_path_toggle covers it. [all platforms] Phase 5 parse_iso_day rejects calendar-impossible days (Feb 30, Apr 31, non-leap Feb 29, …) up-front via a new days_in_month validator (Howard Hinnant's epoch-day arithmetic accepted any 1-31 day for any month, silently rolling overflow forward). Voidtools rejects these — Standing Rule #8 regression. New parser-test invalid_c"
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-changed",
  "heading": "Changed",
  "text": "[all platforms] freally-journal facade now re-exports the canonical JournalEvent / JournalError / JournalSubscriber from the Windows subscriber on cfg(windows) , the macOS subscriber on cfg(target_os = \"macos\") , and the Linux subscriber on cfg(target_os = \"linux\") . Other Unix targets keep the typed-but-stubbed portable_stub surface. [macOS + Linux] freally-indexd Run subcommand's --root <path> flag (preferred on macOS / Linux) now also drives the Linux journal subscriber; the existing --volume continues to work as a synonym on every OS."
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-fixed-phase-4-review-pass",
  "heading": "Fixed (Phase 4 review pass)",
  "text": "[all platforms] Phase 4 Index::apply now degrades a JournalEvent::Rename whose old_path was never indexed (cross-batch rename pair the journal subscriber couldn't pair) into Delete(old) + synthetic Create(new) rather than writing a Tantivy / name-index row with no files.db row of truth. Mirrors the journal subscribers' published cross-batch fallback contract; new smoke rename_of_unknown_path_degrades_to_delete_plus_create covers it. [all platforms] Phase 4 EventQueue::close no longer races against wait_for_events / push_blocking — closed is now stored inside the same Mutex as the queue itself instead of a sibling Mutex , so close() 's notify_all cannot land between a waiter's \"is the queue empty?\" check and its Condvar::wait . New smoke close_unblocks_push_blocking_and_wait_for_events and try_push_after_close_refuses lock the contract in. [all platforms] Phase 4 Manifest::load_or_default now treats a JSON-parse error as missing-and-warn rather than a hard IndexError::Manifest that would block Index::open . The SQLite canonical store and Tantivy meta.json are the durable record; the manifest is a per-commit cache that Index::commit rewrites every cycle. New smoke torn_manifest_does_"
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-fixed",
  "heading": "Fixed",
  "text": "[Windows-only] USN-journal rename pairing on Phase 1's freally-journal-win now classifies the OLD-name half of a rename (and any FILE_DELETE record) as terminal : emit immediately without requiring USN_REASON_CLOSE . NTFS does not emit a closing record for the old-name session — there's nothing more to wait for at that path. Previously the classifier returned Pending for RENAME_OLD_NAME records that lacked CLOSE , the pairing table stayed empty, and the matching RENAME_NEW_NAME | CLOSE record silently dropped via ? . Net effect: JournalEvent::Rename was never emitted for any in-tree rename. Diagnostic re-run on a real NTFS volume confirmed the fix; the integration test realtime_create_modify_rename_delete_round_trip now passes end-to-end and is no longer #[ignore] 'd. [Windows-only] JournalEvent::Delete now consults the rename pairing table by FRN before falling back to the record's build_path result. Modern Windows uses POSIX-semantic NtSetInformationFile deletes which internally rename the file to a $.dF{guid} temp name before issuing FILE_DELETE ; without this lookup the consumer would see Delete $.dF{guid} instead of Delete <original_path> . Defensive: the test that surfaced th"
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-deprecated",
  "heading": "Deprecated",
  "text": "_(empty)_"
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-removed",
  "heading": "Removed",
  "text": "_(empty)_"
 },
 {
  "url": "changelog.html#0-19-84-phases-0-12-the-first-public-build-2026-06-21-security",
  "heading": "Security",
  "text": "_(empty)_"
 },
 {
  "url": "changelog.html#how-to-update-this-file",
  "heading": "How to update this file",
  "text": "Every phase must add at least one user-perspective entry under [Unreleased] before being marked complete. Use sections Added / Changed / Fixed / Deprecated / Removed / Security . Cite new crates and licences. Mark API breaks **BREAKING:** first. When tagging a release, rename [Unreleased] to [X.Y.Z] — YYYY-MM-DD and add a fresh [Unreleased] block."
 },
 {
  "url": "changelog.html#how-to-update-this-file-cross-platform-parity-rule",
  "heading": "Cross-platform parity rule",
  "text": "Freally ships on Windows, macOS, and Linux from v0.19.84. Every entry must call out platform scope with a bracketed prefix. Use one of: [all platforms] — change applies to Windows, macOS, and Linux. [Windows-only] , [macOS-only] , [Linux-only] — single-OS work. Acceptable mid-phase; should be balanced by the other OSes in subsequent phases. [Windows + macOS] , [macOS + Linux] , [Windows + Linux] — partial coverage. Do — explicit scope prefix: Added — [all platforms] Filename-similarity lens via bigram MinHash. Added — [Windows-only] NTFS USN journal subscriber. Don't — no scope prefix (phase review will reject): Added — Filename-similarity lens. Phase reviews will reject changelogs without explicit platform scope. Proprietary — All Rights Reserved. © Mike Weaver. Free to use today; future versions may be sold. Not open source. Everything is a trademark of voidtools, named here only to compare. Freally Sourcerer is not affiliated with voidtools."
 }
];
