/* ⛔ GENERATED by kit/build.mjs from the rendered pages. Do not edit.
 * ⚠ There is no search service behind the box: the index is this file. */
window.FREALLY_SEARCH_INDEX = [
 {
  "url": "features.html#search",
  "heading": "Search a name, not a genre",
  "text": "2,413 artists, producers and genres in one search, through aliases and typos. Before you press anything, a card says what that name does: its song forms, its ways of arranging, its section lengths and its signature moves."
 },
 {
  "url": "features.html#modes",
  "heading": "Not one template per genre",
  "text": "A genre is arranged several ways — radio cut, mixtape cut, club cut, switch-up, minimal — unless it genuinely has only one, and then its card says why. Artists and producers add their own, and every press is a new seed you can keep and paste to get the same arrangement back."
 },
 {
  "url": "features.html#live",
  "heading": "The whole record, performed live",
  "text": "Press play and Unloop performs the record over your own audio, in time with your project: intros, hooks, drop-outs, 808 cuts, filter sweeps, stutter builds, tape stops, half-time and beat switches. No move clicks, and none adds latency."
 },
 {
  "url": "features.html#pattern",
  "heading": "Even on a loop that never moves",
  "text": "FL Studio's pattern mode and Ableton's session view loop without moving the song position. Unloop counts the loops itself, so the whole record still plays over the 8 bars going round."
 },
 {
  "url": "features.html#parts",
  "heading": "One loop, or every part",
  "text": "One stereo loop is enough: Unloop arranges it in low, mid and high bands. Put an instance on each part's track instead and one of them conducts them all as one record, with a full console of faders and lamps."
 },
 {
  "url": "features.html#timeline",
  "heading": "The timeline is yours",
  "text": "Move, copy, split, resize and fade every clip with three-handle fades; ride clip, part and master faders; draw automation on 12 lanes per part; reorder sections; lock what you like and reroll the rest. Unlimited undo, and an autosave that survives a crash."
 },
 {
  "url": "features.html#take",
  "heading": "Hear it, then take it",
  "text": "Preview the arrangement inside Unloop while your DAW is stopped. Print it as WAV, AIFF, FLAC or MP3, the mix or one stem per part, and drag the song, one part or one section straight onto your tracks. A receipt goes beside every file."
 },
 {
  "url": "features.html#midi",
  "heading": "Audio or MIDI, one switch",
  "text": "Flip to MIDI and the same arrangement becomes a multi-track MIDI song template, read from your own loop's notes, with section markers. The Velocity Doctor gives each part the right kind of velocity: accents and ghosts on drums, a steady 808, even chords."
 },
 {
  "url": "features.html#shelf",
  "heading": "One loop, many arrangements",
  "text": "Each loop is saved once, as its own project, with a shelf of named arrangements: switch between them on the next bar, compare any two, and carry one to another loop as a file. The Loop Library holds every loop you have, ready to audition."
 },
 {
  "url": "features.html#standalone",
  "heading": "A standalone app and a web app",
  "text": "Drop up to eight stems or MIDI files and arrange them without a DAW. With no DAW to follow, Unloop suggests the artist's tempo and can stretch your loop to it; the Loop Doctor finds seam clicks, clipping and a tempo that does not add up."
 },
 {
  "url": "features.html#redream",
  "heading": "Re-Dream and the Arrangement Doctor",
  "text": "Re-Dream gives three new takes on the arrangement you have, keeping its shape. Add synthesized risers and impacts, your own producer tag and beat switches, then let the Arrangement Doctor point out a late hook or a section that never changes, with a fix."
 },
 {
  "url": "features.html#offline",
  "heading": "Offline, private, no AI",
  "text": "No account, no telemetry and no model: a rule-based planner and classic signal processing, checked by a build gate. The plugin and the standalone never go online; the one exception is an update check that stays off unless you switch it on, run by a separate program. Compare Side by side with the commercial tools Freally Unloop 1.0 next to five products sold today that arrange a loop, vary it or write whole songs: ArrangerKing (an arrangement plugin), Loopmix (a loop-remix plugin), Songen (a beat-making app), and Suno and SOUNDRAW (AI song generators). Every cell for another product comes from its maker's own pages, checked on 1 and 2 October 2026, and prices are US dollars before tax, as listed on 2 October 2026. Feature Freally Unloop 1.0 ArrangerKing Loopmix Songen Suno SOUNDRAW Price (USD, October 2026) Free today $54 $69 Free tier; Premium $89.99 a year Free tier; Pro $10 and Premier $30 a month From $16.99 a month; stems from $35.99 Turns your own loop into a whole song for you, writing no new music has it partly you set every mute partly loop variations does not writes its own does not writes new music does not writes its own Arranges in the style of an artist or producer you"
 },
 {
  "url": "documentation.html#start",
  "heading": "Getting started",
  "text": "Freally Unloop runs inside your DAW as a CLAP or VST3 plugin, or as an AU on macOS, and on its own as a standalone app. Put it on the track that plays your loop: until you press Generate it passes the track's audio through exactly as it arrives, so it is safe to leave in place. Version 0.6.0 is built to be used in a DAW, with audio. MIDI arrives in version 0.7.0; arranging stems dropped into the standalone app, and the web app, arrive in version 0.8.0. There are no downloads before version 1.0.0, and the source code is private."
 },
 {
  "url": "documentation.html#agreement",
  "heading": "The licence agreement",
  "text": "The first time Unloop opens it shows its End User License Agreement, which is written in English. Read it to the end and Agree becomes available. If you decline, Unloop is paused: nothing is arranged, and your audio still passes through unchanged. Choose Read it again whenever you are ready. Your answer is kept on your computer, for every copy of Unloop on it."
 },
 {
  "url": "documentation.html#window",
  "heading": "The window",
  "text": "Along the top are the loop project menu (the folder button), the Arrangement menu, the search, the mode, and Undo and Redo; on the right, the tempo, the clock and Settings (the gear). In the middle is the arrangement map: the record's sections, a lane for each part, and its moves. Along the bottom is the console: Generate, a strip for each part, the master section and the seed. Settings holds the language, the theme — System, Dark or Light — the interface sounds and the list of keyboard shortcuts."
 },
 {
  "url": "documentation.html#name",
  "heading": "Picking a name",
  "text": "Type in the search to find any of 2,413 artists, producers and genres. Aliases and near misses find them too, and letters such as Ø, ß and Ł fold, so \"mo\" finds MØ. With the search empty it offers your recent names and the flagship models. Use the arrow keys and Enter, or click. Each name has a model card: the modes it arranges in and how often each is drawn, its typical song forms, its signature moves, the parts it drives, where its data comes from and how confident it is. A name with little data of its own inherits from its genre, and the card shows the chain."
 },
 {
  "url": "documentation.html#generate",
  "heading": "Generate, modes and seeds",
  "text": "Press Generate and Unloop plans the whole record for the name you picked: every section, which parts play in it, and every move. Choose a mode first — Radio cut, Mixtape cut, Club / DJ cut, Switch-up, Minimal and more, depending on the name — or leave it on Any mode and Unloop draws one. Every plan has a seed, 16 hexadecimal digits in the console, and each press of Generate draws a new one. The same loop, name, mode and seed always give the same arrangement: copy a seed to keep an arrangement or to send it to a collaborator, and paste one to get it back."
 },
 {
  "url": "documentation.html#tempo",
  "heading": "Tempo and the clock",
  "text": "In a DAW, Unloop always plays at your project's tempo and never changes it. The tempo chip says whether your tempo is in the range the name usually works at — counting half and double time as a match — and, if it is not, which tempo to set your DAW to, with a button to copy it. Unloop needs to know how long your loop is: it asks, and assumes 8 bars until you say. The clock follows your DAW's song position, or counts the loops itself when the position does not move — FL Studio's pattern mode, or Ableton Live's session view — so the whole record still plays over a loop going round. Auto decides for you; choose Song or Loop to decide yourself."
 },
 {
  "url": "documentation.html#parts",
  "heading": "One loop, or every part",
  "text": "On one track with a finished stereo loop, Unloop arranges it in three bands — low, mid and high — and the map says so. For the full set of moves, put an instance on each part's track and give each one a role: drums, bass, melody, chords and so on. Unloop suggests one from the track's name. Instances on the same channel perform one record together: the first conducts, and every other follows its plan to the sample and plays only its own part's moves. The console shows a strip for each, with its fader and lamps. When your DAW runs plugins in separate processes, instances meet through a shared file on your computer, never the network. If another project's plan is already on a channel, Unloop says so and offers another channel."
 },
 {
  "url": "documentation.html#capture",
  "heading": "Capture and preview",
  "text": "After Generate, each instance captures one cycle of its loop — the music arriving on its track, never its own output — and from then on plays the record from memory. The LIVE / CAPTURED chip says where it stands, with Recapture and Forget capture. A loop longer than 64 seconds cannot be captured, and a stop, a jump or a tempo change during a capture starts it again at the next play. If the loop coming in is no longer the one captured, the chip asks: Loop changed — recapture? Nothing is replaced while it plays; recapturing is your press. With your DAW stopped, the play, pause, stop and loop keys in the master section — or the space bar — preview the whole record inside Unloop, every instance on the channel together. Click the map's ruler to jump, or loop a section. Press play in your DAW and it takes over at once."
 },
 {
  "url": "documentation.html#print",
  "heading": "Print, drag and receipts",
  "text": "PRINT in the master section opens Print & export. Choose what to print — the mix, the stems, any of the parts, a section or the whole record — and the format: WAV (16-bit, 24-bit or 32-bit float), AIFF, FLAC or MP3, at the captured sample rate or one you pick. It renders through the very code that plays live, so the file is what you heard. Cancel leaves nothing behind. You can dither when the bit depth drops, put a safety limiter at −1 dBTP on the mix, and write receipts. File names come from a template you can edit, and by default no file name carries an artist's or producer's name. When the export is done, the print meter shows the mix's peak, true peak and loudness. To skip the dialog, use the drag rack: drag the mix, the stems, one part or one section straight onto your tracks. The files are rendered before the drag begins, as 24-bit WAV by default. A receipt, a small .unloop-receipt.json file, goes beside every export and every drag. It holds the versions, the name, mode and seed, and the fingerprints needed to make the same record again. Receipts are on by default; you can turn them off in the dialog."
 },
 {
  "url": "documentation.html#projects",
  "heading": "Loop projects and the Loop Library",
  "text": "Save loop project… in the loop project menu (the folder button) saves the loop — its parts as 24-bit FLAC — with every arrangement over it, as one .unloop file. Open loop project… brings it back exactly. Saving never overwrites a file: a name that is taken gets (2). The Loop Library, in the same menu, lists every .unloop project and every WAV, AIFF, FLAC, MP3 and MIDI file in the folders you add, with its bars, tempo, tags and how often it has been arranged. Search and filter it; click a loop to hear it inside Unloop (the arrow keys walk the list, Esc stops), and Arrange it when it is exactly one loop. It only ever reads your folders. MIDI loops are listed now and become arrangeable in version 0.7.0. Make a loop from a longer file… cuts a loop out of a longer recording: pick a start bar, a length of 1, 2, 4, 8 or 16 bars and the tempo, hear the cut on repeat, then Arrange it as a new loop project. The file itself is never changed. Recent Projects lists what you opened or saved, newest first. One that has moved shows as missing, and Remove from list takes the row away — never the file."
 },
 {
  "url": "documentation.html#timeline",
  "heading": "Editing the timeline",
  "text": "Every clip on the map is yours to edit. Click to select it, Shift-click or drag a marquee for more, or press Ctrl/Cmd+A for all. Drag a clip to move it on the snap (hold Alt to move it freely), drag an edge to resize it — the loop repeats past its length — and Alt-drag inside it to slip it. S splits at the edit cursor. The clip's menu — right-click, Shift+F10 or the menu key — holds Cut, Copy, Paste, Clone after, Duplicate in place, Delete, Split at the cursor, Reverse, Lock, Reset to plan, Colour and Rename. A clip pasted onto a lane its part cannot go on is offered the lanes it can. Snap to the bar, the beat, an eighth or a sixteenth note, their triplets, or nothing; zoom in and out, or fit the whole record. Where clips meet, Unloop crossfades them over 3 ms, and with snapping off an edge lands on the loop's nearest zero crossing, so no edit makes a click."
 },
 {
  "url": "documentation.html#fades",
  "heading": "Fades and faders",
  "text": "Each end of a clip has three fade handles, as in Freally MIDI Master's Song Arrangement: the length on the clip's top edge and the curve on the fade itself. They never cross, at any clip length. Drag a clip's gain handle from −∞ to +6 dB — hold Shift for fine steps, double-click for 0 dB. The console has a fader for each part and a master fader. Every move is heard while you drag, and is one undo step when you let go. The console's faders work like every Freally app's: from −96 dB to +6 dB, even in decibels, 0.1 dB a step, the whole range over 200 pixels — hold Shift for a quarter of that. Double-click or Alt-click a fader for 0 dB; on the keyboard, Page Up and Page Down move it a tenth of the way, Home sends it to the floor and End to the top. The number under a fader is what you set; the meter beside it shows what plays — green below −12 dBFS, yellow to −3, red above — and its clip light stays on until you click it."
 },
 {
  "url": "documentation.html#automation",
  "heading": "Automation",
  "text": "Open Automation, pick a part and what to move, add a lane and draw on it. Each part has lanes for volume, pan, width, low-pass and high-pass cutoff, resonance, reverb and delay sends, drive, crush, gate depth and pitch; the master has volume and a low-pass. Draw points, or select and move them; bend the line between two; stamp a shape over a range — a ramp, an S-curve, a sine, triangle, square or saw, or random steps — and copy and paste a range. A move's own sweep or dive can be edited on the lane it plays. Automation is read sample by sample, live and in a print alike."
 },
 {
  "url": "documentation.html#sections",
  "heading": "Sections",
  "text": "Open a section's menu from its header, or press M, to rename it, change its kind or its length, move it earlier or later, insert a new section before or after it, remove it or lock it. You can also drag a section to reorder it: everything in it goes with it."
 },
 {
  "url": "documentation.html#reroll",
  "heading": "Lock, reroll and moves by hand",
  "text": "Lock a section or a clip you like, and Reroll draws the rest again. It never touches a locked section or a clip you edited, and never moves a neighbour. What changed then lists every part and move it changed, section by section. Add move opens a palette of every move, this arrangement's own first: place one on the moves strip, then drag, stretch or delete it. Select a move to open its inspector — its start, its length, its parts and its own settings, such as a filter's range or a stutter's steps — and Audition it while the preview plays."
 },
 {
  "url": "documentation.html#history",
  "heading": "Undo, redo and autosave",
  "text": "Every change in the Song Arrangement view is one step of unlimited undo and redo. The Undo and Redo buttons at the top name the step, or press Ctrl/Cmd+Z and Ctrl/Cmd+Shift+Z (or Ctrl+Y). The history is saved with your DAW project. Every change is also written to your computer at once, so if your DAW closes before you save, the project reopens on your last change and says so. If that change was really another copy's — an older project reopened after Save As — choose Keep the saved version."
 },
 {
  "url": "documentation.html#shelf",
  "heading": "Many arrangements on one loop",
  "text": "The Arrangement menu holds every arrangement of the loop you have open: New, Duplicate, Rename, Delete, Switch — on the next bar while playing, at once when stopped — and Compare, an A/B between any two. Each arrangement keeps four snapshots, A to D: click one to recall it, or Shift-click to keep the arrangement there. Export arrangement… writes one arrangement as an .unarr file, without its loop. Import arrangement… lays one over the loop you have open, finding each section, clip, move and lane by what it is, and lists anything that had no place."
 },
 {
  "url": "documentation.html#midi",
  "heading": "The MIDI view and the Velocity Doctor",
  "text": "Press MIDI in the header to see the arrangement as notes: each clip on the timeline shows the notes its part plays, and every handle in the drag rack — the mix, a part, a section — now carries a MIDI file instead of audio. Press it again for the audio. The toggle changes only what you see and drag: no clip, section, fade or marker moves, and nothing joins your undo history. MIDI in the header: the loop read as notes, why each part was read as it was, and the audio again. The notes come from your loop. Unloop reads each captured part as notes with Freally MIDI Master's audio-to-MIDI road — classic signal analysis, no AI — while your DAW keeps working. The MIDI panel lists every part and why it was read as it was (on the drum channel, plays like a kit, the lowest voice, split by pitch…), and says plainly what the road cannot do: it writes no counter-melody from audio, a sung line is not written as notes, chords are spelled plainly, and a hit hidden under a louder one is lost. If you have the loop as MIDI, drop the .mid file on the MIDI panel, or choose it there: its notes are used for this part instead, split exactly as Freally MIDI Master splits a file. It is kept with your project "
 },
 {
  "url": "documentation.html#keys",
  "heading": "Keyboard shortcuts",
  "text": "Every edit in the Song Arrangement view works without a mouse. In Unloop, press ? for this sheet; on a Mac, Ctrl/⌘ is ⌘ . Everywhere Undo Ctrl/⌘ + Z Redo Ctrl/⌘ + Shift + Z or Ctrl + Y Show this sheet ? Play or pause the preview while your DAW is stopped Space Close a dialog, a card or a panel Escape Song Arrangement view Select the next clip ] Select the previous clip [ Select the clip on the lane above Alt + ↑ Select the clip on the lane below Alt + ↓ Select every clip Ctrl/⌘ + A Select nothing, or let go of a drag Escape Move the selected clips earlier by the snap ← Move the selected clips later by the snap → Move the selected clips to the lane above ↑ Move the selected clips to the lane below ↓ Shorten the clip from its end Shift + ← Lengthen the clip at its end Shift + → Lengthen the clip at its start Alt + Shift + ← Shorten the clip from its start Alt + Shift + → Raise the clips’ gain = or + Lower the clips’ gain - Move the edit cursor earlier , Move the edit cursor later . Split at the edit cursor S Hold the clip’s fade handles F Reverse the selected clips R Lock or unlock the selected clips L Copy the selected clips Ctrl/⌘ + C Cut the selected clips Ctrl/⌘ + X Paste at the "
 },
 {
  "url": "documentation.html#sounds",
  "heading": "Interface sounds and the title bar",
  "text": "Opening or closing Settings, a menu or a dialog, and showing or hiding the Loop Library, each makes a short sound — the same sounds in every Freally app — that lasts exactly as long as the move on screen. They play through Unloop's own output in your DAW, never into your record: not into a Print, a capture, a stem, a drag or an offline bounce. In Settings you can switch them off, set their level, or keep Quiet while playing on (it is on to start with), so they stay silent while your DAW or the preview plays. With reduced motion turned on in your system, nothing moves and a short tick plays instead. Interface sounds in Settings: on or off, their level, and Quiet while playing. In the standalone app the title bar follows the theme — dark in the dark theme, light in the light one — and carries no title, because the turning name at the top of the window is the title. Inside a DAW the plugin's window belongs to the DAW and keeps its title."
 },
 {
  "url": "documentation.html#look",
  "heading": "Themes, controls and motion",
  "text": "Unloop has two themes, dark and light, on Freally green; in Settings choose Dark, Light or System, which follows your computer. Its faders, knob and meters, the GENERATE, REROLL and PRINT keys, and the sliders and switches are the Freally family's — the same controls as Freally Flipcopy, rendered for each theme — so every Freally app looks and presses the same. Pressing REROLL and moving a fader, then Light, Dark and System. In Settings, Motion has two choices. Speed: Quick turns the name at the top twice as fast. Reduced motion: Reduce lays the name flat and stills every animation; Follow the system does the same whenever your computer asks for less motion. Quick turns the name at the top faster; Reduce lays it flat."
 },
 {
  "url": "documentation.html#language",
  "heading": "Languages",
  "text": "Unloop speaks eighteen languages. It starts in your system's language; to choose another, open Settings with the gear and pick one."
 },
 {
  "url": "documentation.html#privacy",
  "heading": "Privacy and the network",
  "text": "Unloop has no account and no telemetry, and the plugin and the standalone app contain no networking code at all. Your loops, your projects and your records never leave your computer, and a loop, a project or an export folder on a network drive is refused before anything on it is touched. It keeps its own files in your app-data folder (%APPDATA%\\Freally Unloop on Windows): the licence answer, your preferences, Recent Projects, the Loop Library's index, the capture cache (at most 2 GB) and the files instances meet through. It never writes into your loop folders; exports and projects go where you choose. It contains no AI of any kind: every arrangement is planned by deterministic rules over researched arrangement data and performed by classic signal processing, and a build gate fails if a machine-learning library is ever added."
 },
 {
  "url": "documentation.html#report",
  "heading": "Reporting a problem",
  "text": "When Unloop itself fails — it could not write one of its own files, an export or a drag went wrong, a loop it should read could not be read, or the window crashed — the error has a Report button. It opens the report page in your browser with the facts already filled in: where it failed, the version and your system, signed so they cannot be changed. You add what happened, and nothing is sent until you press Send there. Unloop itself sends nothing. If Unloop crashed, the next time it opens it offers to report it once; Dismiss forgets it. An error that only says no to something you asked — a name that cannot be a file, a folder that is not there — has no Report button. Only release builds can make a report."
 },
 {
  "url": "documentation.html#limits",
  "heading": "Known limitations",
  "text": "A loop's key is not read yet, so default file names leave the key out. A drag shows no picture of what you are dragging yet. A reverb or delay throw on the last bar is cut at the record's last bar line; the print does not ring on past it. On a second monitor at another display scale, the editor sizes itself from the primary display. Unloop has not yet been worked through by hand in every DAW, on every system. That is the release candidate's job, before 1.0.0."
 },
 {
  "url": "changelog.html#unreleased-added",
  "heading": "Added",
  "text": "Feature videos in the manual — six short, silent videos that loop beside their chapters, filmed in the real app: the themes and the console's controls, motion, the interface sounds, the MIDI view, a MIDI loop and the Velocity Doctor. npm run showcase films them from the release standalone, on a profile of its own, with a drawn cursor. v0.7.0 2026-10-06 X: MIDI Flip the view to MIDI and drag the same arranged record out as a multi-track MIDI song. The notes come from your loop, read by Freally MIDI Master's audio-to-MIDI road (no AI anywhere in it), or from a MIDI loop you drop on the instance. Every move, fade and section lands in the file honestly, and each part's velocities are set to the right kind. 0.6.7 , the look, ships inside this tag."
 },
 {
  "url": "changelog.html#0-7-0-2026-10-06-x-midi-added",
  "heading": "Added",
  "text": "The AUDIO/MIDI toggle — the MIDI chip in the header. Pressed, the lanes draw each clip's notes and every drag handle (the mix, a role, a section) carries a Standard MIDI File instead of a WAV. It changes the view and nothing else: no clip, section, fade or marker moves, and undo is untouched. The MIDI song template — one Type 1 file: a conductor track with the tempo, the time signature and a marker per section, then one track per part, named by part, with drums on channel 10. Each clip's notes follow its slip, repeat and reverse. A mute, drop-out or cut takes notes out, a stutter or roll repeats them with ramped velocities, and half-time stretches them. Filters, volume, pan and sends become controllers. The same seed gives the same bytes, and the MIDI plan is the audio plan, one tiling. Honest about what MIDI cannot say. A move with no MIDI meaning (a rewind, a reverse, lo-fi) is a marker in the file and a badge on the map. A move MIDI can only approximate (a tape stop, a pitch dive) is a pitch bend plus a marker, flagged in its tooltip. The MIDI panel counts them. Fades in MIDI — a fade scales the velocities of the notes it covers, along the same curve the audio follows, or, by ch"
 },
 {
  "url": "changelog.html#0-7-0-2026-10-06-x-midi-changed",
  "heading": "Changed",
  "text": "Loop projects are schema 7 : they keep the MIDI view, the MIDI loop and the velocity choices. A schema 6 project opens in the audio view with the model's velocities. A receipt now says which format was exported, and for a MIDI file, what it held (the song, a part or a section) and how its fades were written. The contact is freallyproducts@gmail.com everywhere (the licence, the EULA, the security policy, the plugin's details a DAW shows, the crate metadata)."
 },
 {
  "url": "changelog.html#0-7-0-2026-10-06-x-midi-security",
  "heading": "Security",
  "text": "A dropped MIDI loop is bounded : refused over 40 KB, by the page before it is sent and by the plugin before it is decoded, parsed by engine 's reader, and kept only in the loop project. v0.6.7 2026-10-06 L: The look Unloop now looks and presses like the rest of the Freally family. Its keys, faders, knob, meters, slider and switches are Freally Flipcopy's, and so are its light and dark themes on Freally green, copied as they are and never redrawn here. Shipped inside 0.7.0 ; this rung has no tag of its own."
 },
 {
  "url": "changelog.html#0-6-7-2026-10-06-l-the-look-added",
  "heading": "Added",
  "text": "Motion settings — Speed ( Normal or Quick : Quick turns the title twice as fast; a popover's or panel's move stays as long as its sound) and Reduced motion ( Follow the system or Reduce : Reduce lays the title flat and stills every animation)."
 },
 {
  "url": "changelog.html#0-6-7-2026-10-06-l-the-look-changed",
  "heading": "Changed",
  "text": "The look is Freally Flipcopy's, copied, never redrawn. The console's faders, knob and meters, its GENERATE, REROLL and PRINT keys, and Settings' slider and switches are Flipcopy's components drawing the Freally playbook's Blender renders, in a light set and a dark set. Every other button stays a plain labeled button, and the preview's play, stop and loop are plain icon buttons. A gate holds every copied file to Flipcopy's, byte for byte. Two themes, light and dark, on Freally green ( #79d920 ), from the shared Freally UI kit Flipcopy uses: its grounds, glass panels, chassis and glow. The console follows the theme, and its lamps have daylight colours of their own. Every pair passes WCAG 2.1 AA in both themes. No skins (the owner, 2026-10-06). The faders work like the rest of the family's : −96 to +6 dB, even in dB, 0.1 dB a step, the whole range over 200 pixels ( Shift for a quarter of that), a double-click or Alt -click back to 0 dB, Page Up / Page Down a tenth of the travel, Home to the floor and End to the top. The cap shows what you set, and the meter beside it shows what plays. The meters are Flipcopy's : green below −12 dBFS, yellow to −3, red above, and a clip light at 0 dBFS"
 },
 {
  "url": "changelog.html#0-6-7-2026-10-06-l-the-look-security",
  "heading": "Security",
  "text": "The editor's pages allow inline styles ( style-src 'self' 'unsafe-inline' ). Flipcopy's hardware set declares each render's address in one stylesheet of the page's own, and that address depends on where the page is served, so a hash cannot pin it. Scripts are still 'self' only, and nothing else loosened. v0.6.5 2026-10-05 U: Sounds, the title bar & Report this Unloop now sounds and stands like the rest of the Freally family, and when it fails, it says so in a way you can report. Opening a popover or a dialog and showing the Loop Library each make the family's own short sound, exactly as long as the move; the standalone's title bar is dark in dark mode, with no title; and an error that is Unloop's own fault offers Report ."
 },
 {
  "url": "changelog.html#0-6-5-2026-10-05-u-sounds-the-title-bar-report-this-added",
  "heading": "Added",
  "text": "Interface sounds — the Freally family's one set, soft glassy , the same files in every Freally app: a popover or dialog opening and closing (Settings and every header and console popover, the Roles & bus panel, the project menu, the export dialog, the shortcut sheet) and the Loop Library shown and hidden. Each lasts exactly as long as its move, both read from one timing table. They play through Unloop's own output — never the PC's speakers behind the DAW's back — and never into the record: not in a Print, a capture, a stem or a drag-out, not in an offline bounce, not while bypassed. On by default; Settings has their switch, their level and Quiet while playing (on). With reduced motion, a short tick plays instead. Popovers, dialogs and the Loop Library move — they open and close over the family's moves (the Loop Library slides from its edge, the other way in a right-to-left language); with reduced motion they appear at once. The standalone's title bar is dark in dark mode and follows the theme live, and it carries no title — the turning wordmark is the title. Inside a DAW the plugin window's title stays the DAW's. Report this. When Unloop itself fails — a file of its own it could no"
 },
 {
  "url": "changelog.html#0-6-5-2026-10-05-u-sounds-the-title-bar-report-this-changed",
  "heading": "Changed",
  "text": "Every shared crate from Freally MIDI Master moved to shared-v10 (from shared-v5 ; freally-report from shared-v7 ). The roster data is unchanged, but a plan's dataset version names the tag, so every plan hash changed with it — a golden change in the snapshots' header lines only. The app id is com.freallyproducts.unloop (it was com.mikeweaver.freally-unloop ): a DAW project saved with an earlier pre-release looks for the old id and will not find the plugin. Nothing has been released yet. The road to 1.0 gains a rung : the skins and the hardware set move to v0.6.7 , which copies them from Freally Flipcopy once the owner has approved them there. v0.6.0 2026-10-01 T: The timeline The arrangement is yours to edit, every piece of it, and every output hears exactly what you edited. Move, copy, paste, clone, resize, slip and split clips; draw fades with MIDI Master's three handles; ride clip, part and master faders; draw automation; reshape the sections; lock what you like and reroll the rest; place moves by hand — every change one undo step, undone and redone as far as you like. A loop's project now holds a shelf of arrangements you switch between on the next bar, and an arrangement travel"
 },
 {
  "url": "changelog.html#0-6-0-2026-10-01-t-the-timeline-added",
  "heading": "Added",
  "text": "The timeline. Every clip on the map is editable: select (click, Shift , a marquee, Ctrl/Cmd+A ), move (on the snap; Alt bypasses it; a lane change only between parts that may share one), delete, clone after the selection ( Ctrl/Cmd+D ), duplicate in place ( Shift+D ), copy, cut and paste at the edit cursor (an incompatible lane is offered the lanes it may go on, never changed silently), resize from either edge (the loop repeats past its length), slip ( Alt -drag), split ( S ), reverse, rename, colour and Reset to plan — from the context menu too. A moved, slipped or reversed clip is heard from its own place in the captured loop. Fades exactly like MIDI Master's Song Arrangement : three handles a side — length on the clip's top edge, curvature on the path — that never cross, at any clip length; the shortest clip is a 64th note. Faders. An on-clip gain handle (−∞ to +6 dB, Shift fine, double-click back to 0 dB), the console's part faders and a master fader — on one fader law — every move heard while it is dragged and one undo step when it ends. Automation lanes for volume, pan, width, low- and high-pass cutoff, resonance, reverb and delay sends, drive, crush, gate depth and pitch on "
 },
 {
  "url": "changelog.html#0-6-0-2026-10-01-t-the-timeline-changed",
  "heading": "Changed",
  "text": "Project state is schema 6, and a .unloop document schema 2 : edits, history, the shelf, and each arrangement's edits and snapshots. Older projects and files open as they were. The shared Freally crates move to shared-v5 — MIDI Master's shared-v3 to shared-v5 , and its nih-plug fork at df472391 : the editor's page stays under its window when the window is moved (WebView2 is told the window moved and put back under it), freally-extract and nih-plug's process_mode() are available, and the roster snapshot is re-taken at the new tag (its data is unchanged). The repository is public — MikesRuthless12/freally-unloop , All Rights Reserved; the shared crates come from the public MikesRuthless12/freally-midi-master , and the macOS release build needs no secret. Continuous integration runs on GitHub , on Windows, Linux and macOS, for every push and pull request — every gate, clap-validator and pluginval at strictness 10 on every runner (the AU on macOS). No commit carries [skip ci] any more. v0.5.0 2026-09-28 C: Capture, preview & print The MVP is complete. Every instance captures one cycle of its loop and plays the record from memory; the whole arrangement previews inside Unloop while your D"
 },
 {
  "url": "changelog.html#0-5-0-2026-09-28-c-capture-preview-print-added",
  "heading": "Added",
  "text": "Capture. After Generate , each instance records exactly one cycle of its loop — loop_bars of music from the next loop boundary, to the sample at 44.1, 48 and 96 kHz — straight from your DAW's input, never Unloop's own output. The LIVE / CAPTURED chip beside the preview keys says where it stands (waiting, capturing, captured, stale) with Recapture and Forget capture . A stop, a seek or a tempo change mid-take throws the partial take away and tries again at the next play; a loop longer than 64 seconds is refused in words. Captures are kept by their content (BLAKE3) in your app-data folder, up to 2 GB, least recently used out first; a host project saves only the hash, and one whose capture is gone asks you to play the loop once. Loop changed — recapture? When the loop coming in is not the one captured for two cycles running (compared band by band), the chip says so. Nothing is ever replaced while it plays; recapturing is your press. Played from memory. Once captured, an instance plays the record from its capture, locked to the host's position — no drift on a loop whose cycle is not a whole number of samples, a crossfade when the source changes, and still zero added latency. The memory"
 },
 {
  "url": "changelog.html#0-5-0-2026-09-28-c-capture-preview-print-changed",
  "heading": "Changed",
  "text": "Every plan hash moved — the plans did not. A plan names the Freally MIDI Master tag its data was imported at ( mm-shared-v2/… , was mm-shared-v1/… ); the data is unchanged, so every name, mode and seed arranges exactly as before. The 24 golden plans changed in their header line only. The shared Freally crates move to shared-v2 — MIDI Master's freally-encode (every byte of every exported file) and freally-drag (the native drag on Windows, macOS and Linux), carved out of MIDI Master for Unloop, beside the engine and the webview adapter at the same tag. The engine now builds on its own, so the Linux CI's full-checkout workaround is gone. One performer for every output. The schedule and the performer moved into a crate of their own, performance , which live playback, the preview and Print all play through; render holds the Print, the encoders' front door, the decoder, the meter, the limiter and the .unloop container. The bus file's layout moves to 2 ( <letter>.v2.mmap ), carrying each instance's capture hash and the channel's preview clock. An Unloop v0.4.0 and this one never share a channel across processes — update every copy together. A host project saved by v0.4.0 opens here (its s"
 },
 {
  "url": "changelog.html#0-5-0-2026-09-28-c-capture-preview-print-fixed",
  "heading": "Fixed",
  "text": "Unloop's editor keeps a browser profile of its own ( %APPDATA%\\Freally Unloop\\webview , and its macOS and Linux equivalents), no longer the folder of Freally MIDI Master's: the two side by side could leave one editor blank (\"The requested resource is in use\")."
 },
 {
  "url": "changelog.html#0-5-0-2026-09-28-c-capture-preview-print-security",
  "heading": "Security",
  "text": "From the phase's code and security review: Every file is read as hostile — a .unloop , a loop in the library, a cached capture, a preference: size-capped before it is read, every length checked against the bytes present before anything is allocated from it, and refused rather than guessed at. The decoder and the project reader never panic on a file (random-bytes and lying-length tests hold them to it), and a project's parts are decoded one at a time, only when one is used, so a small hostile file cannot make the host hold gigabytes. Nothing touches the network. A network share ( \\\\server\\share ) or a device path is refused before anything touches it; a project, a loop, a folder of loops or an export folder on a mapped network drive is refused before any file on it is opened or even looked at (a look is a connection); and an export folder that resolves to a share — a link or a junction into one — is refused before anything is written. Nothing is overwritten and nothing is left half-written. A taken file name gets (2) ; files are written beside and moved into place, and a failed or cancelled export takes back what it wrote. File names are plain names on every system (no device names,"
 },
 {
  "url": "changelog.html#0-5-0-2026-09-28-c-capture-preview-print-known-limitations",
  "heading": "Known limitations",
  "text": "The v0.5.0 host checks — capture, preview, print, formats and drag-out in FL Studio, Ableton Live and Reaper — are written ( Live-To-Do.md § 4) and not yet worked by hand; drag-out on macOS and Linux is written but has not been dropped into a real DAW. The drag shows no picture of what you are dragging yet. A reverb or delay throw on the last bar is cut at the record's last bar line; the print does not ring on past it. Part faders are at unity in the mix until the console's faders arrive ( v0.6.0 ); a loop project holds one arrangement until the shelf does. A loop's key is not known until detection arrives ( v0.7.0 ), so the default file names leave {key} out until then. On a second monitor at another display scale, the editor sizes itself from the primary display. On macOS nothing yet holds the plugin while a dialog or an export runs ( SECURITY.md , Known limitations ). v0.5.0 ships for Windows and Linux only; no macOS build (AU, CLAP, VST3 or standalone) is made for it. v0.4.0 2026-09-26 R: Roles & the Conductor Put Unloop on each part's track and they perform one record together. The first instance conducts; every other follows its plan to the sample and plays only its own part'"
 },
 {
  "url": "changelog.html#0-4-0-2026-09-26-r-roles-the-conductor-added",
  "heading": "Added",
  "text": "Roles. Each instance takes a role — the whole loop, the drums (or one piece of the kit), bass, melody, counter-melody, chords, vocal, FX or the producer tag — from its strip or from the Roles & bus panel, including another instance's role from any window. Two of one kind are numbered (\"Melody 2\") and share a lane. A part the plan writes for a role nobody took is marked on the map as performed nowhere. The Conductor. The first instance on a channel conducts: it makes the plan, and every other instance receives its inputs and hash — never audio — rebuilds the same plan and reports back. A plan changed in any window is sent to the Conductor and reaches everyone. When the Conductor goes, the next instance takes the baton within a second and carries the record on. Sample-aligned. Every instance places every move edge on the same sample, whatever block size its track runs at; a kit move played on a drum bus is split across that bus's bands as the one-instance record would play it. The bus lamp and the Roles & bus panel. Green: the instances share this DAW's memory. Amber: the host keeps each plugin in a process of its own (Bitwig's sandbox, Reaper's bridging, FL's bridging, macOS's AU ho"
 },
 {
  "url": "changelog.html#0-4-0-2026-09-26-r-roles-the-conductor-changed",
  "heading": "Changed",
  "text": "A new look. A darker, calmer editor: one height, edge and fill for every header control, a search field with its icon, a drawn mode picker, the clock badge tinted rather than outlined, the empty map drawn as the ghost of a timeline, and a console of three modules — the bus, a sunken rack of strips with name plates, and the master section with a full-width Generate key. Dark by default. The editor opens dark whatever the operating system's setting; System and Light are still in the settings, and a theme you pick is remembered. Everything fits, in every language. No label runs out of its box — a long role name wraps on its plate, a long section name on the map is cut with an ellipsis rather than squeezed — and the editor never scrolls sideways, down to windows narrower than any host should give it (a host at 150 % display scaling gave it 930 pixels). The map's ruler spaces its numbers by their measured width, lanes squeeze further on a short map so a whole session still shows, and the lane names get the room they need. The name, once. Every format reports exactly \"Freally Unloop\", and nothing beside it repeats it, so a host's title bar never says it twice."
 },
 {
  "url": "changelog.html#0-4-0-2026-09-26-r-roles-the-conductor-fixed",
  "heading": "Fixed",
  "text": "A host could crash closing an Unloop it had only just opened — a quick plugin scan, a validator, a project closed while it was still loading. The plugin framework's background worker, shared by every instance, stopped for good when it met work left by an instance already gone, and the next instance closed brought the host down. Unloop no longer gives it any work: each instance does its own on a thread it owns. v0.3.0 2026-09-26 M: The magic moment One Unloop on a looping beat now performs the whole record, live: pick an artist, a producer or a genre, press Generate, press play in your DAW, and your loop becomes an arranged song in time with the host — parts dropping out and coming back, filter sweeps, stutter builds, tape stops — with no clicks and no added latency, while the map and the console move with it."
 },
 {
  "url": "changelog.html#0-3-0-2026-09-26-m-the-magic-moment-added",
  "heading": "Added",
  "text": "The live performance (One-Loop mode). One instance splits your loop into three bands — low (below 120 Hz), mid and high (above 4 kHz), a Linkwitz–Riley split that sums back flat — and plays the plan over them: each band comes in and out where the record says, and moves written for the whole loop act on all of it. Nothing about your loop file changes. The first moves you can hear : mute, unmute, drop-out and cut; the filter sweep (low- or high-pass, the cutoff exact at every tick, bowed by the plan's curve); the stutter build (the beat before, retriggered faster and faster, rising); and the tape stop (the loop slowing to a halt on the boundary). Every edge is an eased ramp (5 ms), held to a click test at −60 dB below the music. The rest of the vocabulary is on the map, marked with the version it arrives in. In time with the host, whichever way it plays. The song clock lays the record over your timeline from a bar you choose; the loop clock counts the loop going round — FL Studio's pattern mode, a loop brace, Ableton's session view — so 200 loops are exactly 200 loops. Auto picks one per play and says why on the clock badge. A tempo change keeps every move on its bar. The host owns t"
 },
 {
  "url": "changelog.html#0-3-0-2026-09-26-m-the-magic-moment-changed",
  "heading": "Changed",
  "text": "Every model, genre and mode name is checked against the bundled Noto fonts , as the translations already were, so no name the roster shows can fall back to a system font or a missing-glyph box. Bypass eases the performance and the Output trim out together, then passes your audio untouched; the meters read what actually leaves the plugin, after the trim. v0.2.0 2026-09-24 P: The Planner Any of the 2,413 names now becomes a deterministic arrangement plan. Nothing plays it yet — the first live performance is v0.3.0 — but every decision a record needs is made here, on the grid, before a sample is played."
 },
 {
  "url": "changelog.html#0-2-0-2026-09-24-p-the-planner-added",
  "heading": "Added",
  "text": "The planner. A name, a mode, the session and a seed become a whole record: the song form, each section's length on the 4/8/16-bar phrase grid, which parts play in each section and how (hats only, filtered, faded, half time), every move placed to the tick — drop-outs, cuts, stutter builds, rolls, sweeps, tape stops, beat switches, transition FX, ear candy, the producer's tag — and an energy curve bar by bar. The same inputs give the same plan, byte for byte, sealed by a BLAKE3 plan hash. It plans a three-minute record in under a millisecond. Every genre is arranged more than one way. Modes — radio cut, mixtape cut, club/DJ cut, switch-up, minimal, stripped, extended, and genre-specific ones (classic, posse cut and beat tape for boom bap; slow jam and interlude for 2000s R&B; the vocal cut for liquid drum & bass). Any picks one by its weight. The first 12 genre models , authored from the arrangement research: trap, dark trap, plugg, pluggnb, rage, UK drill, NY drill, boom bap, 2000s R&B, 2020s pop, country-pop and liquid drum & bass — 39 modes — plus the default every other name stands on. The whole roster, imported. 2,413 names — 1,507 artists, 833 producers, 73 genres — from Freall"
 },
 {
  "url": "changelog.html#0-2-0-2026-09-24-p-the-planner-changed",
  "heading": "Changed",
  "text": "The note under Generate now says it arrives in the next build — the planner it waited for is here, and the button is wired in v0.3.0 — in all 18 languages."
 },
 {
  "url": "changelog.html#0-2-0-2026-09-24-p-the-planner-fixed",
  "heading": "Fixed",
  "text": "The standalone on a scaled display (Windows). The page sat offset inside the window, cut off at the right and bottom, and slid behind the frame while the window was dragged: the process was DPI-unaware, so Windows stretched the window while the web view drew at true pixels. The standalone now declares per-monitor DPI awareness before any window exists. The standalone opens at the plugin's size. It passes the display's scale to nih-plug as --dpi-scale (an explicit --dpi-scale still wins), so it opens as big as the same editor does in a host. v0.1.0 2026-09-24 F: Foundation The empty product every later rung builds on: it loads, passes audio through untouched, opens its editor, and every quality gate runs."
 },
 {
  "url": "changelog.html#0-1-0-2026-09-24-f-foundation-added",
  "heading": "Added",
  "text": "The plugin, in every format from one binary. A nih-plug CLAP plugin with VST3 and AUv2 entry points projected by clap-wrapper (licence-clean: no GPL VST3 bindings), plus the standalone application. Stereo or mono, pass-through, zero latency, a versioned saved state that refuses anything it cannot read rather than crashing the host, a host Bypass switch and an Output trim (−24 to +6 dB, smoothed). The editor shell. The React editor in the shared Freally webview adapter, served from inside the binary under a strict Content Security Policy, with a typed bridge to the plugin (request/response plus polled events) whose TypeScript types are generated from the Rust ones. The Freally title bar. The product name in 3D, turning backwards on its Y axis, holding, and turning round again — as in Freally MIDI Master and Freally Oscillate, set larger so the turn is easier to see; still under reduced motion. The licence agreement ( EULA.md ) and its gate: Unloop asks you to accept it on first open and stays inert until you do. An inert plugin passes your audio through untouched — nothing a host or a saved project sets, the Output trim included, changes it before you agree. Accepting or declining i"
 },
 {
  "url": "changelog.html#0-1-0-2026-09-24-f-foundation-security",
  "heading": "Security",
  "text": "From the phase's code and security review: The editor's bridge answers only the editor's own JSON POST : a page that is not Unloop's — a link or file dropped on the window — can neither call it nor read its answers, and a drop no longer navigates the editor at all. The release plugin opens no DevTools debugging port (Freally MIDI Master's test hook, now behind a feature Unloop builds without), and the bundle check refuses a binary that could, or one not built from the pinned sources. A diagnostic trace can no longer take the host down if its console is gone."
 },
 {
  "url": "changelog.html#0-1-0-2026-09-24-f-foundation-fixed",
  "heading": "Fixed",
  "text": "Linux: the editor could not talk to the plugin. The webview delivered every bridge request with an empty body, so the licence agreement could never be accepted. Request bodies now arrive (WebKitGTK 2.40 or later). The standalone no longer refuses to start when given -p <period> . Linux: a host that scans plugins by loading and unloading them no longer crashes a few seconds later. The editor's WebKitGTK brings JavaScriptCore threads with it; the plugin library now stays loaded until the host exits (clap-validator's scan tests found it). Linux: closing the editor quickly no longer ends the host — two fixes in the shared Freally webview adapter (an X error trap on its GTK thread, and a close that waits for the web view to be gone). pluginval at strictness 10 now passes on Linux, editor tests included."
 },
 {
  "url": "changelog.html#0-1-0-2026-09-24-f-foundation-fixed-upstream-in-the-shared-nih-plug-fork-consumed-through-freally-midi-master-",
  "heading": "Fixed upstream (in the shared nih-plug fork, consumed through Freally MIDI Master's shared-v1 )",
  "text": "A CLAP host is now told its parameter values changed after a project loads (clap-validator state-reproducibility-* ). Opening or closing the editor no longer holds a lock that the editor's own start-up could re-enter — a deadlock of the host's main thread (pluginval Editor Automation ). rtrb moved to 0.3.5, closing RUSTSEC-2026-0274 (a use-after-free) at the source rather than ignoring it."
 },
 {
  "url": "changelog.html#0-1-0-2026-09-24-f-foundation-known-limitations",
  "heading": "Known limitations",
  "text": "Hosts: loading in FL Studio, Ableton Live and Reaper is proven by hand, not by CI, and those rows of the host matrix are still to be worked at this rung; the validators prove the plugin well-formed, and the standalone has been run. AU is built and bundled but unproven: no Mac has loaded it yet. The Linux editor is built and validated in a container but not yet used in a real Linux session. The shared webview adapter keeps its browser data in a folder named after Freally MIDI Master until the adapter learns to name its own (roadmap)."
 }
];
