/* ⛔ GENERATED by kit/build.mjs from the rendered pages. Do not edit.
 * ⚠ There is no search service behind the box: the index is this file. */
window.FREALLY_SEARCH_INDEX = [
 {
  "url": "features.html#copy",
  "heading": "The copy engine",
  "text": "Byte-exact copies through each system's fastest path, with instant clones on file systems that support them. Huge folders stream through without filling memory, and you choose before a copy starts what happens to files that already exist: keep both, skip, overwrite, overwrite if newer, overwrite only if different, or ask."
 },
 {
  "url": "features.html#verify",
  "heading": "Verify after copy",
  "text": "Eight checksums: CRC32, MD5, SHA-1, SHA-256, SHA-512, xxHash3-64, xxHash3-128 and BLAKE3. Each copy is read back and compared with the original, and a mismatch fails the file instead of passing unnoticed."
 },
 {
  "url": "features.html#checks",
  "heading": "Hash, re-verify and checksum files",
  "text": "The Hash panel checks files against a checksum you paste. Re-verify compares a folder with its copy months later without writing a byte. Make .md5, .sha1, .sha256, .sha512, .b3 or .sfv files for a whole folder, and drop one on the window to check it."
 },
 {
  "url": "features.html#resume",
  "heading": "Crash and reboot resume",
  "text": "A journal records each copy's progress. On the next launch the part already written is checked against its hash, and the copy continues from there."
 },
 {
  "url": "features.html#history",
  "heading": "History, re-runs and undo",
  "text": "Every job is recorded. Run any of them again, retry only the files that failed, export a signed report, or undo the last copy or move: undone copies go to the Recycle Bin or Trash, never straight to deletion."
 },
 {
  "url": "features.html#sync",
  "heading": "Sync and live mirror",
  "text": "Two-way sync, a mirror in either direction, or contribute-only, with conflicts kept as two files for you to choose between. A live mirror watches a folder and syncs every change you save."
 },
 {
  "url": "features.html#server",
  "heading": "A built-in file server",
  "text": "Serve any folder over WebDAV, HTTP, an S3-compatible API or SFTP, from Settings or the freally serve command, read-only if you like, behind a token or a password, with a Prometheus metrics endpoint."
 },
 {
  "url": "features.html#library",
  "heading": "Snapshots and backups",
  "text": "A deduplicating repository stores each version of a file once. Browse the timeline, restore any snapshot, back up chosen folders on demand, and bring in repositories from restic, Borg or Kopia."
 },
 {
  "url": "features.html#salvage",
  "heading": "Rescue a failing disk",
  "text": "Salvage copies whatever can still be read of a file on a failing drive, fills the unreadable spots with zeros so the rest keeps its place, keeps a map of the gaps, and retries only those gaps on a later run."
 },
 {
  "url": "features.html#metadata",
  "heading": "Nothing quietly lost",
  "text": "Sparse files stay sparse, and alternate data streams, extended attributes and the downloaded-from-the-internet mark travel with each file. A file locked by another program on Windows can be copied from a snapshot."
 },
 {
  "url": "features.html#desktop",
  "heading": "Part of your desktop",
  "text": "Copy and move from the right-click menu in Explorer, Finder, Nautilus, Dolphin and Thunar, paste through it from anywhere with Ctrl+Shift+V, and schedule saved jobs in your system's own scheduler."
 },
 {
  "url": "features.html#cli",
  "heading": "A command line for scripts",
  "text": "The freally command copies, moves and verifies, plans a job before running it, serves folders and imports backups, and reports in JSON lines with documented exit codes. Compare Side by side with the commercial tools Freally File Manager 1.0.0 next to six commercial tools people buy to copy, check, sync and manage their files. Every cell for another product comes from its maker's own pages, checked on 2 October 2026, and prices are US list prices as of October 2026. Feature Freally File Manager 1.0.0 TeraCopy Pro 4 Directory Opus 13 Total Commander 11 ForkLift 4 Beyond Compare 5 Pro GoodSync Personal Price (USD, October 2026) Free today $49.95 not verified sold in Australian dollars not verified sold in euros $19.95 one year of updates $70 $29.95 a year, up to five devices Checks each copy against a checksum has it optional, eight checksums has it not verified has it partly a checksum tool, not after each copy not verified has it Windows, macOS and Linux has it Windows · macOS · Linux partly Windows · macOS the Mac app is older partly Windows partly Windows partly macOS has it Windows · macOS · Linux partly Windows · macOS Linux: web interface only Resumes a copy after a crash or a "
 },
 {
  "url": "documentation.html#start",
  "heading": "Getting started",
  "text": "Freally File Manager is a desktop app for Windows 11, macOS 12 or later, and Linux. The first time it opens it shows its licence agreement: scroll to the end, then choose I Agree to start, or Decline & Quit. The window is a drop zone above the Activity panel. Add files, Add folders and Import list sit in the header. The footer holds Totals, History, Hash, Re-verify, Salvage, Sync, Library, Tasks and the gear that opens Settings. There are no downloads on this site yet."
 },
 {
  "url": "documentation.html#copy",
  "heading": "Copy files",
  "text": "Drag files or folders onto the window, or click Add files or Add folders in the header. The Transfer dropped items dialog opens. Leave Operation on Copy and click Pick destination to choose the folder to copy into. Under If a file already exists, choose what happens to files that are already there: keep both, skip, overwrite, overwrite only if newer, overwrite only if the content differs, skip if identical and ask otherwise, or ask every time. Use Order to sort the list by name or size, or drag the rows. Files always come before folders. Click Start copying. Each file gets a row in the Activity panel with its progress, speed and time left, and the header shows the totals. To pause a job, focus its row and press Space, or right-click it and choose Pause; Resume carries on and Cancel stops it. Pause all jobs, Resume all jobs and Cancel all jobs are in the header. If the destination has no room for everything, you are warned before the first byte moves and can pick which items to copy. The dialog also flags names the destination cannot hold, such as reserved names, characters it does not allow and paths that are too long, and offers to rename them. Use When done at the bottom of the w"
 },
 {
  "url": "documentation.html#move",
  "heading": "Move files",
  "text": "Moving works like copying: in the Transfer dropped items dialog, set Operation to Move, pick a destination and click Start moving. Each file is copied first, and the original is deleted only after the copy has succeeded. If anything fails, the original stays where it was and the row is marked as failed. To make every move recoverable, switch on Send moved source files to Trash in Settings → Secure delete: the originals then go to the Recycle Bin or Trash instead of being deleted."
 },
 {
  "url": "documentation.html#verify",
  "heading": "Verify a copy",
  "text": "Verification is off until you switch it on. Open Settings → Transfer and choose a checksum under Verify after copy: xxHash3 is the fastest, BLAKE3 is strong and still fast, and SHA-256 matches most other tools. From then on every copy is checked. The original is hashed while it is read, so it is not read twice; once the copy is written, the copy is hashed too and the two are compared. A match finishes the row as done. A mismatch fails the row and shows the expected and the actual checksum. If a large copy seems to sit at 100%, the header probably says Verifying: the check is still running."
 },
 {
  "url": "documentation.html#history",
  "heading": "History, re-runs and undo",
  "text": "Click History in the footer. Every job is listed with its kind, source, destination, size, status and duration, and you can filter the list by kind, status or text. Export CSV saves it. From a job you can Re-run it, use Retry failed to copy only the files that failed, Export failed to save that list, Re-verify it, or export a Certificate: a printable HTML, CSV or JSON report of every file's checksum, size and status, which you can sign with your own key. Undo, or Ctrl+Z, reverses the newest copy or move after showing exactly what it will touch. Copied files go to the Recycle Bin or Trash, and only if they still match what was copied; moved files go back where they came from. Totals, also in the footer, shows lifetime figures for bytes, files and jobs, and a chart of the last 30 days."
 },
 {
  "url": "documentation.html#checks",
  "heading": "Hash, re-verify and checksum files",
  "text": "Hash, in the footer, opens the hash inspector. Add files or folders, choose an algorithm and click Hash. Paste a checksum, a line from a checksum file or an SFV row to compare against it, or pick two files to see whether they are identical. Re-verify, also in the footer, compares a folder with its copy again, at any time and without writing anything. It reports every file that matches, differs, is missing from the copy, exists only in the copy, or cannot be read. To make a checksum file for a whole folder, right-click a finished job and choose Create checksums (SHA-256). To check one, drop a .md5, .sha1, .sha256, .sha512, .b3 or .sfv file on the window: every file it lists is hashed and the result is shown."
 },
 {
  "url": "documentation.html#sync",
  "heading": "Sync two folders",
  "text": "Click Sync in the footer, then Add pair. Give the pair a label, choose the left and the right folder, and pick a mode: Two-way; Mirror, left to right or right to left; or Contribute, which copies left to right and never deletes. Click Save pair, then Run now. When a file has changed on both sides since the last run, nothing is overwritten: the other version is kept beside it as a sync-conflict file, and View conflicts lets you keep the left one, the right one or both. Start live mirror watches the left folder and syncs again after every change you save. The pair shows Watching while it runs; Stop live mirror ends it."
 },
 {
  "url": "documentation.html#filters",
  "heading": "Choose what gets copied",
  "text": "Settings → Filters applies to every copy: patterns to include or exclude, such as **/*.log or **/node_modules, size and date limits, and whether to skip hidden, system or read-only files. A folder that matches an exclude pattern is skipped whole. To copy an exact list of files, click Import list in the header and choose a TXT, CSV or JSON file of paths. Copy them flat into one folder, or keep their folders below a common root. Before a big copy, Export plan in the Transfer dropped items dialog saves a report of what the copy will add, replace, skip or find in conflict, before a single byte moves."
 },
 {
  "url": "documentation.html#shell",
  "heading": "Right-click menus and the paste shortcut",
  "text": "Freally File Manager can add Copy with Freally File Manager and Move with Freally File Manager to the right-click menu: in Explorer on Windows, in Finder on macOS, and in Nautilus, Dolphin and Thunar on Linux. On Windows, Settings → Shell turns them on or off. Copy files as usual with Ctrl+C (Cmd+C on a Mac), then press Ctrl+Shift+V (Cmd+Shift+V on a Mac) anywhere: the files open in Freally File Manager's dialog. Change the shortcut or switch it off in Settings → General. On Windows you can go further: Intercept default copy handler, in Settings → Shell, routes Explorer's own copy and paste through Freally File Manager, and each paste then asks whether you want a plain system copy or a verified one. Revert to Windows copy handler undoes it in one click."
 },
 {
  "url": "documentation.html#library",
  "heading": "Snapshots and backups",
  "text": "Library, in the footer, opens the repository: each file's contents are stored once, in deduplicated chunks, and every snapshot is shown on one timeline. The header shows how much is stored on disk against how much it represents. On Sources, add a folder and click Back up now to take a snapshot; a second backup of an unchanged folder takes almost no space. Each source can keep all its snapshots, the last few, or a rolling set, and can run hourly, daily or weekly. On Snapshots, Restore lets you browse a snapshot's files, choose a destination and decide what happens to files that already exist. Forget drops a snapshot, and Reclaim space frees the chunks nothing uses any more."
 },
 {
  "url": "documentation.html#salvage",
  "heading": "Rescue a file from a failing drive",
  "text": "Salvage, in the footer, copies whatever can still be read of a file on a damaged drive. Choose the file, then where to write the copy. Unreadable spots are retried in smaller and smaller pieces, then filled with zeros so the rest of the file keeps its place, and a map of the gaps is saved beside the copy. Run Salvage again on the same file later and only the gaps are tried. A salvaged file with gaps is not a byte-exact copy, and its history entry says so."
 },
 {
  "url": "documentation.html#server",
  "heading": "Run it as a file server",
  "text": "Freally File Manager can serve a folder to other computers over WebDAV, plain HTTP, an S3-compatible API or SFTP. Open Settings → Server and tick the protocols to offer. Set the bind address. The default, 127.0.0.1:8080, serves only this computer; 0.0.0.0:8080 or your network address serves others, once your firewall allows it. Choose the served folder, tick Read-only if nothing should be uploaded or deleted, and choose the authentication: none, a bearer token, or a user name and password. Click Start server. The status line shows the address, and a Metrics link points to the Prometheus endpoint. Stop server, or quitting the app, stops it. Protocol Connect with WebDAV Map a network drive in Windows, Connect to Server in Finder, GNOME Files or davfs2 HTTP A web browser, curl or wget S3 The AWS command line, rclone or any S3 library, with the user name and password as the access key and secret SFTP sftp, scp, FileZilla, WinSCP or rclone WebDAV and HTTP can run together on one address; S3 and SFTP each need a server of their own, and S3 needs a password or no authentication rather than a token. A server open to the network with no authentication can be read, and written unless it is r"
 },
 {
  "url": "documentation.html#migrate",
  "heading": "Bring in a restic, Borg or Kopia repository",
  "text": "The freally migrate command reads another backup tool's repository, rebuilds every file and stores it in a repository in the open CDR-0 format, deduplicated again with Freally File Manager's own chunking. freally migrate restic /path/to/restic-repo /path/to/new-repo --password <passphrase> freally migrate borg /path/to/borg-repo /path/to/new-repo --password <passphrase> freally migrate kopia /path/to/kopia-repo /path/to/new-repo --password <passphrase> Each importer is tested to restore every file byte for byte. The CDR-0 format is described in the specification published beside this site. Read the CDR-0 specification"
 },
 {
  "url": "documentation.html#settings",
  "heading": "Settings",
  "text": "The gear in the footer opens Settings. Changes take effect at once, with no restart. The tabs you will use most: General: language, the app's theme, start at login, minimize to the tray, how errors are shown, the paste shortcut and the clipboard watcher. Transfer: verification, buffer size, how many files copy at once, clones, timestamps and permissions, sparse files, locked files and the security marks a file carries. Filters: what to include and exclude. Shell: the right-click menu and taking over Windows' own copy. Network: a speed limit, fixed or on a schedule. Server: the built-in file server. Updates: the daily update check, and a button to check now. Profiles: save your settings under a name, switch between them, and import or export them."
 },
 {
  "url": "documentation.html#shortcuts",
  "heading": "Keyboard shortcuts",
  "text": "Keys What it does Ctrl / Cmd + Shift + V Paste copied files through Freally File Manager, from anywhere Ctrl / Cmd + Z Undo the newest copy or move Space Pause or resume the focused job Esc Close the topmost dialog or drawer"
 },
 {
  "url": "documentation.html#speed",
  "heading": "How fast it is",
  "text": "Measured on 30 April 2026 on one Windows 11 laptop (Intel Core i9-13900HX, 32 GB of memory, a PCIe 4.0 NVMe drive), copying within the same NTFS drive. Each figure is the median of several runs, in MiB per second: higher is faster. What was copied Freally File Manager Robocopy Windows copy command FastCopy TeraCopy A folder of 100 files, 100 KB to 150 MB 4,308 3,424 3,172 1,769 496 One 512 MB file 3,605 3,220 3,122 1,208 174 One 256 MB file 3,200 3,460 3,765 1,000 102 One 10 GB file 1,988 2,064 2,095 1,591 1,134 It was the fastest on the folder of files and on the 512 MB file, and a little slower than Robocopy and the Windows copy command on the 256 MB and 10 GB files. It was faster than FastCopy and TeraCopy in every test. One machine and one drive, measured with a build from before 1.0.0, and each tool run from its own command line, start-up included. Your numbers will differ, and when the destination drive is the slowest part, every tool runs at its speed."
 },
 {
  "url": "documentation.html#troubleshooting",
  "heading": "Tips and troubleshooting",
  "text": ""
 },
 {
  "url": "documentation.html#trouble-slow",
  "heading": "Why is my copy slow?",
  "text": "While a copy runs below the speed it should reach, the header shows a small badge naming the cause: the source disk, the destination disk, the network, an antivirus scanner, the processor or heat. Hover it for details."
 },
 {
  "url": "documentation.html#trouble-stall",
  "heading": "A copy stops at 100%",
  "text": "If the header says Verifying, the copy is being checked against its checksum. That is normal for large files; switch verification off in Settings → Transfer if you do not need it."
 },
 {
  "url": "documentation.html#trouble-locked",
  "heading": "A file is in use on Windows",
  "text": "Files are opened so that other programs can keep using them, and a refused file is retried a few times. If another program still holds it exclusively, close that program, or choose in Settings → Transfer to copy locked files from a snapshot."
 },
 {
  "url": "documentation.html#trouble-permission",
  "heading": "Permission denied",
  "text": "When files are refused for permissions, Freally File Manager can retry them through one administrator prompt for the whole list, showing exactly which files it will touch before you approve."
 },
 {
  "url": "documentation.html#trouble-changed",
  "heading": "Source changed during copy",
  "text": "The file changed while it was being read, so the copy may mix old and new contents. By default the file is flagged; Settings → Transfer can copy it again once or fail it instead."
 },
 {
  "url": "documentation.html#report",
  "heading": "Reporting a problem",
  "text": "When the app itself causes an error, a Report button appears beside the message. After a crash, the next launch offers Report or Dismiss. Report opens this page in your browser, with the technical facts already filled in: you can read them but not change them. Add what you were doing and, if you like, an email address for a reply. https://freallyproducts.com/freally-file-manager/report/ Nothing is sent unless you press Send on that page, and nothing is ever sent in the background. File paths in a report are shortened, with your home folder shown as ~."
 },
 {
  "url": "documentation.html#privacy",
  "heading": "Privacy and the network",
  "text": "Freally File Manager has no account and no telemetry. The telemetry switch in its settings is permanently off: a value written into the settings file by hand is ignored. Copying, moving and verifying files on your own drives make no network requests. The app goes online for the things you set up, such as the file server or testing a cloud account, and to check for updates when it starts, at most once a day. The update check reads only the list of releases, sends none of your files or paths, and can be switched off in Settings → Updates. It contains no AI: everything it decides comes from checksums, sizes and timestamps, and no machine-learning library is part of it."
 },
 {
  "url": "changelog.html#1-0-0-2026-08-22-the-correctness-release-fixed",
  "heading": "Fixed",
  "text": "Shortcut folders. Copying a folder that is itself a shortcut (a symbolic link or a junction) copied nothing and reported success, and in sync the same flaw could empty the other side. Such a folder is now refused, with the reason. Cancelling. Cancelling a large folder copy could hang instead of stopping. A copy can now be cancelled at any point. The S3 server. Files uploaded by the AWS command line or an AWS library were stored damaged, and uploads larger than about 8 MB failed outright. Both now arrive byte for byte, and a cut-off upload is refused instead of stored. Sync databases. A sync pair whose database sat inside one of its own folders treated that database as a file to sync, and could delete it in the middle of a run. SFTP. SFTP remotes never connected: every connection test failed, whatever the settings. They connect now. Encryption. Encryption could fall back to writing plain files when its key could not be prepared. It now stops the job instead. Read-only server. One kind of request could still write to a server set to read-only. None can now. Progress. A resumed scan reported the wrong number of files, so progress bars were wrong in both directions. Cloud sign-in. Sign"
 },
 {
  "url": "changelog.html#0-22-0-2026-08-19-hashing-reports-scheduling-and-portability-added",
  "heading": "Added",
  "text": "Hash inspector. Hash any files or folders with any of the eight algorithms, paste a checksum to compare against, or compare two files. On Windows it is also in the right-click menu. Copy reports. Export any finished job as a printable HTML report, CSV or JSON, with every file's checksum, size and status, and sign it with your own key if you like, so anyone can check it without Freally File Manager. Re-verify. Compare a folder with its copy again, months later, without writing a byte: what matches, what differs, what is missing and what was added. Filename doctor. Before a copy, find names the destination cannot hold, such as reserved names, characters it does not allow, trailing dots and spaces, paths that are too long and names that differ only in capital letters, and rename them. Copy from a list. Import a list of paths from a TXT, CSV or JSON file as the files to copy, flat or keeping their folders. Plan reports. Export what a copy will add, replace, skip or find in conflict, before a single byte moves. Salvage. Copy what can still be read of a file on a failing drive, fill the unreadable spots with zeros, keep a map of the gaps, and retry only the gaps later. One prompt for man"
 },
 {
  "url": "changelog.html#0-22-0-2026-08-19-hashing-reports-scheduling-and-portability-fixed",
  "heading": "Fixed",
  "text": "Settings could discard your data. Saving Settings reset pinned tray destinations, repositories, cloud accounts, sync pairs and more to their defaults. Every group now survives a save, and a test makes sure of it. v0.20.0 2026-07-20 Safety nets"
 },
 {
  "url": "changelog.html#0-20-0-2026-07-20-safety-nets-added",
  "heading": "Added",
  "text": "Undo. Ctrl+Z, or Undo on a history row, shows what reversing the newest copy or move will touch, then does it. Copied files go to the Recycle Bin or Trash, and only if they still match what was copied. Delete to the Recycle Bin or Trash , and an option to send a moved file's original there instead of deleting it. Retry failed. Copy again only the files that failed in a job, or export their list. Two new choices for existing files. Overwrite only if the content differs, or skip if identical and ask otherwise. Eject. Safely remove the drive a job wrote to. No sleep while copying. The computer stays awake while any job runs. Checksum files. Make .md5 , .sha1 , .sha256 , .sha512 , .b3 or .sfv files for a whole folder, and drop one on the window to check every file it lists. Take over Windows' copy. Optionally route Explorer's own copy and paste through Freally File Manager, with a one-click way back. Every paste offers a plain system copy or a verified one. Licence agreement. It is shown the first time the app opens. v0.19.85 2026-07-01 The Library and backup tools"
 },
 {
  "url": "changelog.html#0-19-85-2026-07-01-the-library-and-backup-tools-added",
  "heading": "Added",
  "text": "The Library. One timeline of every snapshot, with how much is stored against how much it represents: back up chosen folders, and restore any snapshot to wherever you choose. Compressed, compacted storage. Snapshots can be compressed, and maintenance reclaims and compacts the space nothing uses any more, with every long task shown in Tasks. Compare and reports. Compare two snapshots, and see statistics and charts of the repository. Repository keys. Several passwords for one repository, and a recovery key. Replicate. Copy a repository to a second place, sending only what the other side lacks. Other backup tools. Bring in a restic, Borg or Kopia repository with freally migrate , and write one back out with freally export ."
 },
 {
  "url": "changelog.html#0-19-85-2026-07-01-the-library-and-backup-tools-fixed",
  "heading": "Fixed",
  "text": "Fifteen problems found in a full review, including ways a backup could lose data without saying so. v0.19.84 2026-06-27 The first release Byte-exact copy and move through each system's fastest path, with instant clones on file systems that support them, and folders of any size streamed without filling memory. Verify after copy with eight checksums, from CRC32 and xxHash3 to SHA-256 and BLAKE3. Pause, resume and cancel any job, choose what happens to files that already exist, and retry a file refused for permissions with administrator rights. Resume after a crash or a reboot from a journal of each copy's progress. History and totals : every job recorded, filtered, exported as CSV and run again with one click. Filters : include and exclude patterns, sizes, dates and file attributes. Two-way sync with conflict detection, mirror and contribute modes, and a live mirror that syncs every saved change. Speed limits , fixed or on a schedule. Nothing quietly lost : sparse files, alternate data streams, extended attributes and the downloaded-from-the-internet mark are kept, and a locked file on Windows can be copied from a snapshot. Your desktop : right-click menus on Windows, macOS and Linux"
 }
];
