/* ⛔ GENERATED by kit/build.mjs from the rendered pages. Do not edit.
 * ⚠ There is no search service behind the box: the index is this file. */
window.FREALLY_SEARCH_INDEX = [
 {
  "url": "features.html#copier",
  "heading": "The copier",
  "text": "A photoreal copy machine rendered in Blender, with its own sounds. Put a clip on the glass and it prints the real thing — the waveform, or every note — with its data: tempo, length, notes or levels."
 },
 {
  "url": "features.html#start",
  "heading": "Only the green START copies",
  "text": "Dropping a clip only places it on the glass. Nothing is copied until you press START; STOP cancels a scan and HOME clears the glass, so nothing happens that you did not ask for."
 },
 {
  "url": "features.html#audio-to-midi",
  "heading": "Audio → MIDI, in parts",
  "text": "A loop comes out as the parts in it — drums on their own lanes, bass, melody, a countermelody where there is one, and the chord progression — one page and one MIDI file each, from a single scan. A part that is not there gets no page. Or copy a sung line on its own."
 },
 {
  "url": "features.html#midi-to-audio",
  "heading": "MIDI → audio, through real instruments",
  "text": "A MIDI file played through any of the 1,648 instruments Freally MIDI Master uses — a sound for each part and a drum machine for the drums — and printed as one audio page per part, plus the whole mix. WAV, AIFF, FLAC or MP3, at the sample rate and bit depth you choose."
 },
 {
  "url": "features.html#drag",
  "heading": "Drag the copy",
  "text": "Every page wears a lime-green frame: grab it and drop the file on a track. Or drag the whole stack — All parts lands as one track per part, Complete mix as one clip. Each file is named the way your DAW should show it, such as Loop - Bassline - 120 BPM - C# Minor."
 },
 {
  "url": "features.html#copies",
  "heading": "Copies are forever",
  "text": "Every copy is a real, verified file in your Copies folder — numbered, and never moved, overwritten or deleted, so a project that uses it never loses it. Page back through every copy you have made, save one again, show it in its folder, or put it back on the glass."
 },
 {
  "url": "features.html#browser",
  "heading": "The browser and the Preview Player",
  "text": "A file browser from Freally Oscillate: up to 128 folders, back and forward, tags, stars and a keyboard walk. The preview shows the real waveform or the notes, plays MIDI through the same sound the copy uses, and plays a finished stack in sync, with an A/B against the original."
 },
 {
  "url": "features.html#studio",
  "heading": "The Studio",
  "text": "Open any copy in a piano roll, one tab per part, edited exactly as in Freally MIDI Master. Hear it through any instrument, shape it on a mixer with realistic knobs, play it through your own drum kit or one of your samples, and send the edit back to the glass to print as a new copy."
 },
 {
  "url": "features.html#settings",
  "heading": "Settings on the touch screen",
  "text": "The copier's own screen holds the copy settings: which parts, the grid and swing, the tempo and where it comes from, the sound for each part, the file format and the tail. A build gate checks that each setting really changes the copy."
 },
 {
  "url": "features.html#daw",
  "heading": "In every DAW",
  "text": "CLAP and VST3 on Windows, macOS and Linux, AU on macOS, and a standalone app for working without a DAW — and for Pro Tools, by dragging. Saved with your project, safe in many instances at once, and able to scan straight from a track."
 },
 {
  "url": "features.html#skins",
  "heading": "Skins, light and dark",
  "text": "Five skins, each a raised chassis rendered in Blender and shared by every Freally app, in light and dark, beside plain light and dark modes. The copier is rendered again for each one, so it always stands on its own ground."
 },
 {
  "url": "features.html#offline",
  "heading": "Offline, private, no AI",
  "text": "No telemetry and no model. Every copy is made by classic signal processing, and the plugin and the app never go online. The one exception is an update check that stays off unless you switch it on, run by a separate program. Compare Side by side with the commercial tools Freally Flipcopy 1.0 next to the commercial tools producers use to turn audio into MIDI and MIDI into audio. Every cell for another product comes from its maker's own pages, checked on 1 October 2026, and prices are US list prices as of October 2026. Feature Freally Flipcopy 1.0 Melodyne 5 Studio RipX DAW PRO Ableton Live 12 Suite Logic Pro AnthemScore 6 Professional Price (USD, October 2026) Free today $699 $198 $749 $199.99 $39 Turns audio into MIDI has it has it has it has it has it has it One loop split into its parts, each its own MIDI file has it does not separates notes, not instruments has it by instrument partly stems first, then each by hand partly stems first, then each by hand partly Turns MIDI into audio through built-in instruments has it not verified has it has it has it does not plays it, but exports no audio Drag the result straight onto a DAW track has it partly in some DAWs, through ARA not verifi"
 },
 {
  "url": "documentation.html#start",
  "heading": "Getting started",
  "text": "Flipcopy runs inside your DAW as a CLAP, VST3 or AU plugin, or on its own as a standalone app. Put it on any audio track: it passes the track's audio through exactly as it arrives, so it is safe to leave in place. There are no downloads before version 1.0.0, and the source code is private."
 },
 {
  "url": "documentation.html#agreement",
  "heading": "The licence agreement",
  "text": "The first time Flipcopy opens it shows its licence agreement. Read it to the end and Agree becomes available. Until you agree, Flipcopy reads nothing, copies nothing and adds nothing to your track's audio. Your answer is kept on your computer and shared by every open copy of Flipcopy, in every DAW and in the standalone app. If you decline, choose Read it again whenever you are ready."
 },
 {
  "url": "documentation.html#window",
  "heading": "The window",
  "text": "On one side is the browser, with the preview player docked under it. The rest of the window is the stage, where the copier stands. Drag the line between them to make the browser wider or narrower, or focus it and use the arrow keys. Press Ctrl+B (Cmd+B on a Mac), or the button at the browser’s edge, to fold the browser and its preview away: the stage takes the whole window. Press it again and they come back at the width you left them. Flipcopy remembers which you chose."
 },
 {
  "url": "documentation.html#copier",
  "heading": "Making a copy",
  "text": "Put an audio or MIDI file on the glass: drop it from Explorer or Finder anywhere on the window, drag it from the browser or the preview strip onto the copier, press Enter on a row in the browser, or press Enter on the empty glass to choose one. The copier prints the original and lays it face-down on the glass. Putting a file on the glass never starts a copy. Press the green START key, or Ctrl+Enter (Cmd+Enter on a Mac). The lid closes, the lamp sweeps, and the copy slides out onto the tray: an audio loop comes out as MIDI, one page for each part the copier hears; a MIDI file comes out as audio, one page for each part. Esc or the red STOP key cancels it; the grey HOME key clears the glass. Every page is a real file in Documents/Freally Flipcopy/Copies, numbered, and never moved, overwritten or deleted. Grab a page by the lime frame round its printed clip and drag it straight onto a track in your DAW, or drag the whole stack at once. The copier’s sounds play through the plugin’s own output, quietly, never while your DAW plays and never into a bounce. Turn them off or down in Settings."
 },
 {
  "url": "documentation.html#browser",
  "heading": "The browser",
  "text": "The browser opens on its Categories: Copies, every page and mix you have made, and Recent, the originals you last put on the glass. Under them are the folders you have added; choose + Add Folder to add one, up to 128. A folder on a drive that is not plugged in keeps its place and says it isn’t connected right now. To stop browsing a folder, right-click it, or select it and press Delete; nothing on disk is touched. Open a folder to walk it as a tree. Type to filter it by name, pick a tag or Starred to narrow it, and choose Show all files to see the sidecar files Flipcopy hides, such as .asd and .reapeaks. Back and Forward take you through the places you have been. Walk the rows with ↑ and ↓: each row you land on plays once in the preview. → opens a folder and ← closes it. Enter puts the selected file on the glass, and so does dragging its row onto the copier. The first time you add a folder, Flipcopy counts its files, with a bar that shows how far it has got. It reads at most 12 folders deep and 50,000 files, and never follows a shortcut out of the folder."
 },
 {
  "url": "documentation.html#preview",
  "heading": "The preview player",
  "text": "The preview player sits under the browser. An audio file shows its real waveform. A MIDI file shows its notes and plays through Preview Piano, the same sound a copy uses unless you choose another, so you hear what the copy will sound like. Space plays and pauses, Stop goes back to the start, and a click or a drag on the strip moves the playhead. Loop repeats the file, Play when selected (the headphones) plays each file you select, and the slider sets the level. The preview plays through Flipcopy’s own output and never into a bounce. A WAV file of any length plays; a file in another format plays if it is five minutes or shorter. Click the original on the glass, or a page on the tray, to hear it. When a copy is finished, Copy plays all its pages together and Original plays the file on the glass, from the same place in the music, so you can hear the difference before you drag. Playing it is never required: the pages can be dragged as soon as the last one lands. The strip wears the same lime frame as a page. Drag it onto the glass to put that file there."
 },
 {
  "url": "documentation.html#problems",
  "heading": "When something goes wrong",
  "text": "If Flipcopy itself fails, such as a copy it could not write, the screen offers Report. It opens a page in your web browser that shows exactly what the report holds; nothing is sent unless you press Send there. A file the copier refuses, because it is too long, silent or not audio, is not a failure, and the screen says why instead."
 },
 {
  "url": "documentation.html#language",
  "heading": "Languages",
  "text": "Flipcopy speaks eighteen languages. It starts in your system's language; to choose another, open Settings with the gear at the top of the browser and pick one. The choice applies to every copy of Flipcopy on the computer."
 },
 {
  "url": "documentation.html#privacy",
  "heading": "Privacy and the network",
  "text": "Flipcopy has no account and no telemetry, and the plugin and standalone app contain no networking code at all. Your files and your copies never leave your computer. It contains no AI of any kind: every copy is made by classic, deterministic signal processing, and a build gate fails if a machine-learning library is ever added."
 },
 {
  "url": "changelog.html#0-4-0-2026-10-05-the-file-browser-and-the-preview-player-added",
  "heading": "Added",
  "text": "The browser. It opens on its Categories — Copies , every page and mix you have made, and Recent , the originals you last put on the glass, each counted — then the folders you add with + Add Folder (up to 128). A folder on a drive that is unplugged keeps its place and says so; right-click a folder, or select it and press Delete , to stop browsing it, and nothing on disk is touched. Back and Forward move through where you have been, exactly as in Freally Oscillate. A folder as a tree. Expand and collapse it, type to filter it, narrow it to a tag or to your stars, and choose Show all files to see the sidecar files it hides ( .asd , .reapeaks and the like). ↑ / ↓ walk the rows and each one you land on plays once; → opens a folder, ← closes it, and Enter puts the file on the glass. Indexing you can watch. A new folder is counted on a thread of its own with a bar that shows how far it has got — at most 12 folders deep and 50,000 files, never following a shortcut out of the folder. The preview player , docked under the browser. Audio shows its real waveform; a MIDI file shows its notes and plays through Preview Piano , the very sound and render a copy uses, so the preview is the copy. Spa"
 },
 {
  "url": "changelog.html#0-4-0-2026-10-05-the-file-browser-and-the-preview-player-changed",
  "heading": "Changed",
  "text": "The docs site is built from the shared Freally site kit, the same on every Freally site, with its manual updated for this version."
 },
 {
  "url": "changelog.html#0-4-0-2026-10-05-the-file-browser-and-the-preview-player-fixed",
  "heading": "Fixed",
  "text": "A page under the pointer is found at any window size. A click or a drag on a page landed in the wrong place once the window was scaled. v0.3.0 2026-10-01 Audio → MIDI: the magic moment Put an audio loop on the glass, press START, and its MIDI comes out — one page for every layer the copier hears, back to back from one scan, each its own file, framed in lime and dragged into your DAW on its own or all together. A MIDI file with several parts comes out the same way: one audio page per part, and the whole file as one mix."
 },
 {
  "url": "changelog.html#0-3-0-2026-10-01-audio-midi-the-magic-moment-added",
  "heading": "Added",
  "text": "Audio → MIDI. An audio loop is read into its layers — drums, bass, melody, a countermelody where the loop has a second, independent line, and chords — with MIDI Master's classic-DSP extractor (no AI). Each layer found is its own page and its own .mid , named as a DAW shows it ( Loop - Bassline - 120 BPM - C# Minor ); a layer that isn't there gets no page, and a loop with no notes at all is refused rather than copied blank. The key is printed only when it was read clearly. A stack of pages. The pages eject one after another from the single scan, fanned on the tray, each titled by its form and its part ( MIDI MELODY , AUDIO BASSLINE ) with PAGE n/N . Click a page to bring it to the top. Nothing drags until the last page has landed. Two drags from the finished stack. The top page carries two lime tabs: All parts drags every page as separate files, so the DAW lays them out as one track per layer; Complete mix drags one file of everything — a multi-track .mid of every part, or the whole render as a .wav — written beside the pages and never printed. Hover the tab for the mix's facts; without a pointer, Save the complete mix as… saves it. MIDI → audio, part by part. A MIDI file with sever"
 },
 {
  "url": "changelog.html#0-3-0-2026-10-01-audio-midi-the-magic-moment-changed",
  "heading": "Changed",
  "text": "The host's tempo is followed block by block , and a MIDI file with no tempo of its own is copied at the host's tempo at the moment you press START. The session tempo only breaks the octave tie. A 120 BPM loop dropped in a 90 BPM session is read at 120 (four bars), not at 90 (three) — fixed in MIDI Master's shared extractor, for every Freally product that reads loops. Free today, not promised forever. Freally Flipcopy is free today, but it might not be free forever: future versions may be sold. Every page of the docs site now says so. The repository moved to the maintainer's own GitHub account, private and All Rights Reserved, with the shared Freally crates coming from Freally MIDI Master and Freally Oscillate beside it; the plugin's web address is the docs site's new one. Continuous integration runs on the maintainer's machine before every push — every gate on Windows, and the Linux gates in Docker Desktop — and none on GitHub Actions. Every commit carries [skip ci] . (For a few hours on 2026-09-30, the repository was public and CI ran on GitHub for every push.)"
 },
 {
  "url": "changelog.html#0-3-0-2026-10-01-audio-midi-the-magic-moment-fixed",
  "heading": "Fixed",
  "text": "The editor keeps its own browser profile. Flipcopy's WebView2 data ( %APPDATA%\\Freally Flipcopy\\webview ) had been filed under Freally MIDI Master's folder, and two products sharing one WebView2 profile can leave each other's editor blank when both run in the same DAW. It is Flipcopy's own now. A copy's Complete mix can only ever be its own file : a record.json edited behind the copier can't point a drag, a Save As or a Reveal anywhere else. A copy is written whole or not at all. Every page and the mix are on disk before any of them takes its name, so a failure part-way never leaves pages in a numbered folder that no copy owns. No page clips. The one headroom gain is set by every file a copy writes — a part can peak above the mix where the others cancel it. A 16-bar loop exported a tick long is 16 bars , not 17 — a last note released a thirty-second past the bar line is not a bar of its own. Controllers reach a page even on a channel that plays no notes. v0.2.0 2026-09-30 The copier and the first copy The copier stands on the stage, playing the Blender copier story videos' beats in their order: drop a MIDI file on the glass, press the green START, and a real audio copy comes out on"
 },
 {
  "url": "changelog.html#0-2-0-2026-09-30-the-copier-and-the-first-copy-added",
  "heading": "Added",
  "text": "The copier on the stage. The machine rendered by the same Blender scene as the two story videos — its base, its lid as sprite frames, the pressed keys, the glass and tray mattes — rendered over the window's own ground ( #090c09 ) on transparent film, so it stands in the room with no seam. The phases are the videos' beats in the videos' order (the sheet flips and lands face-down, the lid swings shut with its bounce, the START beep, the lamp sweeps side to side leaking cyan out of the front seam while the whole room dims, the copy slides out onto the tray), at the in-app cut's shorter durations; a test fails if the app ever plays a beat the story doesn't have, skips one, or plays them out of order. It fills whatever room the window gives it and never mirrors in a right-to-left language. The green START is the only trigger. Dropping a clip only puts it on the glass. START (or Ctrl/Cmd+Enter , which presses the same key) starts the copy; STOP (or Esc ) cancels it mid-scan with nothing left behind; HOME clears the glass. The key carries an angled START , turned to the touch panel, and its LED is lit whenever a copy can start. A plugin test sends every command and fails if any but copier"
 },
 {
  "url": "changelog.html#0-2-0-2026-09-30-the-copier-and-the-first-copy-changed",
  "heading": "Changed",
  "text": "Shared code : freally-extract (the decode door and the audio analysis), freally-encode (WAV, resampling, the DAW-grid chunks) and freally-drag (the native drag source) are consumed from MIDI Master at shared-v5 , with freally_library::audition::NoteRenderer , read_facts ' controller events, and the web view adapter's file-drop hook, its re-placing of the web view when the window moves and its blank caption added upstream there. The icon is the owner's own — the lime F over a waveform and a piano roll — on the executable, the plugin bundles, the Linux and macOS icons and the docs site, in place of the placeholder. The window. The standalone's title bar wears the icon, is dark and the colour of the room, and says nothing: no title in the title bar of the standalone or of a plugin window in a DAW whose caption names Flipcopy, since the turning name across the top of the window already says it. That turning name is twice the size, to be read at a glance, and centred over the copier's side of the window; the file browser runs from the top of the window to the preview dock beside it. The bridge takes requests up to 2 MiB (a drag image); host_info says whether a page can be dragged here. "
 },
 {
  "url": "changelog.html#0-2-0-2026-09-30-the-copier-and-the-first-copy-fixed",
  "heading": "Fixed",
  "text": "Moving the window on a scaled display. With Windows set to 150 %, dragging the standalone window by its title bar drew its contents a third of the way behind the window, towards the screen's top-left corner, hiding the right and bottom edges until the window was moved back to that corner. The contents now stay exactly under the window wherever it is moved. The standalone at your display's own scale. On a scaled display (150 %) the standalone ran as an old-style, unscaled program: Windows stretched its window while the page inside it drew at true pixels — the root of the drag and drop-down misplacements listed here. It now declares itself per-monitor DPI aware before it opens a window, as Freally MIDI Master's and Freally Unloop's standalones do, so the page draws crisply at the display's scale and the window opens at its intended size. The language list opens under its field. On a scaled display the system's own drop-down list opened down and to the right of the Settings field, further off the further the field sat from the window's corner; the list is now drawn by Flipcopy itself, straight under the field, in the window's own dark style, with each language written in its own scrip"
 },
 {
  "url": "changelog.html#0-1-0-2026-09-26-foundation-ci-spine-added",
  "heading": "Added",
  "text": "The plugin, in every format from one binary. A nih-plug CLAP plugin with VST3 and AUv2 entry points projected by clap-wrapper (licence-clean: no GPL VST3 bindings), plus the standalone application — a native desktop app with its own window and audio device, never a web app. Stereo in and out, a note input for the later \"Scan from track\", zero latency, and the track's audio passed through bit for bit (a null test proves it). A host Bypass switch and a Monitor level for the sound Flipcopy itself will add (the machine's sounds and the preview, from v0.2.0 ) — it never touches the track. A versioned saved state that is bounded, migrated and refused as a whole rather than half-loaded, so a damaged project never crashes the host. The licence agreement ( EULA.md , structured like Freally Oscillate's) and its gate: Flipcopy asks you to accept it on first open and stays inert until you do — it reads nothing, copies nothing and adds nothing to your track. The agreement is compiled into the plugin and served from it, Agree waits until the text has been read to the end, and your answer is shared by every open instance and the standalone. A decline that could not be saved says so. The window , "
 },
 {
  "url": "changelog.html#0-1-0-2026-09-26-foundation-ci-spine-security",
  "heading": "Security",
  "text": "The editor loads only the page compiled into the binary, under a strict Content Security Policy; its bridge answers only the page's own JSON POST , refuses anything over 64 KiB and any path with .. , and before the agreement is accepted answers only an allowlist of commands. Release builds open no DevTools and no remote-debugging port. No network code in the plugin or the standalone, checked by the compiler ( clippy.toml ) and the dependency graph ( scripts/check-denylist.mjs ). The files Flipcopy keeps in your app-data folder (the agreement answer and the preferences) are read with a size bound and written atomically, so a damaged or hand-edited file loads as the defaults and a crash never leaves half a file."
 }
];
