/* ⛔ GENERATED by kit/build.mjs from the rendered pages. Do not edit.
 * ⚠ There is no search service behind the box: the index is this file. */
window.FREALLY_SEARCH_INDEX = [
 {
  "url": "features.html#copier",
  "heading": "The copier",
  "text": "A photoreal copy machine rendered in Blender, with its own sounds. Put a clip on the glass and it prints the real thing — the waveform, or every note — with its data: tempo, length, notes or levels."
 },
 {
  "url": "features.html#start",
  "heading": "Only the green START copies",
  "text": "Dropping a clip only places it on the glass. Nothing is copied until you press START; STOP cancels a scan and HOME clears the glass, so nothing happens that you did not ask for."
 },
 {
  "url": "features.html#audio-to-midi",
  "heading": "Audio → MIDI, in parts",
  "text": "A loop comes out as the parts in it — drums on their own lanes, bass, melody, a countermelody where there is one, and the chord progression — one page and one MIDI file each, from a single scan. A part that is not there gets no page. Or copy a sung line on its own."
 },
 {
  "url": "features.html#midi-to-audio",
  "heading": "MIDI → audio, through real instruments",
  "text": "A MIDI file played through any of the 1,648 instruments Freally MIDI Master uses — a sound for each part and a drum machine for the drums — and printed as one audio page per part, plus the whole mix. WAV, AIFF, FLAC or MP3, at the sample rate and bit depth you choose."
 },
 {
  "url": "features.html#drag",
  "heading": "Drag the copy",
  "text": "Every page wears a lime-green frame: grab it and drop the file on a track. Or drag the whole stack — All parts lands as one track per part, Complete mix as one clip. Each file is named the way your DAW should show it, such as Loop - Bassline - 120 BPM - C# Minor."
 },
 {
  "url": "features.html#copies",
  "heading": "Copies are forever",
  "text": "Every copy is a real, verified file in your Copies folder — numbered, and never moved, overwritten or deleted, so a project that uses it never loses it. Page back through every copy you have made, save one again, show it in its folder, or put it back on the glass."
 },
 {
  "url": "features.html#browser",
  "heading": "The browser and the Preview Player",
  "text": "A file browser from Freally Oscillate: up to 128 folders, back and forward, tags, stars and a keyboard walk. The preview shows the real waveform or the notes, plays MIDI through the same sound the copy uses, and plays a finished stack in sync, with an A/B against the original."
 },
 {
  "url": "features.html#studio",
  "heading": "The Studio",
  "text": "Open any copy in a piano roll, one tab per part, edited exactly as in Freally MIDI Master. Hear it through any instrument, shape it on a mixer with realistic knobs, play it through your own drum kit or one of your samples, and send the edit back to the glass to print as a new copy."
 },
 {
  "url": "features.html#settings",
  "heading": "Settings on the touch screen",
  "text": "The copier's own screen holds the copy settings: which parts, the grid and swing, the tempo and where it comes from, the sound for each part, the file format and the tail. A build gate checks that each setting really changes the copy."
 },
 {
  "url": "features.html#daw",
  "heading": "In every DAW",
  "text": "CLAP and VST3 on Windows, macOS and Linux, AU on macOS, and a standalone app for working without a DAW — and for Pro Tools, by dragging. Saved with your project, safe in many instances at once, and able to scan straight from a track."
 },
 {
  "url": "features.html#light-dark",
  "heading": "Light and dark",
  "text": "A dark mode and a light mode, both in Freally green, from one modern design every Freally app shares, with the knobs, faders, sliders, switches and keys rendered in Blender for each. The copier is rendered again on each mode's own ground, so it always stands in one room."
 },
 {
  "url": "features.html#offline",
  "heading": "Offline, private, no AI",
  "text": "No telemetry and no model. Every copy is made by classic signal processing, and the plugin and the app never go online. The one exception is an update check that stays off unless you switch it on, run by a separate program. Compare Side by side with the commercial tools Freally Flipcopy 1.0 next to the commercial tools producers use to turn audio into MIDI and MIDI into audio. Every cell for another product comes from its maker's own pages, checked in October 2026, and prices are US list prices as of October 2026. Feature Freally Flipcopy 1.0 Melodyne 5 Studio RipX DAW PRO Ableton Live 12 Suite Logic Pro AnthemScore 6 Professional Price (USD, October 2026) Free today $699 $198 $749 $199.99 $39 Turns audio into MIDI has it has it has it has it has it has it One loop split into its parts, each its own MIDI file has it does not separates notes, not instruments has it by instrument partly stems first, then each by hand partly stems first, then each by hand partly Turns MIDI into audio through built-in instruments has it not verified has it has it has it does not plays it, but exports no audio Drag the result straight onto a DAW track has it every page, and any file in its browser partl"
 },
 {
  "url": "documentation.html#start",
  "heading": "Getting started",
  "text": "Flipcopy runs inside your DAW as a CLAP, VST3 or AU plugin, or on its own as a standalone app. Put it on any audio track: it passes the track's audio through exactly as it arrives, so it is safe to leave in place. There are no downloads before version 1.0.0, and the source code is private."
 },
 {
  "url": "documentation.html#agreement",
  "heading": "The licence agreement",
  "text": "The first time Flipcopy opens it shows its licence agreement. Read it to the end and Agree becomes available. Until you agree, Flipcopy reads nothing, copies nothing and adds nothing to your track's audio. Your answer is kept on your computer and shared by every open copy of Flipcopy, in every DAW and in the standalone app. If you decline, choose Read it again whenever you are ready. The licence agreement"
 },
 {
  "url": "documentation.html#window",
  "heading": "The window",
  "text": "On one side is the browser, with the preview player docked under it. The rest of the window is the stage, where the copier stands. Drag the line between them to make the browser wider or narrower, or focus it and use the arrow keys. Press Ctrl+B (Cmd+B on a Mac), or the button at the browser’s edge, to fold the browser and its preview away: the stage takes the whole window. Press it again and they come back at the width you left them. Flipcopy remembers which you chose. The window"
 },
 {
  "url": "documentation.html#copier",
  "heading": "Making a copy",
  "text": "Put an audio or MIDI file on the glass: drop it from Explorer or Finder anywhere on the window, drag it from the browser or the preview strip onto the copier, press Enter on a row in the browser, or press Enter on the empty glass to choose one. The copier prints the original and lays it face-down on the glass. Putting a file on the glass never starts a copy. Press the green START key, or Ctrl+Enter (Cmd+Enter on a Mac). The lid closes, the lamp sweeps, and the copy slides out onto the tray: an audio loop comes out as MIDI, one page for each part the copier hears; a MIDI file comes out as audio, one page for each part. Esc or the red STOP key cancels it; the grey HOME key clears the glass. Every page is a real file in your Copies folder (Documents/Freally Flipcopy/Copies, unless you choose another in Settings), numbered, and never moved, overwritten or deleted. Grab a page by the lime frame round its printed clip and drag it straight onto a track in your DAW, or drag the whole stack at once. The copier’s sounds play through the plugin’s own output, quietly, never while your DAW plays and never into a bounce. Turn them off or down in Settings. Making a copy Audio → MIDI, in parts"
 },
 {
  "url": "documentation.html#screen",
  "heading": "The touch screen",
  "text": "The copier’s screen says what it is doing and which way it copies: AUDIO > MIDI or MIDI > AUDIO. Under it are its soft keys. SETTINGS opens Copy Settings; ◀ PREV and NEXT ▶ page through your copies; SAVE, REVEAL and REPRINT work on the copy in the tray. None of them starts a copy: only START does. When a MIDI file has no tempo of its own but its name says one, such as Hook 127 BPM.mid, a chip beside the screen offers it. Use 127 BPM copies that file at that tempo; Keep the project’s tempo leaves it. Flipcopy never changes your DAW’s tempo, and every page prints its tempo and where that tempo came from. The touch screen"
 },
 {
  "url": "documentation.html#copy-settings",
  "heading": "Copy Settings",
  "text": "Press SETTINGS on the touch screen and the panel grows out of it. Every setting changes the copy you make, and a change is for the next copy, never one already being made; your project keeps them. Tab moves through the panel, the arrow keys choose, and Esc closes it. For an audio loop, Parts chooses what to copy: every part, a page each; one part only, the drums, bassline, melody or chords; or the vocal line, one note at a time. If the loop has none of the part you asked for, the copier says so instead of printing a blank page. Grid puts the notes on 1/8, 1/16, 1/32 or 1/16T, or leaves them as they were read, and Swing keeps a swing or straightens it. For a MIDI file, Pages chooses a page per part or the mix only, and Tail sets how long the sound rings on after the last note. Format writes WAV, AIFF, FLAC or MP3 (320 kbps), at the project’s sample rate or at 44.1, 48, 88.2 or 96 kHz, in 16 or 24-bit or 32-bit float. FLAC and AIFF have no float, so they write 24-bit; MP3 is written at 44.1 or 48 kHz. Both ways, Tempo is Automatic, the project’s, the file’s own, from the file name, or one you set. Copy Settings"
 },
 {
  "url": "documentation.html#instruments",
  "heading": "Instruments",
  "text": "A MIDI copy plays each part through an instrument from the Freally library, the same library Freally MIDI Master uses. In Copy Settings, type in a part’s search box to find one by its name, genre or family, add a number to ask for one of its variations, and pick it: the bassline, melody, countermelody and chords can each have their own. Preview Piano is the default. The drums play through the drum machine you choose: Preview Kit by default, or the 808, the 707 or the 606. Every audio page prints the instrument it was played with on its TONER line, beside its tempo. Instruments"
 },
 {
  "url": "documentation.html#copies",
  "heading": "Your copies",
  "text": "◀ PREV and NEXT ▶ on the touch screen, or the [ and ] keys, page through every copy you have made; each lies in the tray, ready to drag. SAVE saves the page on top as a new file, wherever you choose and in the format you pick. REVEAL shows the copy in its folder. REPRINT puts the copy’s original back on the glass with the settings it was made with: press START to make it again. Drag a page back onto the glass, or drop one from your Copies, and it goes on as an original, ready to be copied the other way; the new copy says which page it came from. To drag several pages at once, Shift-click them, then drag one: they all go, in page order. Every copy’s folder holds a ticket.txt, a plain-text record of how it was made: the original and its fingerprint, the settings, the tempo and where it came from, the instruments, and every page’s file and fingerprint. Your copies"
 },
 {
  "url": "documentation.html#studio",
  "heading": "The Studio",
  "text": "Above the machine are two tabs, COPIER and STUDIO. Press Ctrl+1 or Ctrl+2 (Cmd+1 or Cmd+2 on a Mac) to reach them from anywhere in the window, or move between the tabs with the arrow keys. Switching never stops anything: a copy being scanned carries on behind the Studio, and its pages are out when you come back. Each instance of the plugin keeps its own tab. To open a copy, press STUDIO on the touch screen to open the copy in the tray, or select a file under Copies in the browser and press Open in Studio. A copy of an audio loop opens its MIDI pages, one part tab each, in page order; a copy of a MIDI file opens the parts of the MIDI it was made from. The notes are read from the files the copy wrote, so a copy whose files have moved or changed does not open, and the Studio says why. If the copy already open has changes you haven’t sent, opening another asks first. Each part is edited in Freally MIDI Master’s piano roll. Double-click to draw a note, and drag a note to move it. Drag its left or right edge, where the pointer becomes [ or ], to shorten or lengthen it. Select notes with a box, with Shift-click or with Ctrl-click; copy, cut and paste them; clone them with Shift+D or by dr"
 },
 {
  "url": "documentation.html#mixer",
  "heading": "The mixer and your own sounds",
  "text": "The Studio has three views, Notes, Mixer and Sound, in the tabs at its top right; the arrow keys move between them. Every fader, knob and choice in them belongs to the project's Copy Settings, so what the Studio plays is exactly what START prints, and it is saved with the project. The Mixer has a strip for every part of the open copy and one for the master. A pitched part's strip has Freally MIDI Master's channel strip: Low, Mid and High, the Room and Echo sends, Heat and Pitch Mod. Under it are the pan knob, the fader with its meter, and the S and M keys. The meter is green below −12 dBFS, yellow up to −3 and red above, and its clip light comes on at 0 dBFS and stays on until you click it. A part with its fader all the way down is not printed at all. Drag a fader or a knob up and down, hold Shift to move it finely, or turn the mouse wheel over it. With it focused, the arrow keys move it a step, Home and End take it to either end, and a double-click puts it back: a fader to 0 dB, a knob to its own default. Every one says its value as it moves. Sound shapes the part shown. It plays through the library's instrument, with Freally MIDI Master's SYNTH page beneath it: the oscillators, t"
 },
 {
  "url": "documentation.html#browser",
  "heading": "The browser",
  "text": "The browser opens on its Categories: Copies, every page and mix you have made, and Recent, the originals you last put on the glass. Under them are the folders you have added; choose + Add Folder to add one, up to 128. A folder on a drive that is not plugged in keeps its place and says it isn’t connected right now. To stop browsing a folder, right-click it, or select it and press Delete; nothing on disk is touched. Open a folder to walk it as a tree. Type to filter it by name, pick a tag or Starred to narrow it, and choose Show all files to see the sidecar files Flipcopy hides, such as .asd and .reapeaks. Back and Forward take you through the places you have been. Walk the rows with ↑ and ↓: each row you land on plays once in the preview. → opens a folder and ← closes it. Enter puts the selected file on the glass, and so does dragging its row onto the copier. The first time you add a folder, Flipcopy counts its files, with a bar that shows how far it has got. It reads at most 12 folders deep and 50,000 files, and never follows a shortcut out of the folder. The browser"
 },
 {
  "url": "documentation.html#preview",
  "heading": "The preview player",
  "text": "The preview player sits under the browser. An audio file shows its real waveform. A MIDI file shows its notes and plays through Preview Piano, the same sound a copy uses unless you choose another, so you hear what the copy will sound like. Space plays and pauses, Stop goes back to the start, and a click or a drag on the strip moves the playhead. Loop repeats the file, Play when selected (the headphones) plays each file you select, and the slider sets the level. The preview plays through Flipcopy’s own output and never into a bounce. A WAV file of any length plays; a file in another format plays if it is five minutes or shorter. Click the original on the glass, or a page on the tray, to hear it. When a copy is finished, Copy plays all its pages together and Original plays the file on the glass, from the same place in the music, so you can hear the difference before you drag. Playing it is never required: the pages can be dragged as soon as the last one lands. The strip wears the same lime frame as a page. Drag it onto the glass to put that file there. The preview player"
 },
 {
  "url": "documentation.html#daw",
  "heading": "In your DAW",
  "text": "Flipcopy is made to stay in a project: what is on its glass is saved with the project, it can scan a few bars straight from the track it sits on, its browser drags any file straight onto a track, and many copiers can run in one project at once."
 },
 {
  "url": "documentation.html#saved",
  "heading": "Saved with your project",
  "text": "The original on the glass is kept with your DAW’s project, with the Copy Settings you chose. Reopen the project and the glass shows it again. If the file has moved since, the glass says The original has moved, and Locate… finds it. A project whose Flipcopy state can’t be read opens with an empty glass and says so; nothing from another project is ever carried over. Settings saved by a newer version of Flipcopy are kept as they are, so opening a project in an older version and saving it again loses nothing."
 },
 {
  "url": "documentation.html#scan",
  "heading": "Scan from track",
  "text": "In a DAW, Copy Settings has Scan from track. Choose 1 to 16 bars, press Arm, then press play in your DAW. As the track plays, its audio, or the MIDI notes it receives, is taken for that many bars, written as a new file in the Captures folder of your Copies folder, and put on the glass. Nothing is copied until you press the green START. The bars are counted from your DAW’s tempo and meter: if it isn’t sending them yet, press play once, then arm. The panel says what a host won’t send. Ableton Live gives an audio effect no MIDI, so there a scan takes the track’s audio, never its notes; Logic may not run a track that isn’t live, so arm the track, or play it, before you scan. Nothing is scanned while your DAW bounces, and the standalone app has no track to scan: drop a file on the glass instead."
 },
 {
  "url": "documentation.html#drag-out",
  "heading": "Drag a file straight into your DAW",
  "text": "At the end of every audio and MIDI file’s row in the browser, and on the Preview strip, is a grip: Drag the file into your DAW. Drag it onto a track and the file itself lands there, just as it is on your disk. The row itself still drags onto the glass, to be copied. Whatever you drag out to your DAW, a page or a file, the picture under the pointer is that clip: its notes or its waveform, in the lime frame. A DAW that draws no drag picture shows its own file icon instead; the file is the same. Drag a file straight into your DAW"
 },
 {
  "url": "documentation.html#instances",
  "heading": "Many copiers at once",
  "text": "Put Flipcopy on as many tracks as you like: each copier keeps its own glass, its own Copy Settings and its own tab. Eight at once, each with its sounds, its preview and a scan running, use well under one percent of a 256-sample buffer, and a window with nothing moving runs no animation at all."
 },
 {
  "url": "documentation.html#settings",
  "heading": "Settings",
  "text": "Open Settings with the gear at the top of the browser. Machine sounds turns the copier’s sounds on or off, sets their level and keeps them quiet while your DAW plays. A switch of its own turns off the soft sounds the panels and dialogs make as they open and close. Under Motion, Quick runs the machine at its short timings, with every sound still in its place. Reduced motion follows your system’s setting, or choose Reduce to have it always: no flip, no swing of the lid, no sweep and no dimming of the room. The copier still shows each step and plays each sound, and START is still the only way to make a copy. Copies folder shows where your copies go. Change… picks another folder: new copies go there, and the copies already made stay where they are. Show in folder opens it. About shows the version, the third-party licences and the licence agreement. Settings The copier’s sounds and the animation sounds Quick and Reduce"
 },
 {
  "url": "documentation.html#appearance",
  "heading": "Light and dark",
  "text": "Flipcopy has a dark mode and a light mode, both in Freally green. In Settings, under Appearance, choose Dark or Light: each is shown by its own copier. The change is immediate, with no flash of the other colour, and it is kept on this computer, the same in the plugin and the standalone app. The copier is rendered on each mode’s own ground, so it always stands in one room, with no box around it. The panels, the glass, the dialogs and the keys come from one design that every Freally app shares, and the knobs, faders, sliders, switches and keys are rendered for each mode. The standalone app’s title bar follows the mode too, with no title in it: the turning wordmark is the title. Under Motion, Reduce lays the turning title flat: with reduced motion, whether you chose it or your system asks for it, the title stops square to you, level and still. Quick turns it in half the time, as it speeds up everything else, and reduced motion still wins over both. Under Sounds, Animation sounds turns the sounds of dialogs and panels opening and closing on or off, beside the copier’s own sounds. Light and dark"
 },
 {
  "url": "documentation.html#problems",
  "heading": "When something goes wrong",
  "text": "If Flipcopy itself fails, such as a copy it could not write, the screen offers Report. It opens a page in your web browser that shows exactly what the report holds; nothing is sent unless you press Send there. A file the copier refuses, because it is too long, silent or not audio, is not a failure, and the screen says why instead."
 },
 {
  "url": "documentation.html#language",
  "heading": "Languages",
  "text": "Flipcopy speaks eighteen languages. It starts in your system's language; to choose another, open Settings with the gear at the top of the browser and pick one. The choice applies to every copy of Flipcopy on the computer."
 },
 {
  "url": "documentation.html#privacy",
  "heading": "Privacy and the network",
  "text": "Flipcopy has no account and no telemetry, and the plugin and standalone app contain no networking code at all. Your files and your copies never leave your computer. It contains no AI of any kind: every copy is made by classic, deterministic signal processing, and a build gate fails if a machine-learning library is ever added."
 },
 {
  "url": "changelog.html#0-6-0-2026-10-09-in-every-daw-added",
  "heading": "Added",
  "text": "Saved with your project. The original on the glass is kept with your DAW's project, and the glass shows it again when you reopen it. If the file has moved, the glass says The original has moved , with Locate… to find it. A project whose Flipcopy state can't be read opens with an empty glass and says so; nothing from an earlier project is ever carried over. A newer Flipcopy's settings in a project are kept as they are, so opening a project in an older version and saving it again loses nothing. Scan from track. In a DAW, Copy Settings has Scan from track : choose 1 to 16 bars, Arm , and press play in your DAW. The track's audio — or the notes it receives — is captured as it plays, written as a new file in your Copies folder's Captures folder, and put on the glass. Nothing is copied until you press START. The panel says what a host won't send: Ableton Live gives an audio effect no MIDI, and Logic may not run a track that isn't live. Drag a file straight into your DAW. A grip at the end of every audio and MIDI file in the browser, and on the Preview strip, drags the file itself onto a track. The row itself still drags onto the glass. The drag shows the exact clip. While a page or a fil"
 },
 {
  "url": "changelog.html#0-6-0-2026-10-09-in-every-daw-changed",
  "heading": "Changed",
  "text": "The pianos sound like pianos. The Grand, Acoustic, Upright and Honky-Tonk pianos — the default toner among them — play Freally MIDI Master's new acoustic voice, built from measurements of a recorded concert grand and upright, with no buzz. A copy you made before keeps the piano it was made with: REPRINT and its ticket make it again exactly as it was. A piano copy, copied back to MIDI, reads less well for now. The new pianos ring with real overtones, and the copier can hear them as a line of their own: the melody page may come out an octave or more too high, with the true notes on the countermelody page. Other instruments read as before. A later version teaches the copier to tell a note from its overtones. Eight copiers at once. Eight instances, each with its sounds, its preview and a scan running, cost well under one percent of a 256-sample block; an editor with nothing moving runs no animation loop. Arrow keys and the mouse wheel move a fader one step, with or without Shift. A tenth of a decibel is the finest a fader holds; Shift still makes a drag finer."
 },
 {
  "url": "changelog.html#0-6-0-2026-10-09-in-every-daw-fixed",
  "heading": "Fixed",
  "text": "Two Flipcopy windows opened at once both open. Opened together — two standalones, or a DAW that runs each plugin in its own process and restores their windows — an editor could stay blank. Fixed in the webview the Freally apps share. No click when your DAW changes its sample rate or buffer size while the preview plays: the sound comes back in where it was, faded in over five milliseconds. The search for an instrument, and every other thing the window asks of the plugin, is held to a size; a request too large is refused unread. v0.5.9 2026-10-09 Light Mode A light mode beside the dark one, both in Freally green — and one look, one set of rendered hardware, for every Freally app."
 },
 {
  "url": "changelog.html#0-5-9-2026-10-09-light-mode-added",
  "heading": "Added",
  "text": "Light and dark. Settings → Appearance : Dark or Light, each shown by its own copier. The change is immediate, with no flash of the other colour, and kept on this computer, the same in the plugin and the standalone. The copier is rendered on each mode's own ground, so it always sits in one room with no box around it. The Freally look. The panels, the glass, the dialogs and the keys come from one design shared by every Freally app — modern, sleek and futuristic, in light and in dark — and the knobs, faders, sliders, switches and keys are rendered for each mode. The title bar follows the mode. The standalone's title bar is light in light mode and dark in dark mode, with no title (the turning wordmark is the title)."
 },
 {
  "url": "changelog.html#0-5-9-2026-10-09-light-mode-changed",
  "heading": "Changed",
  "text": "Reduce lays the title flat. With reduced motion — Flipcopy's own setting, or your system's — the turning title stops square to you, level and flat, rather than held at an angle. Quick turns the title faster : in half the time, as everything Quick speeds up. Reduced motion still wins over both speeds. Every key is one width , in every language, and labels that were too long for it are shorter. The Studio's play, stop and loop are plain buttons , as a transport's are. Settings → Sounds says what its switch does : Animation sounds — the sounds of dialogs and panels opening and closing — on or off, beside the machine's own sounds. v0.5.7 2026-10-06 The Mixer and Your Own Instruments The Studio gets a mixer and a sound for every part. Mix the parts with realistic faders and knobs, shape each instrument with Freally MIDI Master's synth controls, and play the parts through your own samples — a drum kit of your one-shots, or one sample across the keyboard — kept in one instrument library every Freally product on your computer shares."
 },
 {
  "url": "changelog.html#0-5-7-2026-10-06-the-mixer-and-your-own-instruments-added",
  "heading": "Added",
  "text": "Notes, Mixer and Sound. Three views in the Studio, side by side at its top; the arrow keys move between them. The mixer. A strip for every part and one for the master: a fader with its meter, pan, solo and mute, and — for a part on a library instrument — MIDI Master's channel strip: Low, Mid and High, Room, Echo, Heat and, for an instrument that sings, Pitch Mod. The meter runs green, then yellow from −12 dBFS, then red from −3, and its clip light comes on at 0 dBFS and stays on until you click it. The mixer is the copy's: what the Studio plays is what START prints, and a part with its fader all the way down is not printed. Realistic faders, knobs and keys. Rendered in Blender for every Freally product: the faders, every knob, the command keys and the toggle keys, with a pressed animation (reduced motion keeps the press without the glow). Drag, hold Shift to move finely, turn the mouse wheel, double-click to go back, or use the keyboard; every one says its value. Realistic sliders and on/off switches. Every slider has a gray, grooved thumb on a groove lit up to it, and every on/off setting is a pill switch — lit when it is on, its knob slid to that end, ON or OFF pressed into it. R"
 },
 {
  "url": "changelog.html#0-5-7-2026-10-06-the-mixer-and-your-own-instruments-changed",
  "heading": "Changed",
  "text": "Copy Settings says what the copy plays : a part on one of your sampler sounds, the drums on your kit, and a mixer set in the Studio — with a button to reset it. Choosing a part's instrument starts it as itself: the knobs moved on the instrument before, and a sampler sound, are let go."
 },
 {
  "url": "changelog.html#0-5-7-2026-10-06-the-mixer-and-your-own-instruments-fixed",
  "heading": "Fixed",
  "text": "Waveforms drawn from the sound itself. The preview's waveform — and the picture a file carries when it is dragged — is read from the file's own samples, every column its true peaks and its loudness, drawn as a DAW draws one: the peaks as a soft outline round a solid body. A short one-shot had drawn as a few flat blocks. A maximized window is filled. Maximized or made bigger, the standalone showed the app at the size it opened at, with a white edge beside it; now the whole window is the app, scaled as one. In Arabic, the Studio's SEND TO THE COPIER key sits at the end of its row again. v0.5.5 2026-10-06 The Studio A second tab beside the copier. Open a copy in the Studio and each of its parts is a tab in MIDI Master's own piano roll: change the notes, hear them through the instruments the copy prints with, and send the edit back to the glass — where the green START makes a new copy of it that drags into your DAW."
 },
 {
  "url": "changelog.html#0-5-5-2026-10-06-the-studio-added",
  "heading": "Added",
  "text": "COPIER and STUDIO. Two tabs above the machine — Ctrl+1 and Ctrl+2 ( Cmd on a Mac) from anywhere, or the arrows between them. Switching never stops anything: a copy being scanned carries on behind the Studio, and its pages are out when you come back. Each instance keeps its own tab. Open in Studio. The touch screen's STUDIO key opens the copy in the tray; in the browser, Open in Studio opens the copy of a file you select in Copies. A copy of an audio loop opens its MIDI pages, one tab each in page order; an audio copy opens the parts of the MIDI it was made from. The notes are read from the files the copy wrote — a copy whose files have moved or changed is refused, and the Studio says why. MIDI Master's piano roll. Draw a note with a double-click; drag a note to move it; drag its left edge [ or its right edge ] to lengthen or shorten it; box-select, Shift- and Ctrl-click; copy, cut, paste, clone ( Shift+D , or drag with Alt), delete (Delete, Backspace, or a right-click); nudge with the arrows; the velocity lane underneath; snap; undo and redo. Drums show their kit voices by name down the side. Hear it. PLAY, STOP and LOOP, and a solo and a mute on every part. What plays is exactly t"
 },
 {
  "url": "changelog.html#0-5-5-2026-10-06-the-studio-changed",
  "heading": "Changed",
  "text": "The fan of pages is wider. Every page under the top one shows its left and front edges, wide enough to Shift-click and grab; a page you raise goes to the top of the pile and the pages under it close up. A Shift-click picks a page without moving the pile. A one-part MIDI file is copied as the part its name says. A file of a single line named for its part — …-Bass.mid , … - Countermelody - … — is copied as that part, through that part's instrument, rather than guessed from how high or low it sits."
 },
 {
  "url": "changelog.html#0-5-5-2026-10-06-the-studio-fixed",
  "heading": "Fixed",
  "text": "A long row of buttons under a selected file in the browser could push the browser under the copier; it now wraps. A file the copier writes is never written over another that a second copier (another instance of Flipcopy in your DAW) saved under the same name a moment before; it takes the next free name. v0.5.0 2026-10-05 The touch screen The copier's touch screen comes alive. Copy Settings opens out of it — which parts to copy, the grid, the swing, the tempo, the instruments, the format — and every setting changes the copy you make; the screen's keys page through your copies, save them, show them and print them again; and a copy can go back on the glass to be copied the other way."
 },
 {
  "url": "changelog.html#0-5-0-2026-10-05-the-touch-screen-added",
  "heading": "Added",
  "text": "Copy Settings. Press SETTINGS on the touch screen and the panel grows out of it. For an audio loop: copy every part , one part only (drums, bassline, melody or chords — refused, never a blank page, when the loop has none of it), or the vocal line , read as one note at a time; put the notes on a grid (1/8, 1/16, 1/32 or 1/16T) and straighten a swing. For a MIDI file: a page per part, or the mix only ; an instrument for each part — search the library by name, genre or family — and a drum machine (808, 909, 707, 606); the tail after the last note; WAV , AIFF , FLAC or MP3 (320 kbps), at 44.1, 48, 88.2 or 96 kHz, in 16, 24 or 32-bit float. Both ways: the tempo — automatic, the project's, the file's own, the file name's, or one you set. Changes are for the next copy, never one being made, and the project keeps them. Every page says its instrument on its TONER line, beside its tempo and where that tempo came from. The file name's tempo, offered. A MIDI file with no tempo of its own whose name says one ( Hook 127 BPM.mid ) gets a chip by the screen: Use 127 BPM copies that file at it; the project's tempo never moves. The stack. ◀ PREV and NEXT ▶ (or [ and ] ) page through your copies, eac"
 },
 {
  "url": "changelog.html#0-5-0-2026-10-05-the-touch-screen-fixed",
  "heading": "Fixed",
  "text": "A page under the top one can be pressed where it shows past the tray's edge. v0.4.0 2026-10-05 The file browser and the preview player Find a sample or a MIDI clip, hear it, see it, and put it on the glass — the browser and the preview player from Freally Oscillate, beside the copier. Everything essential is here: the MVP is complete."
 },
 {
  "url": "changelog.html#0-4-0-2026-10-05-the-file-browser-and-the-preview-player-added",
  "heading": "Added",
  "text": "The browser. It opens on its Categories — Copies , every page and mix you have made, and Recent , the originals you last put on the glass, each counted — then the folders you add with + Add Folder (up to 128). A folder on a drive that is unplugged keeps its place and says so; right-click a folder, or select it and press Delete , to stop browsing it, and nothing on disk is touched. Back and Forward move through where you have been, exactly as in Freally Oscillate. A folder as a tree. Expand and collapse it, type to filter it, narrow it to a tag or to your stars, and choose Show all files to see the sidecar files it hides ( .asd , .reapeaks and the like). ↑ / ↓ walk the rows and each one you land on plays once; → opens a folder, ← closes it, and Enter puts the file on the glass. Indexing you can watch. A new folder is counted on a thread of its own with a bar that shows how far it has got — at most 12 folders deep and 50,000 files, never following a shortcut out of the folder. The preview player , docked under the browser. Audio shows its real waveform; a MIDI file shows its notes and plays through Preview Piano , the very sound and render a copy uses, so the preview is the copy. Spa"
 },
 {
  "url": "changelog.html#0-4-0-2026-10-05-the-file-browser-and-the-preview-player-changed",
  "heading": "Changed",
  "text": "The docs site is built from the shared Freally site kit, the same on every Freally site, with its manual updated for this version."
 },
 {
  "url": "changelog.html#0-4-0-2026-10-05-the-file-browser-and-the-preview-player-fixed",
  "heading": "Fixed",
  "text": "A page under the pointer is found at any window size. A click or a drag on a page landed in the wrong place once the window was scaled. v0.3.0 2026-10-01 Audio → MIDI: the magic moment Put an audio loop on the glass, press START, and its MIDI comes out — one page for every layer the copier hears, back to back from one scan, each its own file, framed in lime and dragged into your DAW on its own or all together. A MIDI file with several parts comes out the same way: one audio page per part, and the whole file as one mix."
 },
 {
  "url": "changelog.html#0-3-0-2026-10-01-audio-midi-the-magic-moment-added",
  "heading": "Added",
  "text": "Audio → MIDI. An audio loop is read into its layers — drums, bass, melody, a countermelody where the loop has a second, independent line, and chords — with MIDI Master's classic-DSP extractor (no AI). Each layer found is its own page and its own .mid , named as a DAW shows it ( Loop - Bassline - 120 BPM - C# Minor ); a layer that isn't there gets no page, and a loop with no notes at all is refused rather than copied blank. The key is printed only when it was read clearly. A stack of pages. The pages eject one after another from the single scan, fanned on the tray, each titled by its form and its part ( MIDI MELODY , AUDIO BASSLINE ) with PAGE n/N . Click a page to bring it to the top. Nothing drags until the last page has landed. Two drags from the finished stack. The top page carries two lime tabs: All parts drags every page as separate files, so the DAW lays them out as one track per layer; Complete mix drags one file of everything — a multi-track .mid of every part, or the whole render as a .wav — written beside the pages and never printed. Hover the tab for the mix's facts; without a pointer, Save the complete mix as… saves it. MIDI → audio, part by part. A MIDI file with sever"
 },
 {
  "url": "changelog.html#0-3-0-2026-10-01-audio-midi-the-magic-moment-changed",
  "heading": "Changed",
  "text": "The host's tempo is followed block by block , and a MIDI file with no tempo of its own is copied at the host's tempo at the moment you press START. The session tempo only breaks the octave tie. A 120 BPM loop dropped in a 90 BPM session is read at 120 (four bars), not at 90 (three) — fixed in MIDI Master's shared extractor, for every Freally product that reads loops. Free today, not promised forever. Freally Flipcopy is free today, but it might not be free forever: future versions may be sold. Every page of the docs site now says so. The repository moved to the maintainer's own GitHub account, private and All Rights Reserved, with the shared Freally crates coming from Freally MIDI Master and Freally Oscillate beside it; the plugin's web address is the docs site's new one. Continuous integration runs on the maintainer's machine before every push — every gate on Windows, and the Linux gates in Docker Desktop — and none on GitHub Actions. Every commit carries [skip ci] . (For a few hours on 2026-09-30, the repository was public and CI ran on GitHub for every push.)"
 },
 {
  "url": "changelog.html#0-3-0-2026-10-01-audio-midi-the-magic-moment-fixed",
  "heading": "Fixed",
  "text": "The editor keeps its own browser profile. Flipcopy's WebView2 data ( %APPDATA%\\Freally Flipcopy\\webview ) had been filed under Freally MIDI Master's folder, and two products sharing one WebView2 profile can leave each other's editor blank when both run in the same DAW. It is Flipcopy's own now. A copy's Complete mix can only ever be its own file : a record.json edited behind the copier can't point a drag, a Save As or a Reveal anywhere else. A copy is written whole or not at all. Every page and the mix are on disk before any of them takes its name, so a failure part-way never leaves pages in a numbered folder that no copy owns. No page clips. The one headroom gain is set by every file a copy writes — a part can peak above the mix where the others cancel it. A 16-bar loop exported a tick long is 16 bars , not 17 — a last note released a thirty-second past the bar line is not a bar of its own. Controllers reach a page even on a channel that plays no notes. v0.2.0 2026-09-30 The copier and the first copy The copier stands on the stage, playing the Blender copier story videos' beats in their order: drop a MIDI file on the glass, press the green START, and a real audio copy comes out on"
 },
 {
  "url": "changelog.html#0-2-0-2026-09-30-the-copier-and-the-first-copy-added",
  "heading": "Added",
  "text": "The copier on the stage. The machine rendered by the same Blender scene as the two story videos — its base, its lid as sprite frames, the pressed keys, the glass and tray mattes — rendered over the window's own ground ( #090c09 ) on transparent film, so it stands in the room with no seam. The phases are the videos' beats in the videos' order (the sheet flips and lands face-down, the lid swings shut with its bounce, the START beep, the lamp sweeps side to side leaking cyan out of the front seam while the whole room dims, the copy slides out onto the tray), at the in-app cut's shorter durations; a test fails if the app ever plays a beat the story doesn't have, skips one, or plays them out of order. It fills whatever room the window gives it and never mirrors in a right-to-left language. The green START is the only trigger. Dropping a clip only puts it on the glass. START (or Ctrl/Cmd+Enter , which presses the same key) starts the copy; STOP (or Esc ) cancels it mid-scan with nothing left behind; HOME clears the glass. The key carries an angled START , turned to the touch panel, and its LED is lit whenever a copy can start. A plugin test sends every command and fails if any but copier"
 },
 {
  "url": "changelog.html#0-2-0-2026-09-30-the-copier-and-the-first-copy-changed",
  "heading": "Changed",
  "text": "Shared code : freally-extract (the decode door and the audio analysis), freally-encode (WAV, resampling, the DAW-grid chunks) and freally-drag (the native drag source) are consumed from MIDI Master at shared-v5 , with freally_library::audition::NoteRenderer , read_facts ' controller events, and the web view adapter's file-drop hook, its re-placing of the web view when the window moves and its blank caption added upstream there. The icon is the owner's own — the lime F over a waveform and a piano roll — on the executable, the plugin bundles, the Linux and macOS icons and the docs site, in place of the placeholder. The window. The standalone's title bar wears the icon, is dark and the colour of the room, and says nothing: no title in the title bar of the standalone or of a plugin window in a DAW whose caption names Flipcopy, since the turning name across the top of the window already says it. That turning name is twice the size, to be read at a glance, and centred over the copier's side of the window; the file browser runs from the top of the window to the preview dock beside it. The bridge takes requests up to 2 MiB (a drag image); host_info says whether a page can be dragged here. "
 },
 {
  "url": "changelog.html#0-2-0-2026-09-30-the-copier-and-the-first-copy-fixed",
  "heading": "Fixed",
  "text": "Moving the window on a scaled display. With Windows set to 150 %, dragging the standalone window by its title bar drew its contents a third of the way behind the window, towards the screen's top-left corner, hiding the right and bottom edges until the window was moved back to that corner. The contents now stay exactly under the window wherever it is moved. The standalone at your display's own scale. On a scaled display (150 %) the standalone ran as an old-style, unscaled program: Windows stretched its window while the page inside it drew at true pixels — the root of the drag and drop-down misplacements listed here. It now declares itself per-monitor DPI aware before it opens a window, as Freally MIDI Master's and Freally Unloop's standalones do, so the page draws crisply at the display's scale and the window opens at its intended size. The language list opens under its field. On a scaled display the system's own drop-down list opened down and to the right of the Settings field, further off the further the field sat from the window's corner; the list is now drawn by Flipcopy itself, straight under the field, in the window's own dark style, with each language written in its own scrip"
 },
 {
  "url": "changelog.html#0-1-0-2026-09-26-foundation-ci-spine-added",
  "heading": "Added",
  "text": "The plugin, in every format from one binary. A nih-plug CLAP plugin with VST3 and AUv2 entry points projected by clap-wrapper (licence-clean: no GPL VST3 bindings), plus the standalone application — a native desktop app with its own window and audio device, never a web app. Stereo in and out, a note input for the later \"Scan from track\", zero latency, and the track's audio passed through bit for bit (a null test proves it). A host Bypass switch and a Monitor level for the sound Flipcopy itself will add (the machine's sounds and the preview, from v0.2.0 ) — it never touches the track. A versioned saved state that is bounded, migrated and refused as a whole rather than half-loaded, so a damaged project never crashes the host. The licence agreement ( EULA.md , structured like Freally Oscillate's) and its gate: Flipcopy asks you to accept it on first open and stays inert until you do — it reads nothing, copies nothing and adds nothing to your track. The agreement is compiled into the plugin and served from it, Agree waits until the text has been read to the end, and your answer is shared by every open instance and the standalone. A decline that could not be saved says so. The window , "
 },
 {
  "url": "changelog.html#0-1-0-2026-09-26-foundation-ci-spine-security",
  "heading": "Security",
  "text": "The editor loads only the page compiled into the binary, under a strict Content Security Policy; its bridge answers only the page's own JSON POST , refuses anything over 64 KiB and any path with .. , and before the agreement is accepted answers only an allowlist of commands. Release builds open no DevTools and no remote-debugging port. No network code in the plugin or the standalone, checked by the compiler ( clippy.toml ) and the dependency graph ( scripts/check-denylist.mjs ). The files Flipcopy keeps in your app-data folder (the agreement answer and the preferences) are read with a size bound and written atomically, so a damaged or hand-edited file loads as the defaults and a crash never leaves half a file."
 }
];
