/* ⛔ GENERATED by kit/build.mjs from the rendered pages. Do not edit.
 * ⚠ There is no search service behind the box: the index is this file. */
window.FREALLY_SEARCH_INDEX = [
 {
  "url": "features.html#pace",
  "heading": "A real reading pace",
  "text": "Characters per second, or BPM from 20 to 250 for lyrics and verses read to a track. Change either while the script runs and the scroll re-paces at once."
 },
 {
  "url": "features.html#pauses",
  "heading": "Pause chips",
  "text": "Type -- for a short pause or --N for an N-second hold. Each is one chip the cursor cannot split, it lights up as the read reaches it, and read-aloud turns it into a real silence."
 },
 {
  "url": "features.html#engine",
  "heading": "Every screen on the same word",
  "text": "The preview, the projector and the devices on your network follow one engine, counted in characters, so they agree on the word being read even at different text sizes."
 },
 {
  "url": "features.html#projector",
  "heading": "A projector for the talent",
  "text": "Full screen on any display, mirrored for beam-splitter glass, with its own transport and keys for the person reading."
 },
 {
  "url": "features.html#mirror",
  "heading": "A mirror to phones and tablets",
  "text": "Off until you switch it on. A link and a QR code open the script in any browser on your own network: read-only, with a key that changes every time the app starts."
 },
 {
  "url": "features.html#import",
  "heading": "Import Word, RTF, PDF, text and Markdown",
  "text": "Clean prompter text with its paragraphs kept, and a report that counts what could not come across — pictures, footnotes, comments. Nothing is saved until you say so."
 },
 {
  "url": "features.html#markers",
  "heading": "Section markers, find and replace",
  "text": "A line that starts with # is a marker on the seek bar and in a jump list. Find and replace matches case or whole words, and is undone in one press."
 },
 {
  "url": "features.html#timing",
  "heading": "Tempo, click and bars",
  "text": "Tap your tempo to fit BPM to your own delivery, hear a click with a count-in, and see the bar and beat on screen and as lines on the seek bar."
 },
 {
  "url": "features.html#rehearsal",
  "heading": "Rehearsal and a timing report",
  "text": "Read it through and see each section's planned time against the real one, and the pace you actually read at. It records timings only — no microphone, no audio."
 },
 {
  "url": "features.html#skip",
  "heading": "Labels that take no time",
  "text": "Mark Chorus, [Verse 1] or ## Bridge as words you do not perform: they stay on screen, dimmed, and take no read time, so your lyrics stay on the bar."
 },
 {
  "url": "features.html#control",
  "heading": "Shortcuts, pedals and hotkeys",
  "text": "A searchable map of every command, with clashes flagged. Pedals and remotes bind like any key, and a key can work while another app is in front."
 },
 {
  "url": "features.html#writing",
  "heading": "Autocomplete, dictation and read-aloud",
  "text": "Word and phrase suggestions in 18 languages from lists inside the app, dictation in English that runs on your computer, and read-aloud in your system's own voices."
 },
 {
  "url": "features.html#look",
  "heading": "Your look, your language",
  "text": "Typeface, size, weight, colour, margins, line spacing and the reading line, on every screen at once. The app speaks 18 languages, in a dark or a light theme."
 },
 {
  "url": "features.html#private",
  "heading": "No account, no cloud",
  "text": "Scripts are plain files on your computer, and there is no telemetry. The app's only request to the internet is a check for a newer version, and nothing installs without your yes. Compare Side by side with the commercial teleprompters Freally Teleprompt 1.5.0 — the released version, the one you can use today — next to six commercial teleprompter apps. Every cell for another product comes from its maker's own pages or app-store listing, checked on 2 October 2026, and prices are in US dollars as of October 2026. Feature Freally Teleprompt 1.5.0 PromptSmart Speakflow Teleprompter.com Teleprompter Pro PromptDog TeleScroll Price (USD, October 2026) Free today $9.99 a month $19 a month $19.99 a month $59.99 a year $69 one-time on sale; usually $99 $249.99 Desktop app for Windows, macOS and Linux has it Windows · macOS · Linux has it + iOS · Android partly Windows · Mac and in a web browser partly iOS · Android · Mac and in a web browser partly iPhone · iPad · Mac partly Windows · Mac partly Windows · Mac Use it without making an account has it does not does not does not not verified does not not verified Works with no internet connection has it only the update check goes online has it doe"
 },
 {
  "url": "documentation.html#start",
  "heading": "Getting started",
  "text": "Freally Teleprompt is a teleprompter for Windows, macOS and Linux, for presenters, streamers, podcasters, actors, singers and rappers. It opens as one window — your scripts, the editor, the preview and the projector controls — and needs no account. The first time it opens, it shows its licence agreement. Scroll to the end, then choose I Agree, or Decline & Quit. The app cannot be used until you agree; your answer is remembered, and you are asked again only if the agreement changes. A one-minute tour then shows the editor, the pace controls and the projector. Type or paste a script, set your pace and press play. There are no downloads on this site, and the source code is private."
 },
 {
  "url": "documentation.html#write",
  "heading": "Write a script",
  "text": "Scripts are .ftscript files: plain text in one folder, readable in any text editor. Open Scripts on the toolbar to create, open, rename and delete them. A recent list takes you back to what you were working on, everything is saved as you type, and the app reopens the script you had open last. Type in the editor or paste from anywhere. Under the read-time estimate, a live word and character count shows what you will actually perform — skipped labels and pause marks are not counted — and a warning marks any line long enough to be a whole paragraph."
 },
 {
  "url": "documentation.html#import",
  "heading": "Import a document",
  "text": "Press Import on the toolbar and choose a Word document (.docx), an RTF, a PDF, a plain text file or a Markdown file. You see the text it produced, and a report, before anything is saved. Paragraphs are kept; bold, fonts and colours are flattened, because a prompter shows one typeface. Curly quotes, long dashes and ellipses become plain ones, and a file saved in an older encoding is read correctly, and the report says so. Pictures, footnotes, comments, headers and footers, link addresses and embedded objects are counted and listed, never dropped quietly. A PDF has no such structure, so for a PDF the report says it could not tell. Name the script — a name is suggested from the file — and press Import. It is added to your library and opened, and it never overwrites a script that already exists. Markdown headings arrive as # lines, so a Markdown script comes with its section markers. A typeset dash becomes an ordinary hyphen, and two of them never turn into a pause, so an imported play does not arrive full of pauses nobody wrote. A text file you wrote with real pause marks keeps them."
 },
 {
  "url": "documentation.html#find",
  "heading": "Find and replace",
  "text": "Press Ctrl+F, or Find on the toolbar, to search the open script. The match count updates as you type; Enter goes to the next match and Shift+Enter to the previous one, wrapping round at both ends. Match case and whole words only narrow the search, and what you type is searched for literally. Replace changes the current match and Replace all changes every one; either is undone with a single Ctrl+Z."
 },
 {
  "url": "documentation.html#markers",
  "heading": "Section markers",
  "text": "Begin a line with # — # Verse 2, # Q&A, ## Bridge — and it becomes a section marker. Any line that is one of your skip words, such as [Chorus], is a marker too. There is nothing to set up. Markers appear in a jump list beside the seek bar, which shows the section you are in, and are ruled onto the seek bar itself. Next and Previous walk them; Previous goes to the top of the section you are in first, like a previous-track button. Choosing one moves every screen, the projector included."
 },
 {
  "url": "documentation.html#pauses",
  "heading": "Pause chips",
  "text": "Type -- (a space, two dashes, a space) for a short pause, or --N for a hold of N seconds. Each becomes a chip in the editor: the cursor sits only before or after it, one Backspace removes it, and Shift with an arrow key selects it whole. Set the length of a plain -- under Settings → Reading. Copy and paste carry chips intact, and pasted text has its spacing tidied so every pause lands as a clean chip. While the script plays, each pause lights up as the read reaches it and the scroll holds for its length — on the preview, the projector and the network mirror alike."
 },
 {
  "url": "documentation.html#pacing",
  "heading": "Pacing: characters per second or BPM",
  "text": "Set the speed in characters per second: a real reading rate that every screen follows, whatever its font size. Or switch to BPM, from 20 to 250, to read lyrics and verses in time with a track. Both drive the same engine, and changing either while the script runs re-paces it at once."
 },
 {
  "url": "documentation.html#tempo",
  "heading": "Tempo, bars and the click",
  "text": "A tempo becomes a reading speed through one number: how many characters you read in a beat. Under Settings → Timing → Your own tempo, press Tap three times or more at the tempo you perform at, then choose Use this tempo; Back to the default undoes it. The BPM box then offers only the tempos the engine can reach. With BPM on, or the click switched on, the bar and beat appear above the seek bar and bar lines are ruled onto it. Set the beats in a bar, from 2 to 12, under Settings → Timing. Tick Play a click at the current tempo for a quiet tick on every beat, higher on the first beat of each bar; the start countdown becomes its count-in. The app makes the sound itself and times every tick against the audio clock, so it does not drift. It stays silent while read-aloud is speaking."
 },
 {
  "url": "documentation.html#rehearsal",
  "heading": "Rehearsal and the timing report",
  "text": "Tick Rehearse, and time my read under the transport, press play and read aloud as you would on the day. Pause, go back, change the speed: all of it is part of the measurement. Untick it and the rehearsal report opens: one row per section, with the time it should have taken at your pace, the time it took and the difference. Sections are your paragraphs, or your section markers when the script is divided by them. If you read at a different pace, the report offers that speed, and one click applies it. While you rehearse, a quiet warning appears once the read is three seconds or more behind or ahead of its plan. Rehearsal records timings and nothing else: it opens no microphone and keeps no audio, and it cannot run together with read-aloud."
 },
 {
  "url": "documentation.html#skip",
  "heading": "Words you do not perform",
  "text": "Section labels — Chorus, Verse 2, Bridge — are landmarks you see coming but never say. List them under Settings → Timing → Words you do not perform, one per line. The list starts empty, because it changes how a script is timed. A line that is nothing but a label is skipped whole: brackets, hashes, a colon and a trailing number are seen through, so Chorus, [Verse 1], ## Bridge and Chorus: all match. The same word inside a real line skips only itself. Matching ignores capitals and only matches whole words. Skipped text stays on screen, dimmed, so the talent still sees it coming, and read-aloud never says it. Because a label takes no time, the scroll passes it at once — and your lyrics stay on the bar you wrote them for."
 },
 {
  "url": "documentation.html#playback",
  "heading": "Playback and the transport",
  "text": "Play, pause, stop, rewind and fast-forward are on-screen buttons; hold rewind or fast-forward to keep going. Spin the mouse wheel to scrub, click a word to start from it, or hover over the seek bar to see the words at that point. The seek bar shows the elapsed and total read time, pauses included. A reading guide keeps the current word on the reading line, and the last lit word never scrolls out of sight."
 },
 {
  "url": "documentation.html#shortcuts",
  "heading": "Shortcuts, pedals and hotkeys",
  "text": "Open Shortcuts on the toolbar. Press the binding you want to change, then press the key, remote or pedal you want; Escape leaves it as it was. Search by a command's name or by the key itself. If two commands share a key, both rows say so; clear one with ×, or choose Restore defaults. Most foot pedals and presenter remotes send ordinary keys, usually F13 to F24, so they bind with no driver and no setup. Bindings follow the physical key, not the letter printed on it, so they survive a change of keyboard layout. The Anywhere column asks your system to deliver a key even when another app is in front — a camera app, a DAW or OBS. Nothing is claimed until you set it, and a key another program already owns says so. Under Wayland on Linux, apps cannot claim keys system-wide, and the dialog tells you. While you are writing, the space bar, the arrow keys and Home type as normal: a bare key runs its command only outside the editor."
 },
 {
  "url": "documentation.html#countdown",
  "heading": "Start countdown",
  "text": "Set Countdown before starting under Settings → Reading, and pressing play counts down that many seconds first, on the preview and the projector, so the talent has a moment before the first word moves. With the click on, the countdown is also the count-in."
 },
 {
  "url": "documentation.html#projector",
  "heading": "The projector",
  "text": "Press Projector and choose the display the talent reads from: the script fills that screen edge to edge. Turn on the mirror for beam-splitter glass, where the reflection would otherwise read backwards. The projector has its own transport, seek bar and keys for the person reading. The preview and the projector lay the script out at the same width and scale it to fit, so they break lines in the same places. Check that the mirrored text reads correctly through your own glass before a shoot."
 },
 {
  "url": "documentation.html#mirror",
  "heading": "The network mirror",
  "text": "To show the script on a phone, tablet or second laptop, open Settings → Network → Mirror to my network and tick Mirror the script to devices on my network. Tick Allow other devices, not just this computer as well — without it, the mirror answers only on this computer — and press Apply. A link and a QR code appear: scan the code, or open the link in a browser on the same network. The mirror follows the same engine, so every device is on the same word as the operator. Each device sets its own text size with A− and A+ without changing anyone else's screen. The page is served by the app itself, straight to your devices — never through this website, which a browser would not let reach a device on your network anyway. It is read-only: no browser can start, stop, seek or edit anything. Its link carries a key that changes every time the app starts. It is plain HTTP, so the key is not encrypted on the way: use it on a network you trust, not on public Wi-Fi. If a device cannot connect: check both switches; make sure it is on the same network, not on mobile data or a guest network that keeps devices apart; allow the app through your firewall for private networks when your system asks; and if "
 },
 {
  "url": "documentation.html#read-aloud",
  "heading": "Read aloud",
  "text": "Tick Read aloud with per-OS speech synthesis to hear the script in your system's own voices: Windows OneCore or SAPI, macOS AVSpeechSynthesis, or Speech Dispatcher or espeak-ng on Linux. No voice is bundled with the app. The transport, the seek bar and a click on a word drive the speech, and the highlight follows it — word by word where the system reports word boundaries, at your pace elsewhere. Pauses become short silences, and -- is never read out as \"dash\". Read-aloud is for the preview only: it never moves the projector. The checkbox is locked while a read is playing or paused, until you press Stop. Check that it speaks on the computer you will present from, especially on Linux."
 },
 {
  "url": "documentation.html#autocomplete",
  "heading": "Autocomplete",
  "text": "As you write, the rest of the word appears dimmed ahead of the cursor; finish a word and press space, and it can offer a whole common phrase. Tab accepts, Esc dismisses, and typing on ignores it. Each of the 18 languages has its own word and phrase lists — 463,985 words and 344,891 phrases in all — inside the app, and only the language you write in is loaded. Under Settings → Editor, turn it on or off and choose its language, which can differ from the app's. The lists are built from the Tatoeba sentence collection (CC BY 2.0 FR), credited in the NOTICE file that comes with the app. It is a dictionary lookup — instant, predictable and offline, with no model."
 },
 {
  "url": "documentation.html#dictation",
  "heading": "Dictation",
  "text": "Open Settings → Voice, tick Write my script by speaking and press Apply. A round record button appears above the script: press it and talk, and what you say is written where your cursor is. Press it again to stop; the microphone is open only in between. Dictated text is ordinary script text, and Ctrl+Z takes back one thing you said, not the whole session. Expect to tidy punctuation and names: it is a quick way to a draft, not a finished script. Dictation understands English only. It uses Vosk, an open-source speech recogniser, with a small English speech model — a trained neural network of about 40 MB — that ships inside the app. It runs on your computer, works with no connection, uploads and downloads nothing, and saves nothing but the text you see. It is off until you switch it on. If the script is mirrored to your network, dictated words reach those devices as they are written, like typing."
 },
 {
  "url": "documentation.html#settings",
  "heading": "Appearance, languages and settings",
  "text": "Under Settings → Appearance, set the typeface, weight and text colour, the side margins, the line spacing and where the reading guide sits; the font size is under Reading. They apply to the preview, the projector and the network mirror together. Settings work on a draft: nothing changes until you press Apply, and Cancel restores what you had. Choose one of 18 languages, or Same as my system. The theme is Dark, Light or Same as my system; the reading surface stays high-contrast whichever you choose. With Minimize to the system tray on, under Settings → General, minimising puts the app in the tray instead of the taskbar. Show the tour again, also under General, replays the welcome tour."
 },
 {
  "url": "documentation.html#access",
  "heading": "The tour and accessibility",
  "text": "The first time the app opens, after the licence, a four-step tour shows the editor and its pause marks, the pace controls and the projector. Skip, Esc or a click outside it closes it for good; Settings → General → Show the tour again brings it back. Every control shows a focus ring when you reach it from the keyboard. Tab stays inside an open dialog, Esc closes it, and focus returns to the button that opened it. The seek bar is a real slider: the arrow keys move one character, Page Up and Page Down a screenful, and Home and End go to either end. If your system asks for reduced motion, animations and blur are dropped while the script itself still scrolls; with reduced transparency, dialogs dim the background instead of blurring it."
 },
 {
  "url": "documentation.html#problems",
  "heading": "Problems and updates",
  "text": "When something goes wrong that the app can tell you about, its message has a Report button beside it. After a crash, the next launch shows a strip with Report and Dismiss. Report opens the Freally Teleprompt report page in your browser, with the technical details already filled in: you can read them, but not change them. Add what you were doing and, if you like, an email address. Nothing is sent unless you press Send on that page, and nothing is ever sent in the background. Once per launch, the app asks GitHub whether a newer version exists. If there is one, you see its version number and release notes and choose yes or no; an update is checked against a signing key inside the app before it installs. When you are offline or already up to date, it says nothing. Check for updates on the toolbar asks again at any time."
 },
 {
  "url": "documentation.html#privacy",
  "heading": "Privacy and the network",
  "text": "No account and no telemetry. Your scripts are .ftscript files on your computer, where you save them, and the app's author never receives them. The only request the app makes to the internet is the update check, which sends no script, no settings and no identifier. A problem report leaves only from the report page in your browser, when you press Send. The projector and the network mirror stay on your own displays and your own network. Machine learning is used in one place: dictation's speech model, which runs on your computer and is off until you switch it on. Autocomplete is a dictionary lookup, read-aloud uses your system's own voices, and nothing you type or say is sent to an AI service."
 },
 {
  "url": "changelog.html#unreleased-documentation",
  "heading": "Documentation",
  "text": "The website is rebuilt in the Freally family's design, and it speaks all 18 of the app's languages — this changelog included. It offers no downloads. v1.5.0 2026-08-05 Anything in the room can drive the prompter."
 },
 {
  "url": "changelog.html#1-5-0-2026-08-05-added",
  "heading": "Added",
  "text": "Foot pedals and presenter remotes. A pedal is how a prompter is actually driven on a shoot — your hands are on a camera, not a keyboard. Open Shortcuts , press the binding you want to change, then press the pedal: whatever it sends is what gets stored, with no driver and no setup. Most pedals and remotes send F13 – F24 precisely because nothing else uses them, and those now bind like any other key. Keys that work when Freally Teleprompt is not in front. The operator is usually in a camera app, a DAW or OBS, so every transport command can be given a second binding that the operating system delivers wherever you are. Nothing is claimed until you ask. No system-wide key is registered out of the box — taking one away from every other program uninvited is not something an app should do on first run. A refused key says so. If another program already owns the combination, the row tells you, with the reason. Under Wayland, which does not let applications claim keys system-wide at all, the dialog says that too rather than showing a binding that quietly does nothing. A searchable, rebindable map of every command , with conflict detection — search by what a command is called, or by the key it"
 },
 {
  "url": "changelog.html#1-5-0-2026-08-05-fixed",
  "heading": "Fixed",
  "text": "Importing a document (1.4.0's Import ), where the theme is: a converter that quietly changes your script is worse than one that refuses it. A PDF no longer claims to know what it left behind. Every other format is read by walking a document model, so \"nothing else was left behind\" is something the importer can actually check. A PDF has no such structure — an empty list there means we could not tell — and saying otherwise was a false reassurance on the format most likely to be carrying figures and footnotes. A Word text box is no longer reported as a missing picture. Its text was being imported all along, and counted as a picture that had been dropped at the same time. It now becomes its own paragraph rather than being spliced into whichever line happened to anchor it — \"we cut ON CAMERA to the wide\" is not what the document says. Pictures and running heads are counted once, and only where they are used. A single photo was reported as two, and Word writes three headers and three footers into every document whether or not they are used — so one running head was reported as six. An operator reading \"Pictures left out: 2\" goes looking for a second picture that never existed. Characters"
 },
 {
  "url": "changelog.html#1-4-0-2026-08-04-added",
  "heading": "Added",
  "text": "Open the file you were sent. Until now the only ways text reached the prompter were typing and pasting, which is not how any script arrives. Import on the toolbar reads Word ( .docx ), RTF, PDF, plain text and Markdown and turns them into clean prompter text: paragraphs kept, bold and fonts and colours flattened, curly quotes and em dashes and ellipses normalised, and a file saved in the wrong encoding read and reported rather than shown as mojibake. It tells you what it could not bring across — pictures, footnotes, comments, headers and footers, link addresses, embedded objects, each with a count. A converter that dropped them quietly is one you find out about on a shoot. Nothing is saved until you say so. You see the text and the report, name the script, and only then does a file appear in your library — and an import will never overwrite a script that already exists. Normalising a dash can never invent a pause: a typeset — becomes an ordinary hyphen, and two of them in a row do not turn into this app's -- caesura token. A .txt you wrote with real caesuras keeps them. Section markers, with a jump list. Any line beginning # — # Verse 2 , # Q&A — is a landmark, as is any line that "
 },
 {
  "url": "changelog.html#1-4-0-2026-08-04-changed",
  "heading": "Changed",
  "text": "The rehearsal report's sections now split on markers as well as skip labels, so a script written with # headings rehearses section by section with no keywords configured. A section is named without its decoration: [Verse 1] reports as Verse 1 ."
 },
 {
  "url": "changelog.html#1-4-0-2026-08-04-security",
  "heading": "Security",
  "text": "Every document parser runs in a separate process . Three of the five formats are read by third-party crates over a file the app did not write, and release builds abort on panic — so a malformed PDF would otherwise have taken the prompter down mid-read. It also gives the work a time limit and keeps a runaway parser's memory out of the app. The import's temporary file is created in a freshly-made directory with an unguessable name, and on Unix one only its owner can enter. v1.3.0 2026-08-03 Reading to time — and the words that shouldn't count."
 },
 {
  "url": "changelog.html#1-3-0-2026-08-03-added",
  "heading": "Added",
  "text": "Tap a tempo, and the app learns yours. BPM has always been turned into a reading speed with one number: how many characters you get through in a beat. It used to be a guess — the same guess for a balladeer and a rapper, who are an order of magnitude apart. Settings → Timing now lets you tap along at the tempo you actually perform at, and measures that number against your own reading speed instead of assuming it. A calibration that puts part of the musical range out of the engine's reach narrows the range the BPM box offers rather than showing you numbers it would quietly change underneath you. A metronome. An optional click on every beat while the script scrolls, accented on the first beat of the bar, with the start countdown doubling as its count-in. The app synthesises it — there is no audio file in the installer and nothing is fetched. It is scheduled against the audio clock from each beat's index, so it does not drift against the scroll: measured over a ten-minute read at the fastest tempo the app offers, the last click is still exact. A bar and beat counter , beside the reading surface, with bar lines ruled on the seek bar — so \"sixteen bars\" is something you can see rather th"
 },
 {
  "url": "changelog.html#1-2-0-2026-08-02-changed",
  "heading": "Changed",
  "text": "The record button is a button, not a sentence. It is now a circle with a glyph in it — ● to record, ■ to stop — with the instruction beside it rather than inside it, so the control stops changing width as you use it. Its colour follows your pointer as well as its state: hover the record button and it turns green, and while it is recording, hovering it turns it red. Moving away puts it back without changing what it will do. Dictated words now go through the editor , which is where they always should have gone. Three things follow from that, and each of them was a real fault before: Undo takes back one thing you said , not the whole session. Ctrl+Z used to jump past everything you had dictated in a single step. Text you type while recording is kept. The next thing you said used to overwrite it. Words land where your cursor is , not always at the end of the script."
 },
 {
  "url": "changelog.html#1-2-0-2026-08-02-fixed",
  "heading": "Fixed",
  "text": "Dictation reported itself ready when the speech-model folder existed, even if the model inside it was missing or half-copied — which put a record button on screen that could only fail when pressed. It now checks the one file the recogniser cannot start without. On an install under a drive-letterless volume (a folder-mounted drive), the model path handed to the recogniser was turned into one that named nothing at all. It now names the model. Whether the recogniser then loads it is untested on such a setup — but a failure there says which model it could not open, instead of quietly looking somewhere else entirely. Text inserted with the cursor at the very top of the script could land at the bottom instead. The editor could not read a cursor position sitting on the script as a whole rather than inside a line of it, and answered with the length of everything — so a paste, or a dictated line, went to the end. Dictation could report itself unavailable while a perfectly good model was installed : a stray or half-copied vosk-model-en in your data folder was preferred over the one inside the app, and then rejected for being incomplete. The app now passes over an unusable folder and uses the"
 },
 {
  "url": "changelog.html#1-2-0-2026-08-02-added",
  "heading": "Added",
  "text": "npm run dev:vosk for contributors — a development run that can actually dictate. Dictation is release-only otherwise, which made it awkward to work on."
 },
 {
  "url": "changelog.html#1-2-0-2026-08-02-documentation",
  "heading": "Documentation",
  "text": "The docs site's search finds dictation — the feature shipped in 1.1.0 and was not in the index, so searching for it returned nothing. In the other direction, search results that could only ever 404 are gone: the shared index listed five Freally apps that have no site yet, which was 39 of its 109 entries. THIRD-PARTY.md records Vosk (engine, model, and the Windows MinGW runtime) alongside the fonts; NOTICE now carries the pointers to that runtime's corresponding source. Both files ship inside the installer. The Settings note for dictation says what happens when the LAN mirror is on: dictated text reaches its viewers as it is written, the same as typing. v1.1.0 2026-08-02 One way to use your voice, and it works the moment you switch it on."
 },
 {
  "url": "changelog.html#1-1-0-2026-08-02-added",
  "heading": "Added",
  "text": "Write your script by speaking (FT-33) — turn on Dictation in Settings → Voice and a record button appears above the script. Press it and what you say is written in; press it again to stop. It needs no training and no setup: the speech model ships inside the installer, so it works the moment you switch it on. Nothing is downloaded at runtime and nothing is sent anywhere — the recogniser and its model are on your machine, and that stays true offline. The microphone is open only while recording, and nothing you say is written to a file but the text itself."
 },
 {
  "url": "changelog.html#1-1-0-2026-08-02-removed",
  "heading": "Removed",
  "text": "Voice commands are gone. They required you to record every command — play, pause, faster, slower, next pause, back to top — in your own voice before any of them did anything, and then to hold a button down while speaking. Until you had done that recording, holding the button opened the microphone and achieved nothing at all, with no way to tell that from a fault. Dictation covers the same ground with nothing to train. \"Follow my reading\" is gone for the same reason: one clear way to use your voice is better than three that overlap. The alignment work behind it still exists as a library and may return in a different shape. The installers are correspondingly larger than 1.0.0's — the speech model is about 40 MB, and it now ships whether or not you use it. v1.0.0 2026-08-02 The first published release: everything from Phase 3 (hands-free voice control) and Phase 5's polish pass, cut as signed installers for Windows, macOS and Linux."
 },
 {
  "url": "changelog.html#1-0-0-2026-08-02-added",
  "heading": "Added",
  "text": "A one-minute welcome tour (FT-50) — the first time you open the app, four short steps introduce the editor and its pause marks, the pace controls, and the projector. Skip it at any point, and run it again whenever you like from Settings → General → Show the tour again . A theme that follows your system (FT-50) — alongside Dark and Light there is now Same as my system , which switches with your OS and repaints immediately when your machine changes at sunset. Dark is still the default. Voice commands (FT-30, FT-31) — train play, pause, faster, slower, next pause, back to top in your own voice (a few takes each) and drive the prompter hands-free. A visible ● Listening indicator shows whenever the microphone is open; choose push-to-talk (mic open only while you hold a button) or always-listening . Off by default. Model-free: matched by classic signal processing against your own recordings, on-device. Voice-following (FT-32, FT-34, FT-35) — an opt-in mode that scrolls the script to keep up as you read it aloud, recognising the script's own words with a bundled Apache-2.0 Vosk model. It steps aside to manual the moment it loses your place (so it never scrolls somewhere wrong) and drives "
 },
 {
  "url": "changelog.html#1-0-0-2026-08-02-changed",
  "heading": "Changed",
  "text": "Keyboard and screen-reader accessibility pass (FT-50) — every focusable control now shows a clear focus ring; Tab stays inside an open dialog instead of wandering onto the window behind it; closing a dialog hands focus back to the button that opened it; and the Settings category list now reports the pane you are actually looking at, even while a search is filtering it. The app also honours reduce motion throughout. The script's own scroll is deliberately untouched by that setting — it is the thing the app is for, and you already control its speed directly."
 },
 {
  "url": "changelog.html#1-0-0-2026-08-02-privacy",
  "heading": "Privacy",
  "text": "No network, ever. Voice commands never touch the network or disk — audio is matched in memory against your own recordings, and nothing you say is written to a file. Voice-following runs the recogniser entirely on-device; the model ships in the installer and downloads nothing at runtime. _ Voice-following is not usable in this build. The recogniser needs a speech model, and this release does not yet bundle one — the feature detects that and reports itself unavailable with a reason, rather than failing when you turn it on. Voice commands are unaffected: they need no model and work here. The alignment and grammar layers underneath are complete and tested._ v0.300.0 2026-07-22 Offline autocomplete in the script editor: it suggests the rest of the word as you type, in any of the 18 languages, from word lists that ship inside the app."
 },
 {
  "url": "changelog.html#0-300-0-2026-07-22-added",
  "heading": "Added",
  "text": "Ghost-text autocomplete (FT-20, FT-21) — start a word and the rest of it appears dimmed ahead of the cursor. Tab accepts it, Esc dismisses it, and typing straight past it ignores it. It completes whole common phrases too, once you finish a word and press space. Autocomplete settings — a new Editor pane with an on/off switch and its own suggestion language , separate from the app's language, because writing a script in one language while running the app in another is normal. Word and phrase tables for all 18 languages (FT-22) — roughly 464,000 words and 345,000 phrases in total, bundled in the installer. Only the language you are actually using is loaded, so this costs the app about 0.5 MB of memory at a time rather than all 12 MB."
 },
 {
  "url": "changelog.html#0-300-0-2026-07-22-changed",
  "heading": "Changed",
  "text": "The language picker now starts with English and then runs alphabetically by each language's own name — Deutsch, Español, Français, and so on — and stays in that order whichever language the app is in. It previously followed the English names, so the order shifted depending on what you had selected."
 },
 {
  "url": "changelog.html#0-300-0-2026-07-22-privacy",
  "heading": "Privacy",
  "text": "Autocomplete never touches the network. It is a lookup against tables inside the installer — no model, no service, no telemetry. Nothing you type is sent anywhere, and the feature works with the machine offline. v0.200.0 2026-07-21 The standalone teleprompter: scripts you can keep, a projector for the talent, a real transport, and the prompter reading itself aloud."
 },
 {
  "url": "changelog.html#0-200-0-2026-07-21-added",
  "heading": "Added",
  "text": "Script library (FT-10) — .ftscript files you can create, open, rename and delete, with a recent list and autosave while you type. They are plain UTF-8 text in one folder, so a script stays readable, diffable and rescuable in any text editor if this app ever goes away. The app reopens whatever you had open last. Caesura chips in the editor (FT-11) — every inline -- / --2 renders as an atomic pill showing its pause length. The caret can only sit before or after one, Backspace/Delete removes the whole token in a single press, Shift+Arrow selects it as a unit, copy/cut carry the real -- text, and a pasted script has its sloppy spacing normalised. Typing the second dash expands a pause for you. Projector window (FT-12) — open the reading surface on any connected display, filling it edge to edge, with a mirror flip for beam-splitter prompter glass. It runs off the same scroll state as the operator preview, so the two can never disagree about where the read is, and it carries its own transport, seek bar and keyboard shortcuts for the person actually reading. LAN mirror (FT-12) — mirror the scrolling script to a phone, tablet or second laptop on your own network, from a link and QR code th"
 },
 {
  "url": "changelog.html#0-200-0-2026-07-21-changed",
  "heading": "Changed",
  "text": "The app draws its own window. No OS title bar: a centred title, with Settings, About, and minimise / maximise-restore / close on the right — the same arrangement Freally Player uses, so the suite's windows read alike. The bar is draggable, double-click still maximises, and the window is still resizable from every edge and corner. Settings is now a proper settings dialog , in the same shape as Freally Capture's: a category sidebar (General, Reading, Appearance, Projector, Network) with a search box, and an OK / Cancel / Apply footer. Apply is dead until something actually changes, and a dot marks the categories you have edited but not yet applied. Minimize to the system tray (Settings → General). Off by default. With it on, minimising hides the window and puts an icon in the tray; restoring brings the window back and takes the icon away — the app is in the taskbar or in the tray, never both. The tray menu is translated like the rest of the app. The app icon is now the full artwork at every size. 0.100.0 swapped in a cropped, glyph-only \"F\" for icons of 48px and below, on the grounds that the wordmark in the artwork is unreadable that small. One consistent mark turned out to matter m"
 },
 {
  "url": "changelog.html#0-200-0-2026-07-21-fixed",
  "heading": "Fixed",
  "text": "Found by the review pass over this phase, before release: A pause chip could appear where the prompter took no pause. The editor and read-aloud each carried their own copy of the -- grammar, without the bounds the scroll engine applies — so --2.5.3 was drawn as a pause the prompter would skip straight past. All three now share one scanner. Right-clicking the tray icon restored the window instead of opening the menu, which made the tray's own \"Quit\" unreachable. The first-run agreement's buttons could sit below the bottom of the window now that the app draws its own title bar. Settings could show a value the app was not using. A number the backend clamped (a port below 1024, say) kept displaying as the one that was typed until the next restart; the dialog now shows what was actually stored. Searching Settings could leave the wrong panel on screen , with no highlighted category to explain it. Stop is now one action in the engine rather than a pause-and-rewind pair composed by each button, so anything else that stops the scroll behaves the same way."
 },
 {
  "url": "changelog.html#0-200-0-2026-07-21-testing",
  "heading": "Testing",
  "text": "Playwright now covers every Phase 1 feature it can reach — the script library's whole lifecycle, chip behaviour, the display picker, the transport, BPM conversion, the appearance pipeline, and the contract that read-aloud never touches the shared scroll. The mocked bridge records IPC calls, so the tests assert what the UI actually asked the backend to do. The app is now launched and photographed on Windows, macOS and Linux every CI run ( scripts/app-screenshot.mjs ), failing if it dies on start or paints nothing. A compile that succeeds and a webview that renders are different things. Every language is checked for legibility, not just for strings. A test switches the app into each of the 18 locales and proves every character of its own interface is covered by a bundled font. A missing script renders as boxes, which looks like working text to a screenshot and to every other check — so Arabic, Hindi, Japanese, Korean and Chinese could each have broken silently, and only for the people who read them. A translation that quietly fell back to English now fails the build. Bulk translation passes leave English behind for anything they cannot translate, and the result parses and ships looki"
 },
 {
  "url": "changelog.html#0-200-0-2026-07-21-notes",
  "heading": "Notes",
  "text": "Still no AI, no accounts, no telemetry. The LAN mirror serves your script to devices you point at it, on your own network; nothing is uploaded or relayed. The only outbound request the app makes remains the update check. v0.100.0 2026-07-21 The scaffold phase: the app now builds, runs, and gates on the agreement, with the character-based scroll engine ported over from Freally Capture."
 },
 {
  "url": "changelog.html#0-100-0-2026-07-21-added",
  "heading": "Added",
  "text": "Tauri v2 scaffold (FT-00) — a Rust workspace ( src-tauri ) plus a React/TypeScript UI ( ui ), sharing Freally Capture's tooling shape: ci.yml , scripts/ci-local.mjs , deny.toml , and a pinned rust-toolchain.toml , so npm run ci:local runs the full gate from day one. Icon set (FT-01) — generated from the source artwork by scripts/make-icons.py , for Windows, macOS and Linux plus the website favicons. Sizes at or below 48px use a glyph-only \"F\" variant, because the wordmark baked into the artwork is illegible below 64px (measured, not guessed). The character-based teleprompter engine (FT-02) — teleprompter.rs and its TypeScript twin ui/src/lib/caesura.ts , ported from Freally Capture: visible-character scroll offsets, inline -- caesura pauses ( --2 for a custom hold), seek/step/speed controls, and a start-countdown pre-roll. Preview and projector lay text on one fixed-width stage and CSS-scale it, so they wrap at the identical column. Single-window app shell (FT-03) — toolbar, script input, and the live prompter surface, with Settings on the draft/apply pattern (nothing takes effect until Apply; Cancel restores exactly what you had) and an 18-locale Fluent i18n foundation. Docs site "
 },
 {
  "url": "changelog.html#0-100-0-2026-07-21-notes",
  "heading": "Notes",
  "text": "No AI, no accounts, no telemetry. The only outbound request is the update check; it sends nothing about you, your machine, or your scripts. Download links on the site are placeholders until the release pipeline lands."
 },
 {
  "url": "changelog.html#0-100-0-2026-07-21-known-limitations",
  "heading": "Known limitations",
  "text": "There are no installers yet. 0.100.0 is a source milestone; the signed, per-OS release pipeline is a later phase. Automatic updates are not active. The updater ships without its signing public key, so it refuses every package rather than installing an unverified one — it fails safe, but it also cannot succeed. \"Check for updates\" will report an error until code signing lands."
 }
];
